### ISSUE TITLE
Bug: Can't load Levequests

### ISSUE THREAD

**Issue by Dragonscraft** [ffxiv-teamcraft/ffxiv-teamcraft#1004]
**Describe the bug**
When selecting the Job it returns an empty screen.

**To Reproduce**
1. Go to 'https://ffxivteamcraft.com/levequests'
2. Click on 'Select a job'
3. Scroll down and select any Job
4. See empty screen

**Expected behavior**
Show Levequest list.

**Screenshots**
![chrome_2019-07-03_13-27-57](https://user-images.githubusercontent.com/52477166/60563565-4e40c180-9d97-11e9-9640-64e5f97e31d9.png)

**Additional context**
An Example Request URL found when changing the job is: 
[https://xivapi.com/Search?indexes=leve&string=&filters=ClassJobCategoryTargetID=9,ClassJobLevel>=1,ClassJobLevel<=10&columns=LevelLevemete.Map.ID,CraftLeve.Item0TargetID,CraftLeve.Item0.Icon,CraftLeve.ItemCount0,CraftLeve.ItemCount1,CraftLeve.ItemCount2,CraftLeve.ItemCount3,CraftLeve.Repeats,Name_*,GilReward,ExpReward,ClassJobCategoryTargetID,ClassJobLevel,LevelLevemete.Map.PlaceNameTargetID,LevelLevemete.Y,PlaceNameStart.ID,ID&limit=105](https://xivapi.com/Search?indexes=leve&string=&filters=ClassJobCategoryTargetID=9,ClassJobLevel>=1,ClassJobLevel<=10&columns=LevelLevemete.Map.ID,CraftLeve.Item0TargetID,CraftLeve.Item0.Icon,CraftLeve.ItemCount0,CraftLeve.ItemCount1,CraftLeve.ItemCount2,CraftLeve.ItemCount3,CraftLeve.Repeats,Name_*,GilReward,ExpReward,ClassJobCategoryTargetID,ClassJobLevel,LevelLevemete.Map.PlaceNameTargetID,LevelLevemete.Y,PlaceNameStart.ID,ID&limit=105) 

returns Status code 500 with the following JSON Response:

{"Error":true,"Subject":"XIVAPI ERROR","Note":"Get on discord: https:\/\/discord.gg\/MFFVHWC and complain to @Vekien :)","Message":"No alive nodes found in your cluster","Hash":"a3b4ade96553d37ad2c409c9016d3aae1421fe71","Ex":"Exception","Url":"http:\/\/xivapi.com\/search?columns=LevelLevemete.Map.ID%2CCraftLeve.Item0TargetID%2CCraftLeve.Item0.Icon%2CCraftLeve.ItemCount0%2CCraftLeve.ItemCount1%2CCraftLeve.ItemCount2%2CCraftLeve.ItemCount3%2CCraftLeve.Repeats%2CName_%2A%2CGilReward%2CExpReward%2CClassJobCategoryTargetID%2CClassJobLevel%2CLevelLevemete.Map.PlaceNameTargetID%2CLevelLevemete.Y%2CPlaceNameStart.ID%2CID\u0026filters=ClassJobCategoryTargetID%3D9%2CClassJobLevel%3E%3D1%2CClassJobLevel%3C%3D10\u0026indexes=leve\u0026limit=105\u0026string=","Debug":{"ID":"D7a7qrpy19070304","File":"#97 xivapi.com\/src\/Service\/Search\/Search.php","Method":"GET","Path":"\/search","Action":"App\\Controller\\SearchController::search","Code":500,"Date":"2019-07-03 04:28:32","Env":"prod"}}

**Comment by Supamiu** [comment]
It seems like this was a bug on xivapi's end, and it seems like they fixed it. Can you confirm this fixed the bug in Teamcraft as well? 😄

**Comment by Dragonscraft** [comment]
Yes now is working!

Sorry to bother

Thank you very much
