### ISSUE TITLE
Bug: White Clay Gathering alarm is incorrect

### ISSUE THREAD

**Issue by Hinalover** [ffxiv-teamcraft/ffxiv-teamcraft#1013]
**Describe the bug**
The White Clay gathering item alarm is currently set to 8 AM.

**Expected behavior**
The item does not show up until 8 PM.

**Screenshots**
I'm attaching a screanshot of the Gathering log with the time stamps

![White Clay](https://user-images.githubusercontent.com/10355909/60699197-dc649700-9ec0-11e9-86a5-04c20b2dd1ed.PNG)

**Comment by Supamiu** [comment]
I corrected data in https://docs.google.com/spreadsheets/d/1hEj9KCDv0TT1NiGJ0S7afS4hfGMPb6tetqXQetYETUE/edit#gid=1571190523 and will update the data source soon (during the next couple of hours). Once it's done, you'll have to delete and create the alarm again to have its time properly set :)

Thank you for the report
