### ISSUE TITLE
bug: cannot open alarm overlay

### ISSUE THREAD

**Issue by efreebairn** [ffxiv-teamcraft/ffxiv-teamcraft#1030]
**Describe the bug**
When I try to open the alarm overlay, I get a popup error message.

**To Reproduce**
1. Go to Alarms page.
2. Click on "Open Overlay" icon
3. See error

**Expected behavior**
Have the overlay open.

**Screenshots**
![teamcraftbug](https://user-images.githubusercontent.com/9341714/61178576-88367280-a5a4-11e9-9abe-b13874271bda.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 5.6.12

**Additional context**

**Comment by Supamiu** [comment]
Fixed in 5.6.13, or you can re-download the 5.6.12 release on https://ffxivteamcraft.com/desktop
