### ISSUE TITLE
feat:Rotation tags w/o needing to be community rotation

### ISSUE THREAD

**Issue by MDlumia** [ffxiv-teamcraft/ffxiv-teamcraft#1039]
*please prefix the issue with "feat:", example: "feat: commission board system"*

**Is your feature request related to a problem? Please describe.**
Yes, it is related to a QoL issue i seemed to have had with rotation tags, and telling what a rotation is at a glance.
**Describe the solution you'd like**
The ablity to use rotation tags/ Metadata that the community rotations feature sports without having to have the rotation set as a  community rotation. 
**Describe alternatives you've considered**
i have been currently using shorthand in Rotation titles to indicate tags/ metadata. but it kind of cumbersome at times.  other ideas might be to set comments or notes on the individual rotation.  
**Additional context**
When i talked to Miu on this issue you they did say it was kind of hard but also worth making a issue, in case  it could become a reality.

**Comment by Supamiu** [comment]
After thinking more about it, I don't think it's a good idea as the tags are handled inside the community rotation window.

That being said, you can input a name as long as you wish, and add tags in form of strings to find a rotation easily. That's how most people who have this issue are doing, and I think it's the best way to do it.
