### ISSUE TITLE
bug:Wrong values in Custom Simulator

### ISSUE THREAD

**Issue by Mephi-Dross** [ffxiv-teamcraft/ffxiv-teamcraft#1048]
**Describe the bug**
Using the crafting simulator in Custom mode allows you to configure the Recipe, as well as your normal crafter statistics at the top. This works fine when you're staying on the page, but reloading the page (e.g. saving and reopening the rotation at a later date) will cause the values to change:
-The recipe configuration resets the values to (at the time of this report) a r430 80 Duration item (e.g. Dwarven Cotton Jacket).
-The crafter configuration interacts oddly with any boni applied from consumables. Every time you reload the page it applies the consumable buffs to the base stats and then adds the consumable buffs as boni again.

**To Reproduce**
1. Go to Crafting Simulator and select "Create a custom rotation"
2. Enter the desired values and create a rotation.
3. Save your new rotation.
4. Go to Crafting Rotations and open the newly created rotation in the Simulator.
5. Compare expected values with actual values.

**Expected behavior**
When loading the crafting rotations I would expect the custom recipe values to be loaded correctly. I would also expect that the consumable buffs are not applied to the base stats.

**Screenshots**
[Set Values](https://i.imgur.com/ccE06XF.jpg)
[Loaded Values](https://i.imgur.com/86xkdeS.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox 68.0.1
 - Version 5.6.18 of App
For questions you can reach me on Discord: Mephi-Dross#0945

**Comment by Supamiu** [comment]
This has been fixed in 5.6.19 :)
