### ISSUE TITLE
ACT plugin

### ISSUE THREAD

**Issue by easly1989** [ffxiv-teamcraft/ffxiv-teamcraft#1049]
As an heavy ACT user and dev,
Do you have in mind to develop a plugin for ACT that does what your desktop app do?

Thank you for the answer, and all your work!

**Comment by Supamiu** [comment]
What would be the benefits of such a plugin? It's a full JS client so I believe it can be started inside ACT, but I don't really see the benefits of it.

**Comment by easly1989** [comment]
Well, 
beside being able to use the FFXIV parsing plugin to know when the timers could be stopped (hidden maybe), for example when you are in a duty and unable to gather while you are in!

It also would reduce the number of applications open/needed to install (as it would be integrated there)

**Comment by Rietty** [comment]
This seems messy and unnecessary. Why not just turn off the alarms when you start raiding? It's a quick toggle. Or you know, just ignore them?

**Comment by easly1989** [comment]
Yeah, i know that we can manually turn them off.. but why if we could do that automatically?
Anyway, the main reason, at least for me, for an ACT plugin would be the integration in that software.
Giving the possibility to just execute one software to handle all the necessary things someone wants (including the timers).

All the good things that could come out of this kind of plugin would also be welcome.

**Comment by Rietty** [comment]
ACT is a Combat Tracker, this literally would feel like shoe-horning in an extra thing that practically no one will use. I don't know about you, but when I'm crafting I never have ACT up, only when actually raiding.

**Comment by easly1989** [comment]
It is indeed a Combat Tracker as the name says.
But it is actually a lot more than that, and while someone uses it only for raiding others uses it other things, like hunting or duty finder notifications to menton some. 

So, it is just a matter of what one wants to use it for.. 

I do have it always on, even when I'm not doing anything special 😅
