### ISSUE TITLE
bug: incorrect field names for custom recipe configuration

### ISSUE THREAD

**Issue by AzariahAeroborn** [ffxiv-teamcraft/ffxiv-teamcraft#1055]
**Describe the bug**
The labels for the "progress" and "durability" fields in the Recipe Configuration window in the simulator when creating a custom recipe are swapped.

**To Reproduce**
1. Go to 'https://ffxivteamcraft.com/simulator/custom'
2. Observe the labeling of the fields in the Recipe Configuration section

**Expected behavior**
- The third box (default value of 70) is labeled Durability
- The fifth box (default value of 5654) is labeled Progress

**Actual behavior**
- Labels are switched

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest stable (75.0.3770.142 (Official Build) (64-bit) (cohort: Stable))

**Comment by Supamiu** [comment]
Clsoed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/1757ed2c469e81927924cb5485cba1ce2000cbb8
