### ISSUE TITLE
bug: [Simulator] "ingenuity II" providing same boosts as "ingenuity"

### ISSUE THREAD

**Issue by wahr01** [ffxiv-teamcraft/ffxiv-teamcraft#1058]
## I'm submitting a...
* (X) Bug report *- please add **bug:** before the title*

### Browser
brave

Have you disabled script-/adblockers before submitting? Y

## Current behavior
There is currently no difference in progress or quality between the use of ingenuity and ingenuity II
## Expected behavior
"Ingenuity II" should provide a higher boost to quality and progress than ingenuity, so 'upgrading' ingenuity in a given rotation to ingenuity II should result in greater quality/progress.

## Steps to reproduce
1 - create a crafting rotation in the simulator for facet earrings of slaying utilizing "ingenuity" to boost various parts of the rotation (byregot, a set of prudent touches, doesn't matter).
2 - export as a FFXIV macro
3 - edit the macro to change "ingenuity" to "ingenuity II"
4 - note current quality and progress states, then import new macro tot he same rotation.
there is no change in the end result.

**Comment by Supamiu** [comment]
Hello,

Did you check that this wasn't the case ingame? Both Ingenuity 1 and 2 are bringing level difference over the cap, which is why they both have the same effect, this will be the case ingame and we have checked it.
