### ISSUE TITLE
feat: manual starting quality for crafting simulator

### ISSUE THREAD

**Issue by Sephiroth018** [ffxiv-teamcraft/ffxiv-teamcraft#1117]
**Is your feature request related to a problem? Please describe.**
As a crafter, I would like to be able to simulate using HQ materials even if the information for them is missing in the database (as is the case for at least a number of <50 recipes).

**Describe the solution you'd like**
A quick and easy way to solve this problem would be to be able to set a starting quality.

**Describe alternatives you've considered**
An alternative would be to still display the ingredients in the HQ ingredients section and add a field to set the quality they add, if it is unknown.

**Comment by Supamiu** [comment]
Hi, 

Thank you for your suggestion, I'm going to add an input field for initial quality in case ingredients are missing.
