### ISSUE TITLE
Feat: Setting to prefer gathering/buying mats

### ISSUE THREAD

**Issue by NocturneBlock** [ffxiv-teamcraft/ffxiv-teamcraft#1119]
**Is your feature request related to a problem? Please describe.**
I have matching DoH/L levels and don't do much in the way of specifically earning Gil, so the current behavior of putting anything that can be purchased into the Vendor category, even if it can also be gathered/hunted is not desirable for me. 

**Describe the solution you'd like**
I would like to add to the per-list toggles one or more settings to determine if Vendor or other categories should be preferred if the item can both be purchased and gathered/hunted. Personally, I would separate hunted items (such as skins) from items directly gathered by DoL classes, as I don't mind gathering, but prefer not to grind for mats. Others might be in the opposite situation. 

**Describe alternatives you've considered**
Currently, I just check to see if any of the items in Vendor can be acquired another way, but that is suboptimal for organizing large team projects. 

I also considered more of fewer toggles, such as one per DoL category, so that people who don't have all the DoL classes available on the team can, for example, prefer to gather mined resources and buy the others. That would work fine for me as well, but I don't know if it would be excess granularity for most users. 

**Additional context**
Nothing I can think of.

**Comment by Supamiu** [comment]
Hello, thank you for your suggestion.

However, this is already possible 😃 

All the panels and the way they are ordered and displayed can be customized, see [the wiki guide on how to edit layouts](https://wiki.ffxivteamcraft.com/base-features/layout-system).

Once this is done, you can switch from one layout to another by hovering the quick layout swap button:
![image](https://user-images.githubusercontent.com/11519203/66337333-3dc45800-e93f-11e9-9c7d-be620ec8980f.png)

**Comment by NocturneBlock** [comment]
Ah, okay. Then maybe a quick, likely optional, button tour or something? I could record one for you if I knew what everything does. Because that didn't occur to me as the place to look for that solution. Also got some wonky behavior while setting up my layouts, but I eventually got them to cooperate. So, yeah, you can consider this one closed.
