### ISSUE TITLE
feat: Ability to select multiple items from one search

### ISSUE THREAD

**Issue by NocturneBlock** [ffxiv-teamcraft/ffxiv-teamcraft#1121]
**Describe the solution you'd like**
When searching for items to add to a list, I would like to be able to select multiple items without the popup closing.

For example, if I am making a set of hempen gear, I would like to be able to search for "hempen", and check all the items I need, rather than having to do the same search multiple times. I.e., similar behavior to Crafting as a Service's lookup.

This could either be achieved by offering a setting that turns item selection from a one-click action to an arbitrary number of select-item actions, and then a commit, or a toggle in the search box to check (or uncheck) to determine whether this particular search is a one-hit or many, applying the described behavior only if the toggle is active.

**Describe alternatives you've considered**
None, really, it's a fairly simple change, but one that could have a major effect on user experience when doing large crafting lists with items of the same grouping.

**Comment by Supamiu** [comment]
You can already do that by checking the checkboxes next to each item you want to add, them use the "Add selection to a list" button that is shown above the results.

**Comment by NocturneBlock** [comment]
As soon as I hit any of the checkboxes, the window closes. Are you referring to when I use the "Add Item to List" button in the list itself, or another screen?
