### ISSUE TITLE
Bug: Mahi-Mahi Fish level mismarked

### ISSUE THREAD

**Issue by Hinalover** [ffxiv-teamcraft/ffxiv-teamcraft#1136]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
The Mahi-Mahi fish is categorized as being a level 10 fish. However it is in reality a level 50 1-star fish. It is just that it is fished up from a level 10 fishing hole.

**To Reproduce**
Create a List for a Pan-fried Mahi-Mahi

In List it will show up as a level 10 fish

**Expected behavior**
It should show as a "50*" fish

**Screenshots**

![image](https://user-images.githubusercontent.com/10355909/67257364-9f191a80-f459-11e9-8638-c50ec2419da6.png)

![image](https://user-images.githubusercontent.com/10355909/67257380-adffcd00-f459-11e9-8e88-8f474acba45a.png)

![image](https://user-images.githubusercontent.com/10355909/67257396-c374f700-f459-11e9-93c7-06b7f79b9f83.png)

**Comment by Supamiu** [comment]
This cannot be fixed because all we have as data is the spot's level, not the fish level :/ I'll see if some stuff inside data can be changed for this but for now, it's far from being possible.
