### ISSUE TITLE
Feat: Control-F to Find text on the page in the Desktop app

### ISSUE THREAD

**Issue by NocturneBlock** [ffxiv-teamcraft/ffxiv-teamcraft#1144]
When using Teamcraft as a website, it is easy to find specific items in long lists by just hitting Control-F and searching for the text you want. I prefer the desktop app to the website for most things, but I sorely miss this ability when I am working with large shared projects.

Ideally, I would like a search bar similar to what is in my browser, which includes the field for searching, "Next" and "Previous" buttons to move up and down through instances of the searched text, a button to highlight all instances of the text, and tickboxes to toggle "Match Case" and "Whole Words". If it is not possible to have all of that, the highlight would be the first thing I would cut, then the filtering for matching case and whole words.

**Comment by Supamiu** [comment]
I'm closing this because it cannot be done properly using the electron API
