### ISSUE TITLE
bug: desktop: extremely high CPU usage on large lists with packet capture

### ISSUE THREAD

**Issue by sandsong** [ffxiv-teamcraft/ffxiv-teamcraft#1196]
Description:

When updating items in a large list, the interface becomes unresponsive and the CPU usage spikes to close to 100%.

**To Reproduce**
1. Make sure packet capture is enabled.
2. Create a large list, say for completing a section of the crafting log.
3. Attempt to check off an item.
4. CPU usage maxes out, interface becomes unresponsive.

**Expected behavior**
Either the interface continues to function while the model updates; or there is no extended CPU spike.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Desktop app
 - Version 6.16

**Comment by Supamiu** [comment]
Hi, thank you for your report 🙂

Were you in a crowded city when you reproduced the bug?

**Comment by sandsong** [comment]
I mostly observed it in the wild, while gathering.

**Comment by Supamiu** [comment]
I am adding more packet filtering with next patch (6.1.7) and i'll also try to work on list screen performances, please try again once 6.1.7 is out to report potential improvements :)

**Comment by DingFandango** [comment]
The CPU usage on my end is not high, but I noticed on large lists (like GC supply lists), the client will run smoothly and autofill/auto sound notification as soon as I complete a listing, but when I get halfway through the list or more it takes several seconds up to even a whole minute before the client catches up and actually pings a notification. The client also goes from heavily laggy to completely unresponsive when I am waiting for the autofill to work on larger lists.

**Comment by sandsong** [comment]
I tested on a very large list of 65 items. I noticed brief CPU bursts and associated UI hangs of a few seconds. While gathering, however, I noticed much longer UI hangs and lengthier periods of high CPU usage.

**Comment by DingFandango** [comment]
Seconding @sandsong When gathering the client goes unresponsive for much longer times than just taking items from retainer or crafting them.
