### ISSUE TITLE
bug: just found that I can't search the item start from "霊" in Japanese

### ISSUE THREAD

**Issue by Kaiay** [ffxiv-teamcraft/ffxiv-teamcraft#1211]
**Describe the bug**
can't search the item name start from "霊"
example: "霊青材" "霊青岩"

**To Reproduce**
1. Go to search
2. type "霊青材"/"霊青岩"/"霊青"/"霊"
3. Show no data(but there are those item in database that can find by other ways)

**Expected behavior**
show the items that i'm searching.

**Desktop (please complete the following information):**
 - OS: both iOS, Windows app and windows web.
 - Browser: chrome,desktop app
 - Version: 6.1.11

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 13.2
 - Browser: safari

**Comment by karashiiro** [comment]
Hello, can you try searching for 「霊青打刀」?

**Comment by Kaiay** [comment]
Hi there."霊青打刀" is work. But the others still can't find.
Also find that "桜貝"/"桜吹雪" can't find by search
Is that i'm the only guy facing this problem?

**Comment by Supamiu** [comment]
The issue comes from the fact that search is only fired when you input at least 3 characters, but using the string length as # of characters. This is bypassed for KR and CN, not for JP.

I'll add JP to the list of languages that don't have this limit in 6.1.13 :)
