### ISSUE TITLE
bug: searching community lists appears to be very flaky

### ISSUE THREAD

**Issue by aserra54** [ffxiv-teamcraft/ffxiv-teamcraft#1217]
**Describe the bug**

The community list searching feature does not appear to be matching searching lists for no obvious reason. For example, searching for "Armorer" will not return all lists with the string "Armorer" in the title.

**To Reproduce**

1. Navigate to the "Community Lists" page (`https://ffxivteamcraft.com/community-lists`).
2. Type 'Armorer' in the search field.
3. Keep track of the lists returned.
4. Delete 'Armorer' from the search field, and enter 'ARM' in the tag field.
5. Observe that lists with the string 'Armorer' appear, but did not appear in the lists returned in step 3.

**Expected behavior**

All lists with the string 'Armorer' in them are returned.

**Screenshots**
![lists-armorer](https://user-images.githubusercontent.com/3211528/68548838-433e1380-03bf-11ea-8348-878750a2b044.png)
![lists-arm](https://user-images.githubusercontent.com/3211528/68548839-433e1380-03bf-11ea-90ad-8f4ef506d85d.png)

Observe that the lists highlighted in the second image (using the tag 'ARM') have the term 'Armorer' in them, but were not returned in the first list selection (using the search phrase 'Armorer').

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox
 - Version: v6.1.1.2

**Comment by Supamiu** [comment]
This is because the search field uses Firestore's native search for "string contains", which is the only option to avoid freezing the page due to an OOM error.

It can't be fixed until firestore has a proper string search system.

**Comment by Supamiu** [comment]
I'm closing this as it depends on firestore, not us :/
