### ISSUE TITLE
Bug: Mark as HQ Required still counts NQ items

### ISSUE THREAD

**Issue by DingFandango** [ffxiv-teamcraft/ffxiv-teamcraft#1245]
**Describe the bug**
When marking an item as HQ Required and beginning gathering said item, the list tracker will autofill the item even when you collect NQ variants and will complete the listing despite having no HQ. 

**To Reproduce**
1. Create a list for a recipe
2. Set item(s) as HQ Required
3. Take items from retainer/gather items as NQ
4. Watch Teamcraft count NQ items as "HQ"

 

**Expected behavior**
When an item is Marked as HQ, I expected it to only track and autofill items that are HQ and ignore counting the NQ items towards the list.

**Screenshots**
![ffxiv-teamcraft_2019-11-23_09-24-53](https://user-images.githubusercontent.com/23725766/69482667-2a782980-0dd3-11ea-9fa2-d1d582586c6e.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Browser [e.g. chrome, safari, desktop app]
 - Version 6.2.6

**Comment by Supamiu** [comment]
This is not a bug in fact. The HQ mark is "you might want this HQ" not a filter.

A feature is being considered for that but it has not been created yet.
