### ISSUE TITLE
Bug: New patch on Nov 26 2019 breaks packet sniffing 

### ISSUE THREAD

**Issue by Nowbob** [ffxiv-teamcraft/ffxiv-teamcraft#1250]
I'm on windows 10 pro using the desktop app

## Current behavior
Freshly opening both the game and the app, I am unable to get inventories to update. If I try to tick "Autofill" on lists, I get the popup to change zone to update inventories (which I've done before and seen work) but it never seems to pick it up. It also doesn't pick up anything when I complete crafts or gather items.

## Expected behavior
Expect popup to go away and update after I tele to different zone, expect items to update as I get them.

## Steps to reproduce
Open game
Open desktop app and go into a list, tick "Autofill" and see the "Your inventory is outdated" popup.
Teleport to different zone(s) in game (I don't know if it matters but I go to completely different maps, i.e. gridania to eulmore to mor dhona etc.)
Popup stays open in app.

**Comment by Nowbob** [comment]
You know what, after some thinking I'm wondering if this isn't to be expected after patches, and I'm just jumping the gun on this, apologies if that is the case.

**Comment by Supamiu** [comment]
This is known and it's going to happen with every sinle patch :/ it needs some time to properly be fixed.
