### ISSUE TITLE
Cannot find module '.playTime.js' - 6.2.8

### ISSUE THREAD

**Issue by m4chinations** [ffxiv-teamcraft/ffxiv-teamcraft#1253]
Hey, I just installed version 6.2.8 and I'm getting this error. 

"Uncaught Exception: Error: Cannot find module './playTime.js'"

Teamcraft doesn't open :c 

Windows 10.

**Comment by m4chinations** [comment]
Definitely has something to do with https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/compare/v6.2.8...staging#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R181

**Comment by Supamiu** [comment]
Fixed in 6.2.9
