### ISSUE TITLE
**feat** - User (possibility developer too) friendly updating

### ISSUE THREAD

**Issue by porisius** [ffxiv-teamcraft/ffxiv-teamcraft#1265]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (X) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing
Update TeamCraft as an installation file for updates to the core application, and not every little change. Have TC check for asset updates and auto download/update as necessary.

## What is the use case for this feature?
First, you wouldn't need to recreate a new MSI/Release file every other day/update. This should help cut down on some work for the TC Dev team.

Second, user friendliness, I have had a few of my LS and FC mates ask me (I work as a Server Admin) what I could do about the constant having to install TC updates. So, I can't be the only one. Downloading a 117MB file to make 117KB worth of changes is rather inefficient.

These are my thoughts. I know ngld and his/her OverlayPlugin has the core application, and then downloads the rest as needed. However, I am no developer, so I am not sure what kind of re-write that would require. Do take a look though and see if it would make your lives (and ours) better.

In theory, TC should get to a point where updates should only be needed around patch releases of XIV, unless you have a feature update or bug fixes from outside sources.

**Comment by KhloeLeclair** [comment]
I was coming to request this myself. If nothing else, could we please get an update flow more like most other electron apps where the app just updates itself automatically prior to launching with no user interaction? 

The size of the download, while inefficient, doesn't matter much to me. What gets me is having to confirm that we want to update (when the outdated app often doesn't work in the first place without doing so), then allowing the setup to run as administrator, and clicking through the setup, then clicking to allow Teamcraft itself to run as administrator *again* is just frustrating.

**Comment by Supamiu** [comment]
Hey, thank you for your suggestions :)

I'm investigating on this topic because like a lot of players, I have a slow connection, and 117MB is super slow for me to download. Even if everything is done in cloud (CircleCI), which makes building not hard at all, no matter the size of the setup.

I'm looking at Squirrel at the moment, which seems to be the solution used by many apps, downloading patches instead of a full app everytime as you mentionned. But I'm not sure it'll be able to do everything that the current solution (nsis) does.

Another solution would be to get assets from web even using desktop app, but that would make no sense to me as it would mean that you have a desktop app that can't load files from filesystem, which is way faster than web no matter what.

**Comment by porisius** [comment]
Hey, if you need a willing test dummy/lab rat, let me know. I'll be glad to assist. AFAIC, I started it, I should be willing to help make it happen.

One suggestion, have it pull from the web and cache it, and maybe have that cache check itself on change of screen/window. Sure, the first pull will take a moment, but once they have the majority of the assets, it should go quick. I really am not sure how that would be done for this, especially keeping features like communication with Unversalis. IIRC, the Web version of TC asks you to refresh the page when the TC Devs push updates.

I use nginx for a LANCache at home for Blizzard/Steam/FFXIV. For the FFXIV 5.0 Release, one member of the house fought for about 6-8 hours to download it as they were the first during the rush, but it took me 8 minutes straight shot/no problem as soon as they completed. Not sure how that will compare to TC, but thought I would give it perspective.

**Comment by Supamiu** [comment]
Did 6.3.3 solve the issue for you?

**Comment by porisius** [comment]
@Supamiu, to be honest, I hadn't seen an update come across lately. Either y'all took a break for the holidays, or the async change in the code did it.

I didn't have an "issue" per say, I had only a feature request/suggestion. It doesn't feel like there has been a new update, so I think you guys did pretty well. Close if you think it has been added.

**Comment by Supamiu** [comment]
I'm closing for now :) feel free to comment again if you think it's not properly done yet :)
