### ISSUE TITLE
Bug: moving items in inventory adds to amount in autofill

### ISSUE THREAD

**Issue by Nowbob** [ffxiv-teamcraft/ffxiv-teamcraft#1280]
**Describe the bug**
When using "Autofill" in a list, if you drag items around your inventory, it adds the stack to your collected items total.

**To Reproduce**
1. Open a list and select "Autofill"
2. Have an item in your inventory that is part of your teamcraft list
3. Drag item to any other slot in your inventory

**Expected behavior**
Not having the item counted additional times on the autofill list

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 6.3.3 Desktop App

**Comment by Supamiu** [comment]
This has been fixed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/80a85e634e889fc989114a1f68828c0507b157bc and will be in 6.3.4 :)
