### ISSUE TITLE
feat: setting to autofill only with HQ items when marked as HQ

### ISSUE THREAD

**Issue by pokeguru87** [ffxiv-teamcraft/ffxiv-teamcraft#1281]
## Environment
Windows 10 Version 1909

## Current behavior
When an item is marked as HQ required in a List and it is autofilling with Packet Capture it will count NQ items towards its completion.

## Expected behavior
Only HQ items should count.

## Steps to reproduce
1. Create List, Enable Autofill
2. Mark Item as HQ Required
3. Collect Item In game

**Comment by Supamiu** [comment]
Hello,

This isn't a bug because the HQ mark doesn't mean "required as HQ" but "you might want this HQ", hovering it shows the exact signification.

However, I'm keeping this opened because I would like to add an option to do this.

**Comment by pokeguru87** [comment]
My bad. The wording in the menu said "Mark as HQ Required," so I assumed that would be the behavior. It would very much be a nice feature to have though.
