### ISSUE TITLE
feat: installer debug information

### ISSUE THREAD

**Issue by bgwendling** [ffxiv-teamcraft/ffxiv-teamcraft#1283]
**Is your feature request related to a problem? Please describe.**
I've been trying to update ffxiv teamcraft, but every time the installer stops partways in with the message "Installation Aborted; Setup was not completed successfully."

That makes me think "Oh gee, thank you Sherlock" and doesn't offer me any other useful information than the obvious. (Though it is nice to know that the installation stopped, rather than froze or the like).

**Describe the solution you'd like**
Print out debug information on installation error, doesn't have to be super legible or anything, something like x went wrong in y location, and I'd be happy to go into the source to try to figure out what the issue was.

(just printing out the exception that happened, or exception + stacktrace would be wonderful)

**Describe alternatives you've considered**
Log files would also be a wonderful alternative.

**Comment by Supamiu** [comment]
It seems like this cannot be done, because of the fact that NSIS doesn't have a way to log stuff: https://github.com/electron-userland/electron-builder/issues/2691

That being said, I feel like this is just a case of corrupted installer or Teamcraft is still running in the background (check your tray bar). These are the only real two cases where the installer doesn't work properly.

**Comment by bgwendling** [comment]
Ahh... That's too shabby. Checked traybar, and running processes, as well as running a clean reboot of win10. And the installer still fails to install.

Some info which might be useful:
Had older version installed
Installed newer version with some issues (can't quite recall what it was)
Tried reinstalling newer version, it didn't work.
Deleted the folders within appdata roaming & local.
Now I'm stuck on installer failing consistently.

Are there any other folders I'd need to delete in order to get a completely fresh install, apart from those in appdata?

**Comment by Supamiu** [comment]
I would just run the uninstaller in this case, in order to make sure everything, including registry, is cleaned, it should help with that.
[uninstaller.zip](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/files/3937284/uninstaller.zip)

**Comment by bgwendling** [comment]
Ahh... Sorry for the late reply, been a bit busy, your sollution worked!

I'll let you handle closing the issue (and decide on wether or not you'd like to keep it open for the sake of the potential feature in question or not... Though it definitely does sound close-worthy, or at the very least, quite far down the backlog)

**Comment by Supamiu** [comment]
I'm closing it :)
