### ISSUE TITLE
**bug** Eorzean time in Teamcraft desktop app does not match in game time

### ISSUE THREAD

**Issue by laelipoo** [ffxiv-teamcraft/ffxiv-teamcraft#1290]
## I'm submitting a...
* (x) Bug report

## Expected behavior
time should match exactly so alarms will match when nodes are up/fish are up.  Please see below screenshot with the two times circled.
![image](https://user-images.githubusercontent.com/58866865/70838554-dad7bd00-1dd6-11ea-8961-fb7540ee46fd.png)

**Comment by Supamiu** [comment]
Hello,

This issue is because your windows time is unsync'd, see https://time.is/

In order to resync it, simply disable auto time sync in windows and enable it again.

**Comment by laelipoo** [comment]
yes, this did correct.  thank you for your assistance.
