### ISSUE TITLE
Bug: Packet capture feature not working anymore since 5.18

### ISSUE THREAD

**Issue by Neoware** [ffxiv-teamcraft/ffxiv-teamcraft#1304]
Hello @Supamiu and thanks for the awesome tool !

It seems that the FFXIV 5.18 update of today broke the packet capture. I tried on 2 different computers to be sure :)

Version is the current 6.5.3

## Current behavior
Impossible to load inventory and all packet capture related stuff.
## Expected behavior
Working realtime inventory.
## Steps to reproduce
Launch the game, reset inventory, teleport to trigger an inventory loading.

Thanks in advance !

**Comment by Supamiu** [comment]
This happens on every patch and will be fixed during 26th of december. I'm closing it as it'll be the same on every single patch

**Comment by damianb** [comment]
@Supamiu Perhaps it'd be a good idea to include a notification in the application going forward that indicates that it's a known issue? Put down an expected version in textools, and then in a remote API indicate the current patch of XIV - if the two are not equal via a dumb string comparison, display said message.

**Comment by Neoware** [comment]
This, or at least something in the README or in a FAQ or something that indicates this issue. I understand that it can be annoying to have issue like this created, but I really checked everywhere to get information about this kind of known non-compatibility issue but I found none :(

**Comment by Supamiu** [comment]
There's an annoucement in the discord server, and this is not using textools at all, it's only packet capture, which means that it's not that easy to detect stuff isn't working because of a version error.

Which is why there's an announcement inside the discord server, and I'm posting it on every single patch.

**Comment by Supamiu** [comment]
Also, it's usually fixed before people even notice, but today is cristmas and I'm with family so the update will wait one more day.

That was also inside the announcement ;)
