### ISSUE TITLE
Bug (6.5.6): Autofill not catching every items gathered.

### ISSUE THREAD

**Issue by Speedy321** [ffxiv-teamcraft/ffxiv-teamcraft#1313]
**Describe the bug**
When gathering, the autofill feature did not catch every item i gathered, it missed about 20% of them (over a few hours of intense gathering (1000++ items). The count for the number of items did go up properly (counting every item added).

**To Reproduce**
1. Make a list with gather-able ingredients.
2. Make sure autofill and packet capture are on.
3. Gather items (the more you gather the more the problem becomes obvious)

**Expected behavior**
Every item gathered should be added to the count.

**Screenshots**
This screenshot has been taken after gathering 664 Skybuilders' Straw without touching the app. I have seen it happen with my other mats but i was correcting it when i was seeing it.
the 20% misses from above comes from this attempt [664 - 519 = 145 missed => = 21.8% missed].
![image](https://user-images.githubusercontent.com/4757883/71606025-a7699200-2b3b-11ea-90cd-33e9b5bafa56.png)

**Desktop:**
 - OS: Win10
 - Browser: desktop app
 - Version: 6.5.6

**Additional context**
I was using quick gathering on and off through, the bug might only occur with quick gathering on, i have not been able to test if that's the case.

1- One can easily work around this and worst case, you have a few more items than what you need when the alarm goes of/you're done.

2- It MIGHT be related to network stuff outside of the app's control. but i highly doubt it, as i have fiber 1Gbps up and down. But if it is, there might be a way to mitigate the bug (periodic sync with inventory count or something).

3- I'm making this issue more to see if others can replicate and/or help me investigate further than to have it fixed right this instant.

**Comment by Speedy321** [comment]
Update:
I started at 0 in inv.
Definitively happens with quick gathering on:
![image](https://user-images.githubusercontent.com/4757883/71606364-39729a00-2b3e-11ea-9b05-f330264afd9c.png)
"Fixed" the count to 64, then gathered without quick gathering.
Still happenening without:
![image](https://user-images.githubusercontent.com/4757883/71606465-fb29aa80-2b3e-11ea-9987-49dd2050f146.png)

**Comment by Speedy321** [comment]
Update 2: 
This attempt gave me a dropped ratio of [666-562 = 104 =>] 15.62% dropped (not including the few i corrected at the beginning).
I am not able to see any kind of pattern on when/why it drops some, no (noticeable) lag spikes that caused drops or anything. Seems to drop randomly. (but i know nothing is truly random in software.)
![image](https://user-images.githubusercontent.com/4757883/71606850-6fb21880-2b42-11ea-99af-c8bd4d94b31e.png)

**Comment by Speedy321** [comment]
I also saw something similar to #1196 happen (didn't check the cpu usage) after a bit, had to restart the app because it froze after a few stutters. It hasn't dropped a autofill input since (118 items) but those items where ARR items while the ones where i saw drops where in HW zones... that might also make a difference.

**Comment by flavien-normand-cbp** [comment]
Hey, do you manage to reproduce with the latest update (6.5.11)?

**Comment by Supamiu** [comment]
Hey, do you manage to reproduce with 6.5.11?

**Comment by Speedy321** [comment]
I will have to find the time to test it, will report back when I do.
