### ISSUE TITLE
feat: set stats from profile?

### ISSUE THREAD

**Issue by windyweather** [ffxiv-teamcraft/ffxiv-teamcraft#1316]
Am I missing this. Is this feature already here, but I can't see it?
I went here and created an account:
https://ffxivteamcraft.com/simulator/

And I have several Jobs in my profile since I'm leveling all the DoH/DoL jobs.
But when I go to the simulator, I don't see a way to just fill in the configuration from my profile.
Or if I select a job and I'm logged in, why is it not just prepopulated from my profile? Duh?
Isn't that why we are saving them in the profile? I go to the profile and clickity clicktyh click click and nothing. Can't set the config in the simulator from the profile.

What am I missing?
Why is this so obscure?
What else could the data in the profile be for if it's not to set the config in the simulator?

Just make it easier to find this feature if it's there, or PUT IT IN IF ITS NOT.

Duh

**Comment by ArcaneDisgea** [comment]
> But when I go to the simulator, I don't see a way to just fill in the configuration from my profile.
> Or if I select a job and I'm logged in, why is it not just prepopulated from my profile? Duh?
It does populate from your profile.
Did you set and save your stats in your profile on teamcraft? 

![image](https://user-images.githubusercontent.com/39720490/71771044-03993100-2f03-11ea-8911-51b4b0ae9c4b.png)

If you have then they will automatically be applied in the simulator. I can't tell you what you are missing but it is certainly not obscure.

What version of the app are you using? What operating system? Do you have any errors inside the console when you go to the simulator?

**Comment by windyweather** [comment]
I'm sorry, my bad. I had pulled up a LTW recipe, but had only filled in the CRP profile.
No App, Win 10. FFox 71. Again, looks like it works fine. Sorry for my frustration. But the site works exactly as I would want. Thanks.

**Comment by ArcaneDisgea** [comment]
All good @Supamiu can close this issue when he is back from vacation.
