### ISSUE TITLE
[Bug] Searching Items to Add to List in Japanese

### ISSUE THREAD

**Issue by MCAxiaz** [ffxiv-teamcraft/ffxiv-teamcraft#1318]
**Describe the bug**
When searching for items to add to list in Japanese, it appears the search requires 4 characters before firing. But many items have names that have less than that amount of characters.

**To Reproduce**
1. Switch to Japanese
2. Create a list
3. Add Item to list
4. Enter search that has < 4 characters.

**Expected behavior**
Search fires.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 71.0

**Comment by ayyaruq** [comment]
Known issue, also also applies to KR and CN users. I believe the fix would be a mix of stuff we do in TC, and tuning the ngram tokeniser for the Name_JP/ZH/KO field matchers in xivapi.
