### ISSUE TITLE
BUG: Desktop App Black Screen When Trying to Add Items to a List

### ISSUE THREAD

**Issue by sumphatguy** [ffxiv-teamcraft/ffxiv-teamcraft#1319]
BUG: Desktop App Black Screen When Trying to Add Items to a List

**Describe the bug**
When going to create a list in the desktop app for crafting, the entire desktop application window goes black and the entire app has to be restarted to resume normal functionality. The browser version is not doing this.

**To Reproduce**
1. Go to the lists tab and attempt to add an item to an existing list.

2. Start typing in the name of the item.

3. Screen goes black.

Also occurs when trying to create a new list and typing in the list name, or attempting to open a list made in the web browser.
**Expected behavior**
The screen shouldn't go black.

**Screenshots**

![Image of Black Screen](https://user-images.githubusercontent.com/32505187/71818964-749e2d00-3058-11ea-9305-262d46352c90.PNG)

![Example Text Box that made screen go black](https://user-images.githubusercontent.com/32505187/71819164-19206f00-3059-11ea-95f4-8551431bed20.PNG)

**Desktop**
 - OS: Windows 10 Desktop App
 - Version: 6.5.6

**Comment by Strati** [comment]
I'm unable to duplicate this, everything works fine on my end. Could you try clearing the desktop app's cache and trying again? 
![image](https://user-images.githubusercontent.com/59393535/72045805-9e379e00-327c-11ea-9fca-d8ff97d916a8.png)

**Comment by sumphatguy** [comment]
I did as you instructed, and now when I try to sign in, the screen goes black when I start to type my email address. Whatever is causing it is something to do with the popups. I'll try reinstalling the app completely next.

**Comment by Supamiu** [comment]
I'm closing for now as i cannot be reproduced, if you manage to reproduce it in a reliable way, please feel free to reopen this issue and leave a comment :)
