### ISSUE TITLE
feat: combine lists

### ISSUE THREAD

**Issue by doubleyewdee** [ffxiv-teamcraft/ffxiv-teamcraft#1336]
**Is your feature request related to a problem? Please describe.**
I sometimes want to combine two or three community lists into a personal list for bigger projects. E.g. just now an FC-mate wanted the 71 i330 DoH+DoL stuff, and that ended up being in community lists (great!) but it was 3 different ones. I ended up re-generating to give them a link to all the mats I need, but it was a bit tedious.

**Describe the solution you'd like**
A couple ideas here:
1) 'Combine lists' function in the hamburger (...) dropdown in lists UI
2) 'Save list to existing ...' to save a community list's items into my existing list

**Describe alternatives you've considered**
"add all items from list" paste mechanism where I paste in a list of items and the exact matches are loaded/added....?

**Additional context**
item db lookups "feel" expensive when searching, so maybe this is harder than it sounds and needs some core perf improvements before this feature makes sense?

**Comment by Supamiu** [comment]
Hello, thank you for taking some time to write an issue 👍 

Inside the lists page, you have this small icon: 
![image](https://user-images.githubusercontent.com/11519203/73535579-2e07dc80-4424-11ea-9e3b-6e9739e31bf8.png)

It allows you to merge multiple lists into one, and I believe it's what you are looking for 😃 

Adding community lists to other lists is not something easy to do and I think it's better to not have it as it would cause very large lists to be created super easily, leading to bad performances.
