### ISSUE TITLE
bug: "Marketboard information" option from any item in a list does nothing

### ISSUE THREAD

**Issue by rcdailey** [ffxiv-teamcraft/ffxiv-teamcraft#1345]
When I select the "Marketboard information" submenu item from any item in a list, nothing happens.

**To Reproduce**

1. Click the ellipsis (...) button next to any item / ingredient
1. Select "Marketboard information" from the popup menu

**Expected behavior**
I expect the marketboard information popup to appear showing sale prices and history for that item.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Using desktop app
 - Version 6.5.12

Here is the contents of the log error I see when the issue happens:

```
ERROR TypeError: Cannot read property 'emit' of undefined
    at Object.eval [as handleEvent] (VM276 t.ngfactory.js:1068)
    at Object.handleEvent (main.js:1)
    at Object.handleEvent (main.js:1)
    at yf (main.js:1)
    at main.js:1
    at HTMLLIElement.<anonymous> (main.js:1)
    at t.invokeTask (polyfills.js:1)
    at Object.onInvokeTask (main.js:1)
    at t.invokeTask (polyfills.js:1)
    at e.runTask (polyfills.js:1)
Oi @ main.js:1
e.handleError @ main.js:1
next @ main.js:1
o @ main.js:1
t.__tryOrUnsub @ main.js:1
t.next @ main.js:1
t._next @ main.js:1
t.next @ main.js:1
t.next @ main.js:1
t.emit @ main.js:1
(anonymous) @ main.js:1
t.invoke @ polyfills.js:1
e.run @ polyfills.js:1
e.runOutsideAngular @ main.js:1
onHandleError @ main.js:1
t.handleError @ polyfills.js:1
e.runTask @ polyfills.js:1
e.invokeTask @ polyfills.js:1
m @ polyfills.js:1
b @ polyfills.js:1
```

Link to the list that has the problem:

https://ffxivteamcraft.com/list/cagPjQBG8CIFoNWFEhYJ

**Comment by Supamiu** [comment]
It has been fixed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/477891c2f4023bea9470d96c298331c3869b6bf9 but this commit won't be in production before the next update.

Sorry for this, thank you for the time you took to write this issue.
