### ISSUE TITLE
feat: Inventory Optimizer (Mats used for multiple recipes)

### ISSUE THREAD

**Issue by GaeaRW** [ffxiv-teamcraft/ffxiv-teamcraft#1348]
Idea: An addition to the Inventory Optimizer that allows for users to sort mats by recipes used to better manage what is worth keeping and what is better selling/discarding.

Examples: 
Mythrite Ore and Cobalt Ore are commonly used in high-end recipes, recipes for Company Workshop items, and are generally smart to keep in a retainer at all times. The feature idea would allow you to either "_save_" these mats or "_hide_" them depending on how it would work, making it easier to keep them handy. This would be handy for Omni-80 Crafters who are working toward specific goals and have different retainers for different sets of mats and help them know to keep stacks of specific mats instead of selling or discarding them.

Another option/idea example for this would be Map Mats (Aquapolis, Lost Canals, etc). Shell Leather is used only particularly for the Urban and Rebel coats and boots. While this mat isn't commonly used, the user is trying to make sure that they don't get rid of the leather while organizing their full capacity retainers, so they mark it as "_important_" and Teamcraft recommends "**DO NOT DISCARD**" or akin so the user knows "okay I need to keep this".

An opposite example would be something like Perlite. This is only useful for Growth Formula Theta and is reducible for Aethersand (when a collectable). The user has no need for Growth Formula Theta, and the mat isn't a collectable so it's just sitting in the retainer for no reason other than taking up space. The user can mark the mat as "_unnecessary_" and Teamcraft recommends "**DISCARD/SELL**" or akin so the user knows "okay I don't need to keep this."

**Comment by Supamiu** [comment]
Adding technical details for the newcommers who might want to do it:

How to create a new inventory optimizer:

- Create a new file in https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/tree/7c09781eea1120134af07d820e21718aaa02a552/apps/client/src/app/pages/inventory-optimizer/optimizations
- Implement your optimizer (take the other ones as example, you just need to extend `InventoryOptimizer`
- Add it to the `optimisations` array with its dependencies here: https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/5efd91619fa120d0be4c950425aacc92b25f073f/apps/client/src/app/pages/inventory-optimizer/inventory-optimizer.module.ts#L24-L42

Regarding the data, `LazyDataService` has a property in `data.recipes` that's filled with the data from the recipes.json file here: https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/0fa4afc208682aa1b41ae0aacc0ecfdf1e021e93/apps/client/src/assets/data/recipes.json

You can use this to find how used an item is, and create a basic optimizer from this.

**Comment by rcdailey** [comment]
@GaeaRW I get the idea you are going for but I'm not sure how specifically you would want it to function. You mentioned in the idea that you want to "sort mats by recipes", but what exactly does that mean?

In what way would you specify a recipe and how would you expect the UI to change for materials required by that recipe? For example, you mentioned "sort" so do you simply expect them to be ordered differently? Do you need other visual indicators? Some more detail on how you expect this to function in a step-by-step fashion would be valuable.

Also for the other examples where you mark an item not needed: Why not just hide the item? Wouldn't that effectively work the same as if there was a note on it that said "DO NOT DISCARD?" If you can't see it, you won't sell it I would think.

Again having more information specifically on how recipes interact with the inventory optimizer itself is the missing critical piece of information that I think will make the rest of it more clear.
