### ISSUE TITLE
Packet Capture down

### ISSUE THREAD

**Issue by Sephodious** [ffxiv-teamcraft/ffxiv-teamcraft#1360]
bug: App not capturing Packets

After 5.2 update to ffxiv the app is no longer capturing packets.  I've tried relogging, restarting, running with launcher and without, running game as admin and app with and without admin.  Still inventory packets aren't being captured. EDIT: after reading closed issues, i thought i would state here that this issue did not exist before 5.2 update.  It worked fine before that and therefore should be considered a bug and not a user issue seeing as how the issue began with a new update to the game and the app itself.

![image](https://user-images.githubusercontent.com/44609387/74779006-b979ce00-526a-11ea-9da8-0a4ccd64ee02.png)

 - OS: Windows 10 Pro, build 18362
 - Browser: Desktop App/Google Chrome
 - Version: Teamcraft 7.0.2

**Comment by Supamiu** [comment]
Like with every big update from the game, packet capture is broken because they are switching opcodes.

As said in the announcements channel on discord, this will be fixed later on as it needs more time.
