### ISSUE TITLE
feat: inventory/armoury/retainer optimization: highlighting items no longer valuable for leveling

### ISSUE THREAD

**Issue by atraholt** [ffxiv-teamcraft/ffxiv-teamcraft#1375]
As you level through all the jobs in the game, you are inevitably going to accumulate gear which is viable for boosting your stats, but you gradually acquire better gear. It would be nice if Teamcraft had a way to tell you which items in your massive inventory are ones that no longer are viable and could be desynthsized or turned in for Grand Company seals.
The method of doing so doesn't need to be anything too fancy, it would suffice with a simple check of available item level gear + level restriction of your gear, compared up against your jobs' levels.

**Comment by rcdailey** [comment]
@atraholt The way I manage this today is basically in my Armory Chest, for each slot category (head, chest, ring, etc):

Right click -> Sort. From left to right, and top to bottom: Items are sorted in descending order by level. This means you can start from the bottom of the list and right-click -> desynth for each one. Or sell. Or trade to GC.

You stop doing this once you reach a piece of gear that has the little paper icon on the bottom right of the item icon. This means it is part of a gearset. You don't want to get rid of those.

Is this in-game solution not viable? If not, why? What more are you looking for?

The thing I think that will make this less convenient than you seem to think is that basically when you see an item suggested in Teamcraft, you either have to copy/paste an `isearch` command to find it, or manually search it in your armory chest. This takes time and makes it tedious.

Definitely go into more detail so I can understand the value add.

**Comment by atraholt** [comment]
I think I perfectly described the value add? The idea is that there are easily 16 different inventories of items that it is very hard to keep track of which ones are no longer valuable for anything but glamours, and surfacing those because Teamcraft already is collecting that data would be a massive value add for helping out in maintaining inventories.

**Comment by rcdailey** [comment]
I wouldn't say you "perfectly" described it. That's why I responded with questions/ideas. You never addressed my questions. I think it would be helpful to understand what in-game solutions you have tried, why those didn't work, and what *specific* gaps you feel Teamcraft will fill.

Until then I personally don't feel there's anything to do here. Especially since you've left out a significant amount of detail regarding what the actual Teamcraft implementation of this solution would be. You mentioned:

> it would suffice with a simple check of available item level gear + level restriction of your gear, compared up against your jobs' levels

But what does this mean? Are you saying it should look at some delta in gear level compared to character level and suggest those to be removed? For example, gear 30 levels below the respective job level?

Also you mentioned 16 different inventories but I doubt all of those apply here. Beyond the Armory Chest, where do you usually store gear that you never intended to keep? I need some real life examples and a lot more detail.

**Comment by atraholt** [comment]
You don't have four retainers full gear then, I take it? I would like to know what, in which inventory, no longer benefits any job or class as an item to use as gear for leveling that job or class. Digging through all of them is easily days of work to figure out, so why not have something that already knows what's in every single one of them surface it instead? If I knew what the data structure looked like and where the data was stored I could mock it up using Python or R, but I sadly am less than useful when it comes to JavaScript.

**Comment by rcdailey** [comment]
So a separate section in the inventory optimizer called "Useless gear", with an edit field where you can set a desired level difference?

**Comment by Supamiu** [comment]
This brings a step up in difficulty, as it means that we have to maintain a list of your retainers' levels, which is not done at all at the moment. I'm also not sure about if we're able to detect the ClassJob they're using.

It also means that we need to build another lazy data file that will contain level and ClassJob req for each item in the game. I'm not saying it makes it impossible, just listing what's needed here.

**Comment by atraholt** [comment]
For retainer levels, I believe node-machina-ffxiv supports to capture this, see [this source file](https://github.com/karashiiro/node-machina-ffxiv/blob/master/models/retainerInformation.js) over on the repository.
I am a bit unfamiliar with what lazy data entails (mostly due to my unfamiliarity with this repository); is that locally cached inventory that the client knows about without querying Firebase about the details?

**Comment by Supamiu** [comment]
Oh yeah I know it includes the data, but we're not reading or storing it at all for now, that's the thing that needs to be added.

Lazy data is file-cached data that comes from several XIVAPI calls, it's regenerated on every patch and stored here: https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/tree/staging/apps/client/src/assets/data

This is what's loading when the loading screens says "loading items, npcs, and more" or something like that.

Saving all this inside Firebase (or firestore) would create an insane amount of requests and give no advantage to desktop app over web. With this file cache, it's loading way faster on desktop and it can be heavily cached per patch on web.

It's generated by this file: https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/staging/data-extraction/xivapi/index.js

**Comment by Supamiu** [comment]
I started thinking about how to implement this feature again and found a major issue: ingame gearsets.

The information that a piece of gear is inside a gearset is not sent inside packets, it's handled by a local file that I do'nt want to be reading, as it requires linking with current ingame char etc, which is a lot more complex than an inventory optimizer has to be.

I'm closing this as impossible, sadly. Will reopen if someone finds a proper solution.
