### ISSUE TITLE
feat: no desktop shortcut on update

### ISSUE THREAD

**Issue by iFral** [ffxiv-teamcraft/ffxiv-teamcraft#1382]
I prefer to keep things off my desktop. So it's a personal frustration when I have no voice in whether something is placing items on my desktop directory. Teamcraft does this on every update. With the frequency of updates, I'm having to pull a shortcut to Teamcraft off my desktop multiple times a week. It would be great if there were some way to prevent this from happening without depriving people who want things on their desktop from having the convenience.

**Comment by Supamiu** [comment]
I'm going to add a setting in a future update to address that
