### ISSUE TITLE
feat: Fishing spot pages misses display

### ISSUE THREAD

**Issue by Lodinn** [ffxiv-teamcraft/ffxiv-teamcraft#1388]
**Problem description:**
A known issue of the older fishing resources like CBH is that the actual catch and bite rate data is pretty much mangled and figuring it out, especially when coming up with strategies, requires no small effort.

**Proposed solution:**
Add misses/cancelled casts to the "Fish per bait" table on the spot page.
Ideal resolution of the issue works as follows:
1) For the purposes of the table, "The fish gets away" and "Nothing bites" situations are treated as separate "fishes" which are a legitimate result of "catching" the fish and therefore participate in the overall statistic;
2) Upon hovering over the "fish gets away" entry in the table (or clicking on one), a breakdown by tug is displayed. Reasoning: to help people differentiate between other fishers ignoring the undesired tug type altogether and fish getting away.

An example would look as follows:

 Mogpom | Moggle Mogpom | Cancelled Cast | Get Away
------------ | ------------- | ------------ | -------------
70% | 2% | 0% | 28%

Upon hovering over or clicking on the "28%" entry an info box like

> Tug type:
> Light (!) - 99% 
> Medium (!!) - 0%
> Big (!!!) - 1%

is displayed.

If the "Cancelled cast" and "failed hooking" situations are hard to discern it's okay to collate them. Tug type breakdown would be actually pretty helpful, however - that is, the very basic implementation with just one column added would help immensely already.

**Comment by Supamiu** [comment]
I'm closing this as it seems like it's covered by the current misses popup inside spot details page 🙂
