### ISSUE TITLE
bug: Missing EN translation on Lists page: "LISTS.Load_archived"

### ISSUE THREAD

**Issue by rcdailey** [ffxiv-teamcraft/ffxiv-teamcraft#1399]
Teamcraft v7.0.7

![image](https://user-images.githubusercontent.com/1768054/75377202-ee070e80-5896-11ea-9090-4cb7c43b2afe.png)

**Comment by rcdailey** [comment]
Apparently already fixed!

**Comment by latenightwreck** [comment]
https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/5a1ae8c9ad19c58f88cfeb5e99f4f2183a5d77bb
