### ISSUE TITLE
Bug: Bite time formatting issue in fish pages

### ISSUE THREAD

**Issue by de-gene-rate** [ffxiv-teamcraft/ffxiv-teamcraft#1400]
## Environment
Windows 10 Edge Chrome, Chrome, and Desktop app 7.0.7
### Browser
Edge Chrome: Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36 Edg/80.0.361.62

Chrome: Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

Have you disabled script-/adblockers before submitting? Yes

### Teamcraft Link
https://ffxivteamcraft.com/db/en/item/29786/Spectral-Sea-Bo
 but as far I can tell it applies to all the detailed fish views.

## Current behavior
When loading a fish page the bite time shows what appears to be the correct bite times, after 5 to 6 seconds though additional data is loaded in such as the icons for the weather table at which point the decimal in the bite time shifts one digit to the left completely changing the bite time to unrealistic numbers. For example the numbers for Spectral Sea Bo start at 21.3s minimum, 35.7s max, 7.2s avg and shift to 2.1s min, 3.5s max, 0.7s avg after the page finishes loading. This appears to be happening in all the fish pages.

[Video](https://gfycat.com/naughtyflamboyantgazelle)

## Expected behavior
The bite times shouldnt change after the page is finished loading.

## Steps to reproduce
1. Visit the page for any fish
2. Wait a few seconds after the initial data loads for the rest of the page to load. 
3. Witness the bite times change

**Comment by Supamiu** [comment]
This has been fixed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/255daa5d8362ced24150f2867b51ea193de09866 and will be in 7.0.8, the next update.

Thank you for reporting 👍
