### ISSUE TITLE
ux: update label for custom alarm creation fields

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#1405]
In custom alarms page, the form has some confusing names:

![](https://media.discordapp.net/attachments/462954987329159176/679028079812673684/unknown.png?width=493&height=703)

**Fields that need to be more clear are:**

- Spawn (it's the hour at which the node spawns).
- Duration (needs to be explicit about the unit, it's in eorzean hours).

To open the dialog in screenshot, go to `/alarms` and click the "Add custom alarm" button in top-left buttons.

**Source**: https://discordapp.com/channels/355013337748209665/462954987329159176/679028085173125122

**Comment by Nowbob** [comment]
I am taking a look at this :)
(slowly D:)
