### ISSUE TITLE
feat(levequests): add a setting to always include all 3 leves for large deliveries

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#1406]
**Is your feature request related to a problem? Please describe.**
When using levequests page, people who do all 3 deliveries always do all 3, checking the boxes everytime by hand is boring.

**Describe the solution you'd like**
A setting to make these checked by default.

**Describe alternatives you've considered**
Checking them by hand everytime.

**Additional context**
This needs to be done in [SettingsService](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/e7f25d01226715037a08432a5b63cf4e08b96def/apps/client/src/app/modules/settings/settings.service.ts), you can use [alwaysHqLeves](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/e7f25d01226715037a08432a5b63cf4e08b96def/apps/client/src/app/modules/settings/settings.service.ts#L174-L180) as an example.

**Source**

https://discordapp.com/channels/355013337748209665/462954987329159176/639184326763741185

**Comment by Nowbob** [comment]
Taking a look at this one
