### ISSUE TITLE
Bug: Total Trades not letting me ignore a currency despite there being other ways to get them.

### ISSUE THREAD

**Issue by virantx** [ffxiv-teamcraft/ffxiv-teamcraft#1426]
When having a list like shown on the screenshot it doesn't let me ignore the  Alexandrian Manifesto's or Alexandrian Gears despite the items they are used for can be bought with poetics.

**To Reproduce**
A list like this https://imgur.com/a/D1z1DFB and attempt to ignore the currencies.

**Expected behavior**
Able to Ignore the Manifesto's and Gears allowing the correct number of poetics

**Screenshots**
https://imgur.com/a/D1z1DFB

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Version v7.0.9

**Additional context**
You are able to ignore the gears but only if that is what you try to first clicking on the Manifesto's first will prevent you from ignoring the gear and the Manifesto's will stay and ignoring the gear first will not let you ignore the Manifesto's afterward.

**Comment by Nowbob** [comment]
Taking a look
