### ISSUE TITLE
feat(inventory-optimizer): ability to hide an optimizer entirely

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#1432]
**Is your feature request related to a problem? Please describe.**
With the increase of available optimizers, people may want to ignore some entirely, because they don't apply to them.

**Describe the solution you'd like**
A simple way to ignore an optimizer, just like we can ignore containers and items.

**Describe alternatives you've considered**
*none*

**Source**

https://discordapp.com/channels/355013337748209665/355110181148819467/683274515719127170

**Comment by Nowbob** [comment]
Ok I kinda cheated on this one, I've done most of the work already (to see if I could even figure it out), but now I'll mention that I'm working on it :)
