### ISSUE TITLE
feat : Add multiples items from multiples searches in a single window/single time.

### ISSUE THREAD

**Issue by Kylvan-8** [ffxiv-teamcraft/ffxiv-teamcraft#1436]
## What feature are you proposing

- Make the possibility to retain multiples items from one search windows with memory retention of ticked checkboxes and then being able to add everything from the list in a single time.

## What is the use case for this feature?

- Gain a LOT of time, this will allow to make only two click to open and close a window in a single time,, for  X number of items.

**Comment by Supamiu** [comment]
This is not possible, and it's why you can create a list and add items to it on the fly by checking the chackboxes, then clicking "add selection to a list", then picking the list. Keeping results from previous searches to avoid 2 clicks is not worth it in my opinion.

**Comment by Kylvan-8** [comment]
@Supamiu It's not just two click, it's two per items, if you have 100 items it's 200 click. In my opinion actually it's a lack of ergonomics in the design and can make you loss precious time.
Yes, it's not possible at the moment, but this can be done for sure.

**Comment by Supamiu** [comment]
I think you're using this wrong, because you can use search filters to get everything you're looking for, and checkboxes to add them all at once.

Adding more details about your request would be helpful, as it seems like you're searching for recipes for log completion or something else that's not usual, can you check the feature template again and fill it properly please? The questions about what motivates it and what you tried are important because people tend to ask for the solution without exposing the problem, and this case creates niche features, which is not something I want to do.

**Comment by ArcaneDisgea** [comment]
You also shouldn't be adding anywhere near 100 items to a list due to the performance drawbacks within the list. This feels like a solution looking for a problem imo. A nice to have feature sure but ultimately it would be very complex to add for very little gain.

**Comment by Kylvan-8** [comment]
> 
> 
> I think you're using this wrong, because you can use search filters to get everything you're looking for, and checkboxes to add them all at once.
> 
> Adding more details about your request would be helpful, as it seems like you're searching for recipes for log completion or something else that's not usual, can you check the feature template again and fill it properly please? The questions about what motivates it and what you tried are important because people tend to ask for the solution without exposing the problem, and this case creates niche features, which is not something I want to do.

I don't know how can i be make it more clear..
So i will take a use case step by step :
- Making a new character, leveling up all the DOH/DOL class to 80. Then i would like to do all the quests for example.
So i have to add many materials that are not from recipes and some from recipes.
https://ffxivteamcraft.com/list/Ayidto4clHKWpVla3h3x
And this takes me a long time to complete.
I can't use filters for the materials that are not from recipes.

All what you can do about the search is :
- Click on add an item
- Fullfill the search box with the name of ONE item or more with filters
- Use the checboxes
- Add to the list

You can't :
- Click on a " Add items " button
- Fulfill the search box multiples times for many items
- Use the checkboxes on each items
- Add to the list all the items at once

And the filters aren't not really usefull for this case except if you search items from a same family or if you need multiples items with a familiar name. Because when you use teamcraft, most of the time, you know which materials you need or which recipes.

Maybe the tool isn't design for this but it's too bad i think, because everything else is great so far and most of the use cases i think.

**Comment by Supamiu** [comment]
The use case you're describing here is the exact reason why community lists exist in fact 🙂 

See [Community lists with QUEST tag](https://ffxivteamcraft.com/community-lists?tags=QUEST) for instance.

What ArcaneDisgea means and what I mean, is that implementing this would be hard and cost a lot of time for a benefits that's not sorth it, as it wouldn't be used by a lot of users, considering the fact that community lists exist for this exact use case, so one person can do a boring list by hand and share it to everyone so they can copy the list easily (you can even add job tag if you want class quests for one job only).
