### ISSUE TITLE
Bug: Some recipes cannot work in simulator when chose China region

### ISSUE THREAD

**Issue by cmcm951102** [ffxiv-teamcraft/ffxiv-teamcraft#1440]
**Describe the bug**
For example, recipes startswith "Skybuilders'" work regularly when I chose "Global" region.But when "China", the Crafting simulator page show loading animation forever (unfortunately,develop tool always crashed when loading "main.js", this file is too large.)

**To Reproduce**
1. choose "China" region
2. open Crafting simulator page
3. search "Skybuilders'" recipes and select any one
4. see loading animation

**Expected behavior**
please find out the problem and solve it. Thanks!

**Comment by Supamiu** [comment]
This is due to some missing data inside the zh-recipes file, I'm going to add fallback to english recipes in case this happens again. a content update might be needed for chinese recipes, @zhyupe will know more about this.

**Comment by Supamiu** [comment]
I added a fallback in https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/92be7475e33d83b3c74b1cb9bedee8094fade4b0 , will make it load again but won't be the chinese recipe unbtil data update is performed.
