### ISSUE TITLE
bug: GCD shown on gearset is incorrect

### ISSUE THREAD

**Issue by msoltyspl** [ffxiv-teamcraft/ffxiv-teamcraft#1445]
For balance's 2.38 bis war - https://ffxiv.ariyala.com/1CDCB - the GCD is reported as 2.39 (sks breaking point is 1522/1523).

**Comment by Supamiu** [comment]
As said right above the stats display in gearset's display mode:

> Results are not 100% accurate, they are from players (the allagan studies) like you and me who spend a lot of time trying to figure the formulas, please do not report inaccuracies as bug.

If you want to report innacuracies, the discord server is here for that, but reporting this as a single sentence and after wiping the bug template entirely to just write a minimum of details is not an acceptable issue.

**Comment by ayyaruq** [comment]
This is closed but just for posterity, @msoltyspl, I just did an import and the food wasn't selected. The SKS without food is 1454, which is below the 1523 threshold for 2.38s GCD. 2.39s is correct in this case.

**Comment by msoltyspl** [comment]
> This is closed but just for posterity, @msoltyspl, I just did an import and the food wasn't selected. The SKS without food is 1454, which is below the 1523 threshold for 2.38s GCD. 2.39s is correct in this case.

The gearset includes food, so that would imply that food is ignored when calculating (or looking up) the sks tier.
