### ISSUE TITLE
feat(inventory): add expansion filter possibility inside item search field

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#1449]
**Is your feature request related to a problem? Please describe.**
When checking the inventory page, it'd be cool to be able to find all the items for a given expansion.

**Describe the solution you'd like**
An expansion filter, either as dropdown, or token (like `expansion: Shadowbringers` for instance).
The former being easier to implement, the latter being easier to extend with more filter without having to add more dropdowns and use more space.

**Describe alternatives you've considered**
_N/A_

**Additional context**
For the second possibility, reusing the logic from search page with the `patch` prefix should be considered:

https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/b8d7724bcc943f7b4a212a507951a087845303c5/apps/client/src/app/pages/search/search/search.component.ts#L284-L297

**Source**
https://discordapp.com/channels/355013337748209665/355110181148819467/685264074069508118

**Comment by Nowbob** [comment]
Taking a look at this, going to try the token approach
