### ISSUE TITLE
feat(pricing): add server name to text export

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#1450]
**Is your feature request related to a problem? Please describe.**
Being able to buy all the items at once in different servers would be nice, when using pricing mode to find cheapest option.

**Describe the solution you'd like**
Having the server name included in the text export so it can be imported in a sheet and ordered easily.

**Describe alternatives you've considered**
Making the list of this on paper, by hand.

**Additional context**
This has to be added in the `getSpendingText` method:

 https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/57eeb1925913b2c92adb63ddfa1763f66fad3bb2/apps/client/src/app/modules/pricing/pricing/pricing.component.ts#L303-L319

Server is available inside the `Price` model: 

https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/0260cbdfc5b869a7ff369bf0e1b2cebf33f1a0fd/apps/client/src/app/modules/pricing/model/price.ts#L1-L8

**Source:**
https://discordapp.com/channels/355013337748209665/355110181148819467/684403701573877770

**Comment by Nowbob** [comment]
Taking a look
