### ISSUE TITLE
Bug: Desktopapp and Browser Version can't find Company Crafts

### ISSUE THREAD

**Issue by Jyntax** [ffxiv-teamcraft/ffxiv-teamcraft#1454]
**Describe the bug**
Teamcraft doesn't find company crafts. (Tested with Airship and Submarine parts)

**To Reproduce**
1. Go to search
2. Type any Name of a Submarine part like "Shark-Class Bow" or even just "Shark-Class"

**Expected behavior**
Usually the Company Crafts were found and addable to a list.

**Screenshots**
https://cdn.discordapp.com/attachments/356074405451005955/687378355712032793/unknown.png
https://media.discordapp.net/attachments/356074405451005955/687378488742772761/unknown.png?width=1087&height=383
https://media.discordapp.net/attachments/356074405451005955/687378610134319160/unknown.png?width=1087&height=370

**Desktop (please complete the following information):**
 - OS: Win10 64bit
 - Browser Firefox
 - Version v7.0.13

**Comment by Supamiu** [comment]
This was because of a search maintenance being operated, it's now fixed.
