### ISSUE TITLE
ux: allow for mouse wheel up/down to edit amount of number input fields

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#1458]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Mousewheel events on inputs increasing/decreasing amount like ingame.

**Describe alternatives you've considered**
focus => use arrow keys or click on arrow buttons inside the input.

**Additional context**
It could be a nice first directive to create, see http://blog.sodhanalibrary.com/2016/10/angular-2-directive-for-mouse-wheel.html for a pretty good example.

Once this directive is created, add it to all the `nz-input-number` elements in the app, and bind the wheel event emitters to the corresponding amount edition methods, based on the page it is in.

**Source**
https://discordapp.com/channels/355013337748209665/355110181148819467/687433079350100024

**Comment by Nowbob** [comment]
Ooh this looks fun to try, but I can guarantee I will be slow on this one, if someone else *really* wants to take it over and finish it fast, please do.

**Comment by ayyaruq** [comment]
This was completed with the release of 7.3.0, if you find latest Teamcraft doesn't do what you're expecting in regards to this feature, please leave a comment and we'll reopen this issue.
