### ISSUE TITLE
feat: import log tracker complete lists.

### ISSUE THREAD

**Issue by Mycah** [ffxiv-teamcraft/ffxiv-teamcraft#1470]
*please prefix the issue with "feat:", example: "feat: commission board system"*

**Is your feature request related to a problem? Please describe.**
these lists are FRIGGIN LONG and packet capture would be FRIGGIN SWEET

**Describe the solution you'd like**
Clicking log tracker, instead of having to alt-tab through and check off each thing one at a time, it'd be nice if we could just click through our lists and auto populate in teamcraft what's done.

**Describe alternatives you've considered**
click tab click tab click tab click tab

**Additional context**
hope this hasn't been a rejected feature request in the past

**Comment by Supamiu** [comment]
I'm no closing this because I understand the need and I would love to have it too, but in reality, nobody ever found a packet repsonsible for that :/ so while it has not been found, it'll stay as a request.

**Comment by Mycah** [comment]
is this what you use for reference for packet capture?

https://github.com/zhyupe/FFXIV-Packet-Dissector

**Comment by Supamiu** [comment]
No, but it can help finding the packet for sure, as we need opcode and structure, using the dissector can help, even if this is a chinese fork, and china has different opcodes.

**Comment by Supamiu** [comment]
Possible inspiration: https://github.com/delroth/FFXIVCollectionHelper

**Comment by ayyaruq** [comment]
This was completed with the release of 7.2.9, if you find latest Teamcraft doesn't do what you're expecting in regards to this feature, please leave a comment and we'll reopen this issue.
