### ISSUE TITLE
bug: Fireheart cobalt wrong map

### ISSUE THREAD

**Issue by KingDeDeDe11** [ffxiv-teamcraft/ffxiv-teamcraft#1474]
**Describe the bug**
Fireheart cobalt is obtainable in Lakeland, however the database shows it in Ahm Araeng

**To Reproduce**
1. Search Fireheart Cobalt
2. Click on View Details Inside Database
3. Scroll down to How to Obtain

**Expected behavior**
Fireheart Cobalt should be found where the map leads to, however it is the wrong area. 

**Screenshots**
![Fireheart](https://user-images.githubusercontent.com/11394704/77253918-be47ee00-6c2b-11ea-9cb5-56a5b79170f8.PNG)
![actualfire](https://user-images.githubusercontent.com/11394704/77253960-f3544080-6c2b-11ea-873a-1d07e86ae2ca.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
- Version: 74.0 

**Additional context**
The position on the map is correct.
The list view correctly shows it in Lakeland, but everywhere else it shows it as

**Comment by Supamiu** [comment]
This has been fixed in 7.0.18, please make sure you update to it (or 7.0.19 as it's being released right now).
