### ISSUE TITLE
feat: similar to ffxivcollect.com monitor and maintain collection lists not doh/dol related

### ISSUE THREAD

**Issue by Mycah** [ffxiv-teamcraft/ffxiv-teamcraft#1476]
**Is your feature request related to a problem? Please describe.**
As I find myself using teamcraft more and more every day, it'd be nice to have support for the things I have to reach out to other services for.  Specifically tracking in game collection items, with potential links to where to get stuff thats missing.

**Describe the solution you'd like**
Lists for the following would be awesome:

- Achievements
- Mounts
- Minions
- Orchestrion
- Blue Magic
- Emotes
- Bardings
- Hairstyles
- Relics
- Triple Triad
- Seasonal Items

**Describe alternatives you've considered**
ffxivcollect.com

**Additional context**
Since ffxivcollect uses xivapi for its data, maybe that would be easier than implementing it via packet capture.

**Comment by Supamiu** [comment]
I will never implement ffxivcollect.com's stuff in TC, because Raelys did a super good job and this would make no sense at all considering TC's scope :)

And yeah, packet capture can't help you for that, sorry but it'll have to stay as being done by hand :/

**Comment by Mycah** [comment]
It's cool, I understand.  Just thought I'd throw it out there.
