### ISSUE TITLE
Open list showing full tag for Inventory and FC Chest

### ISSUE THREAD

**Issue by StellarJay77** [ffxiv-teamcraft/ffxiv-teamcraft#1479]
Bug: Showing Inventory and FC Chest with long tag

**Describe the bug**
In an open list it is showing "INVENTORY.BAG.INVENTORY.BAG.FC_chest : 7" for items in FC chest and "INVENTORY.BAG.INVENTORY.BAG.Inventory : 7" for items in inventory

**To Reproduce**
Move items from retainer to inventory or to FC chest with item view able in an open list

**Expected behavior**
Should just show "Inventory: 7" or "FC Chest: 7"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser desktop app
 - Version 7.0.19

**Comment by Supamiu** [comment]
This has been fixed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/eb5522efc64a3ecdafe19005b0681227475adef5 and will be in 7.0.20 🙂
