### ISSUE TITLE
bug: Alarms showing inaccurate fishing window end times on fish with time AND weather restrictions

### ISSUE THREAD

**Issue by ciel115** [ffxiv-teamcraft/ffxiv-teamcraft#1483]
## I'm submitting a...
* (x) Bug report *- please add **bug:** before the title*
* (_) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

### Browser
*Please state your browser and version. Go [here](https://ipchicken.com/) and copy everything after "Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0 ".*

Have you disabled script-/adblockers before submitting? yes
### Teamcraft Link
*If the bug appeared on a list (i.e. layout issues), please put a link here.*
### Layout code
If you're reporting a layout issue, please give us the layout code
```
Paste your Export code here
```

## Current behavior
I've noticed issues with alarms for fish that have both time and weather requirements. The alarms start at the correct time, when the weather and time requirements are both met, but there are two ways in which they go on to work incorrectly, and I think this depends if the time or weather requirement was met first. I'll use a couple examples that I saw while fishing today. 

The time window for Hannibal from Bluefog, NT is 22:00-4:00, and the weather needs to be fog. When I went after him today the fog started at 16:00 and ended at 0:00. The bug is that in my alarms list, Hannibal stayed green until 4:00, even though the weather changed to fair and he was no longer catchable after 0:00. **So the first incorrect behavior is when the weather is correct before the time window, but changes during the time window, alarms still displays the fish as available for the entire time window.** 

The second example is with Darkstar from The Weeping Saint in CCH. It's available 19:00-4:00 and needs snow or blizzards. When I tried to catch it today, the weather wasn't correct until 0:00, but while I was fishing at about 3:00 i noticed the alarm list on Teamcraft said there was still about 15minutes left for the fish, as if it was just using the time until the correct weather ends, even though the time window only had about 3 minutes left. BUT even though the alarm entry said there was a bunch of time left, it still went dark at the correct time and went back to showing time til next window. **So in this situation where the correct weather starts after the time window starts, the alarm entry will show incorrect time remaining (until the correct weather ends) but will still go inactive at the correct time.** 

I've noticed this several times with different fish that have both time and weather requirements. 

## Expected behavior
Alarms should show time remaining in a window based on when **either** the weather or time requirement for a fish ends, whereas it seems to currently be when **both** end, which leads to errors when they don't end at the same time. 

## Steps to reproduce
1. Add some fish with time AND weather requirements to alarms.
2. Watch the alarms lie!

**Comment by ciel115** [comment]
Update: right after writing this I went to fish a little and noticed something pertinent that shows whatever's going wrong is more complex than I thought. Here's a screenshot I took of my game and browser at 3:00ET. https://i.imgur.com/m6NFE48.jpg You can see in the alarms list there are three active fish windows showing. All three of these fish have time windows that end at 4:00ET so the time remaining should be the same for all of them. Charon's Lantern has no weather requirement and is showing the correct time remaining. Hannibal and Starbright have weather requirements that started at 0:00, partway through their time windows, and they're showing incorrect time remaining as I talked about above. All three of their alarm entries went dark at 4:00ET, despite showing more time remaining, as described in my example with Darkstar in the original post. 
What I don't understand is why Hannibal and Starbright are showing a different amount of time remaining. It's not as simple as when the correct weather ends as I thought in my original post. Anyway just noticed that and thought I should add.

**Comment by Supamiu** [comment]
Hey, thank you for your (very detailed !) bug report.

Before I start investigating more, I'll need these to have a way to reproduce:

 - Local time (IRL time) at which the conditions are met but the remaining time is wrong.
 - Name of the target fish.
 - Name of the correct weather.
 - Timespan for this fish.

Thank you in advance 🙂

**Comment by ciel115** [comment]
Ok here is an example that will come up in about an hour: 

At about 2:34pm MDT (22:00 ET) the window for the fish Hannibal should open but it will likely be showing incorrect time remaining. It should be about a 6 minute window because at 2:40pm MDT (0:00 ET) the weather will change from fog to clouds. 

So between 2:34-2:40pm MDT conditions will be met but it will show excessive time remaining if I understand the bug correctly.
Target fish: Hannibal
Correct weather: Fog
Timespan for fish: 22:00-4:00ET 

Hope this is what you were looking for, thank you!

**Comment by shilohareles** [comment]
In 8.5m:

Rain in Gridania will start at midnight ET which is the end of its window. Timer should say 6 minutes remaining for the last two remaining ET hours but will display 25 minutes instead before cutting off appropriately at the end of its window at 2am ET

LT: 8:51 am est (fish will be available at 8:59am est)
Fish name: Stormdancer
Correct weather: Rain
Timespan for fish: 5pm ET to 2am ET

**Comment by Supamiu** [comment]
The document isn't open for other persons, updating your message in the issue might be a solution to share it easily and will avoid several comments from being posted.

**Comment by CerbStarraiser** [comment]
Specific Example: 
Fish name: Endoceras
This fish is available from 20:00 to 5:00 ET, but only during Fog/Cloud/Wind that follows clear skies.
At 21:00 ET, the timer in TC stated that there was 20 minutes left, which aligns with a 5:00 ET ending time.  However, the Fog/Cloud/Wind weather that causes the fish to be spawned was ending at 0:00 ET, so in reality it only had 8 minutes left.  This same situation should occur within 1 hour from now (it is currently 10:36 AM Central US).  It is currently 5:49 ET, and at 16:00 it will turn to wind, which should allow the fish to spawn, but the wind will end the window premature as it will turn back to clear skies at 0:00.

**Comment by ciel115** [comment]
As of May 22, 2021, despite patch notes saying "better fix for weather + time alarms.", alarms for fish with time and weather constraints are still showing up wildly wrong. 

Example: https://i.imgur.com/BRcATlx.jpg Alarms list says Soul of the Martyr is available for catching, yet it is 9:49pm ET and the fish's window is 4am-6am ET

Example: https://i.imgur.com/vsM3RXL.jpg Alarms list says Problematicus is available for catching, yet it is 10:49pm ET and the fish's window is 10am-3pm ET. 

The weather was correct for the fish in both these examples, and they may be possible to catch with Fish Eyes at those times, but these incorrect alarms are listed as normal non-Fish Eyes catching windows, as opposed to some fish where you have 2 options (Fish Eyes or not) of alarms to add. 

Even if it is possible to catch these fish with Fish Eyes, it's important to have non-Fish Eyes alarms because it's very hard to use Fish Eyes on fish where you need to spend a lot of GP mooching.
