### ISSUE TITLE
bug: Favorite Page has big problem

### ISSUE THREAD

**Issue by Kareylo** [ffxiv-teamcraft/ffxiv-teamcraft#1510]
**Describe the bug**
While in Favorite page, if you've got something in, it's like page is always refreshing and can't be used. See screenshots, the both one is in a loop

**To Reproduce**
1. Go to your username
2. Click on Favorite
3. See error

**Expected behavior**
Could use the favorite page

**Screenshots**
![image](https://user-images.githubusercontent.com/4358740/79354460-b9c9d900-7f3c-11ea-8d86-ac3406a68fcf.png)
![image](https://user-images.githubusercontent.com/4358740/79354585-e1b93c80-7f3c-11ea-8d3d-8b0296e3a04c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser chrome, firefow and desktop app
 - Version 7.1.8

**Comment by Supamiu** [comment]
Hello,

I can't seem to reproduce your issue so I think it's related to one of your favorites, can you please open console using Ctrl + Shift + i before opening favorites page, then screenshot the content of the console? If what I think is true, I'll also need your user ID, which is inside the settings page, account section, you can give it to me via Discord, using direct message 🙂

**Comment by Kareylo** [comment]
Nothing in console, needed to show all levels (with verbose too)
![image](https://user-images.githubusercontent.com/4358740/79371156-31573280-7f54-11ea-859c-2936741524e0.png)
