### ISSUE TITLE
bug: can't select the materia at the bottom in gear-set

### ISSUE THREAD

**Issue by Kaiay** [ffxiv-teamcraft/ffxiv-teamcraft#1517]
**Describe the bug**
gear-set can't select the materia at the bottom
**To Reproduce**
1. Go to 'gear-set'
2. Click on a list->a item
3. the 4ed and the last can't see(select) the materia at the bottom
**Expected behavior**
can see(select) the materia at the bottom
**Screenshots**
![image](https://user-images.githubusercontent.com/43386053/80462746-c05b4600-8969-11ea-8c32-7fadaafe20cc.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: desktop app
 - Version v7.1.8

**Comment by joseapintor** [comment]
Hey @Supamiu . Could I try taking a look at this? I worked on this by locally implementing a scrollbar.
