### ISSUE TITLE
bug: firewall entries duplicating

### ISSUE THREAD

**Issue by Wolfehart** [ffxiv-teamcraft/ffxiv-teamcraft#1528]
**Describe the bug**
Multiple firewall entries on every new update on desktop client vis the auto updater.

**To Reproduce**
1. Update ffxiv teamcraft app via the updater on top left.
2. After update done, there's multiple entries in windows 10 firewall exceptions for different versions.

**Expected behavior**
Only have one firewall entries for current version on every new update.

**Screenshots**
![firewall](https://user-images.githubusercontent.com/14332574/81468155-60d62380-9210-11ea-8d8a-62e770d106e5.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: Teamcraft 7.2.3

**Additional context**
Each of the firewall entries points to a different version of the exe software itself.
E.g. update from 7.2.2 to 7.2.3 would make it has 2 entries, one with 7.2.2 and one with 7.3.3 and so on.

**Comment by Supamiu** [comment]
This is most likely remnant entries from previous versions, from what I see, the FFXIVTeamcraft entry is "the real one" and the other ones are here because of the previous versions that had this bug and weren't properly cleaned up.
