### ISSUE TITLE
bug: Error when opening desktop app

### ISSUE THREAD

**Issue by RobPFarley** [ffxiv-teamcraft/ffxiv-teamcraft#1530]
**Describe the bug**
When opening the desktop app I often receive a javascript error and stacktrace. I think it's happening when there's an update available for the app, however I can't be certain about that as there seems to be a new update every time I open the app and it doesn't happen 100% of the time

**To Reproduce**
1. Open the Windows desktop version of Teamcraft and the error should appear straight away, possibly only if the currently installed version isn't the latest

**Expected behavior**
No error pop-up

**Screenshots**

![teamcraft bug](https://user-images.githubusercontent.com/17273366/81812531-2cb77700-951e-11ea-9e34-c3801e003180.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: desktop app
 - Version: 7.2.2

**Comment by Supamiu** [comment]
This has been fixed in 7.2.4 and will stop appearing in 7.2.5 (as 7.2.4 will be applied on 7.2.3 which still has the bug).

I'm closing this as it's resolved but not deployed yet 🙂

**Comment by RobPFarley** [comment]
Ah brilliant, thanks 😀

**Comment by RobPFarley** [comment]
I think this issue needs reopening, I have the same error message popping up in v7.2.5.

![bug](https://user-images.githubusercontent.com/17273366/82606941-d3031c80-9baf-11ea-837d-8b1a2c4e27e3.png)

This was a fresh install too, as I completely uninstalled Teamcraft before running the 7.2.5 installer
