### ISSUE TITLE
bug: fail to meld materia in half screen mode

### ISSUE THREAD

**Issue by Kaiay** [ffxiv-teamcraft/ffxiv-teamcraft#1538]
**Describe the bug**
fail to meld materia in half screen mode

**To Reproduce**
1. hold the top bar and push to left/right hand side(half screen)
2. new gear set
3. BLM 480-505
4. Click on meld materia on any item
5. choose any materia
6. can't detect any materia
7. press confirm and still nothing happen

**Expected behavior**
detect materia and show details and meld success %.

**Screenshots**
![image](https://user-images.githubusercontent.com/43386053/83248062-10cafb00-a1d7-11ea-8cfd-2a6a38643d85.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: desktop app
 - Version: v7.2.6

**Comment by Supamiu** [comment]
I managed to reproduce the bug, will be fixed for next update.
