### ISSUE TITLE
bug: black screen when start up the desktop app

### ISSUE THREAD

**Issue by FairyScript** [ffxiv-teamcraft/ffxiv-teamcraft#1562]
**Describe the bug**
Since yesterday, when starting desktop app, the main window will not be shown, click taskbar shortcut will popup a black window.
Reinstall app can't fix it.

**To Reproduce**
1. run desktop app, nothing happened.
2. click the taskbar shortcut, popup a black window.

**Expected behavior**

**Screenshots**
![Snipaste_2020-07-26_12-46-28.png](https://i.loli.net/2020/07/26/1di4J5bnhvTNork.png)

**Desktop (please complete the following information):**
 - OS: Windows 1909
 - Browser: desktop app
 - Version: 7.2.11

**Additional context**
The first day i upgrade app to 7.2.11, it works fine, but after next day, this is the problem.

**Comment by Supamiu** [comment]
Hello, thank you for your report.

What's inside the `console` tab when pressing `Ctrl + Shift + i` ?

**Comment by FairyScript** [comment]
> Hello, thank you for your report.
> 
> What's inside the `console` tab when pressing `Ctrl + Shift + i` ?

the console tab is empty.

console:
![Snipaste_2020-07-27_09-03-16.png](https://i.loli.net/2020/07/27/34YhLnKM8sFV5GJ.png)

element:
![Snipaste_2020-07-27_09-02-09.png](https://i.loli.net/2020/07/27/sHL1yYRhei9pCAx.png)

**Comment by FairyScript** [comment]
reinstall windows fixed it.
