### ISSUE TITLE
feat: Focus the input field if Ctrl+Shift+F is used in the desktop app

### ISSUE THREAD

**Issue by Drachenkaetzchen** [ffxiv-teamcraft/ffxiv-teamcraft#1567]
**Is your feature request related to a problem? Please describe.**
When I use the quick search shortcut (Ctrl+Shift+F), I cannot type right away since the input field is not focused. I need to click the field first before I can type something.

**Describe the solution you'd like**
When I use the quick search shortcut, the input field should be focused so I can type right away.

**Comment by Supamiu** [comment]
Hi, thank you for your report.

Last time I tried to do that, the browser was catching the event because something else was focused and it triggered an error, but I'll investigate more on the topic and hopefully include this in 7.3.

**Comment by ayyaruq** [comment]
Can I piggyback this to switch the shortcut to do like the electron CommandOrControl where it'll switch out the modifier key as appropriate?

**Comment by Supamiu** [comment]
I tried everything and couldn't have a working focus, even with a document.getElementById(...).focus() call... I have no idea what's wrong but it is wrong for sure.

Regaridng CommandOrControl, I don't know how it's used inside the renderer but I can point you to the right piece of code to try and implement it.

**Comment by Supamiu** [comment]
Closed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/0455781b1d4edb7c610a70fb8fa7cfb352274e4e (super hacky, but FINALLY)
