### ISSUE TITLE
bug: Item Search Overlay Opacity not working v7.3.4

### ISSUE THREAD

**Issue by macrossfiru** [ffxiv-teamcraft/ffxiv-teamcraft#1580]
**Describe the bug**
Desktop Teamcraft app Item Search Overlay opacity slider does not affect the opacity of the overlay 

**To Reproduce**
1. Go to side bar on Teamcraft desktop app, 
2. Click the magnifying glass icon with tool-tip `Open item search overlay`
3. At the top of the newly opened panel, click the slider and attempt to reduce the opacity of the overlay.

**Expected behavior**
The overlay should become more transparent as slider is moved to the left.

**Screenshots**
![image](https://user-images.githubusercontent.com/7554887/90310305-aacb5580-df33-11ea-8343-b9e8cc166a6b.png)
![image](https://user-images.githubusercontent.com/7554887/90310371-4b217a00-df34-11ea-999f-39074b763116.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 7.3.4

**Comment by Supamiu** [comment]
Fixed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/2962d2160d184bdfefaf37c2d97632f65ce392bb, will be in 7.3.5 👍
