### ISSUE TITLE
bug: Pricing mode doesn't populate the price field of large lists

### ISSUE THREAD

**Issue by Alukah** [ffxiv-teamcraft/ffxiv-teamcraft#1598]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
Using pricing mode on a list with many different mats and trying to fill prices causes it to only fill the prices of a couple items

**To Reproduce**
1. Make a large list of items that contains many different mats, such as https://ffxivteamcraft.com/list/PvJUG9eCfolP1rvxUkEe
2. Enter pricing mode
3. Press "fill prices" under "other" 
4. It only populates a few mats while the rest remain at 0 

**Expected behavior**
All mats should have their price updated.

**Screenshots**
Issue https://i.imgur.com/fr0pU7m.png
Expected behavior https://i.imgur.com/ZYUjJ4y.png
Console screenshot https://i.imgur.com/nPKcbkj.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 79
 - Version 7.3.9

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Supamiu** [comment]
Closed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/1256fc370c5face5fa422b9549748534d0cee8ba
