### ISSUE TITLE
bug: Dependencies update (dependabot Alerts on my forked project)

### ISSUE THREAD

**Issue by PellegriniPierre** [ffxiv-teamcraft/ffxiv-teamcraft#1602]
bug: Dependencies update (dependabot Alerts on my forked project)

**Describe the bug**
I think you actually need to update dependencies to resolve security isssues and avoid technical debt, i added dependabot (Git Dependency checker) on my forked project and it founds some alerts, it also merge in my project to update this: 

- chore(deps-dev): bump standard-version from 4.4.0 to 8.0.1
- chore(deps): bump lodash from 4.17.11 to 4.17.20 in /functions
- chore(deps): bump https-proxy-agent from 2.2.1 to 2.2.4 in /functions

**To Reproduce**
1. Go to your project on Github
2. Click on: 
![image](https://user-images.githubusercontent.com/10381459/91225695-53439b80-e724-11ea-8054-e4bec36fd571.png)

3. Add dependabot  and see what you can do to resolve kickcly.

**Expected behavior**
No dependency alert expected for node.js/typescript/javascript project.

**Comment by Supamiu** [comment]
I'm not going to update standard-version for now, because it causes a conflict with husky and the commit checker that I don't have time to resolve properly. I dismissed these warning on the repo, expected them to be hidden on forks as well.
