### ISSUE TITLE
feat: Click here to open with app (on web)

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [ffxiv-teamcraft/ffxiv-teamcraft#1603]
I think having "open with desktop app" button on web version would be good.

![K-002](https://user-images.githubusercontent.com/4695371/91235221-11d8dd80-e770-11ea-836a-e829a0896541.png)

Like Microsoft office online has a button to open document with desktop app. (I translated it myself, it was written in Korean)

![K-003](https://user-images.githubusercontent.com/4695371/91235336-519fc500-e770-11ea-93ca-2fb1bf5b2e0e.png)

Something like this?
![K-002](https://user-images.githubusercontent.com/4695371/91235572-c3780e80-e770-11ea-8d98-d99af3b9a077.png)

**Comment by Supamiu** [comment]
![RuRArdevrk](https://user-images.githubusercontent.com/11519203/91269856-10abae80-e778-11ea-8f44-bc3c2cb86027.png)

Hey, this button is already a thing, in the top-right corner of the app 🙂
