### ISSUE TITLE
bug: metric date range shows incorrect data on specific days

### ISSUE THREAD

**Issue by PatrickQuintal** [ffxiv-teamcraft/ffxiv-teamcraft#1621]
**Describe the bug**

Opening up the metrics dashboard page (on the default dashboard) and changing the date range to 2020-09-01 - 2020-09-10 causes the view to go blank. (Setting it to the 2nd, or the 31st shows what I expect; the page filled with data). 

**To Reproduce**
1. Go to `Metrics Dashboard`
2. Click on the leftmost date picker
3. Select the 1st of the current month, then select any other date, or the same date. (Specific examples given below)
4. TC will display "No data to display"

**It's important to navigate away, then navigate back to the Metrics Dashboard. Sometimes it just 'magically corrects' itself**  (more on that below)

**Expected behavior**
TC should show data for the date range.

**Screenshots**

![image](https://user-images.githubusercontent.com/8119713/92700496-38169400-f392-11ea-8fd8-48399a656064.png)

![image](https://user-images.githubusercontent.com/8119713/92700536-449aec80-f392-11ea-9dba-dc8d04eb5aec.png)

**Desktop**
 - OS: Windows 10
 - Desktop App v7
 - v7.3.15 (I've been experiencing this for about a week.)

**Additional context**
![image](https://user-images.githubusercontent.com/8119713/92700795-9479b380-f392-11ea-8ed9-7d758161f0ba.png)

There is definitely some shenanigans going on. The last file on the list is the file for the 1st of September but its been marked as the 31st. Not to mention the files are all strange. (the 8th was skipped, and everything is back a day)

Interestingly; 

If I select `2020-09-01` - `2020-09-01`
If I select `2020-09-30` - `2020-10-01`
If I select `2020-09-01` - `2020-10-01`

It ONLY shows me the data contained in the file `20200831.tcmetrics` (I presume.. Its 3KB and theres only 4 entries in `Full Entries Record` on the UI.

You can actually get around this problem by clicking the (X) on the date range picker (on the right hand side) and reselecting the dates. However it shows differently then to when you select the dates WITHOUT clicking the (X):

Clicking (X): 
![image](https://user-images.githubusercontent.com/8119713/92701792-c63f4a00-f393-11ea-86a0-3e7f63ceaf1d.png)

Not Clicking (X) but changing the dates: 
![image](https://user-images.githubusercontent.com/8119713/92701950-f38bf800-f393-11ea-882e-d7d2ebc81d00.png)

Due to the nature of this bug. I am happy to provide a snapshot of my metric data (I've taken a backup of its current state) in private.

Could be related to:
https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/issues/1622

**Comment by Supamiu** [comment]
Hey, sorry for the delay on that, I would like to start investigate on it and for that, as you guessed, your metrics would be nice to have.

Can you provide them to me using a zip file or something? That'd help a lot 🙂

**Comment by PatrickQuintal** [comment]
Sure thing, I'll PM you on Discord when I get the chance.
