### ISSUE TITLE
bug: Web app CSS on mobile

### ISSUE THREAD

**Issue by riarle3** [ffxiv-teamcraft/ffxiv-teamcraft#1627]
**Describe the bug**
Various elements do not fit on a portrait screen layout when using the web interface on a mobile device.  So far I've found the following:
- Maps when looking up gathering points for materials, particularly from Heavensward to Shadowbringers, are sized too large for their parent element and extend past the edges of the screen.  Able to scroll to the right, but anything cut off from the left of the screen is unviewable unless turning the screen to landscape.
- Currency spending guide extends past edges of the screen on both sides

**To Reproduce**
Steps to reproduce the gathering map behavior using Mythrite Ore as an example (2 methods)

Method 1:
1. Search for Mythrite Ore using the search feature
2. Click on the (i) information button
3. Scroll to Gathering section.

Method 2:
1. Create a new list with Mythrite Ore as an item or a gathering step
2. Find Mythrite Ore in the list, click the Mining button to view gathering map

Steps to reproduce the Currency spending guide behavior:
1. In side bar, click Helpers > Currency Spending
2. Information I used: 
 -- Yellow Crafters' Scrip
 -- 5000
 -- Famfrit
3. List should exhibit erroneous behavior on sides

**Expected behavior**
Elements should fit properly on screen while using web app on mobile devices

**Screenshots**
[Gathering map from info](https://drive.google.com/file/d/1MEE4XMXrwbZ-J-Psefn2LpPcmsOFVhD1/view?usp=sharing)
[Gathering map from list](https://drive.google.com/file/d/1MBKjCVyKlZRnr5VBObJrpRWehKg2ehNB/view?usp=sharing)
[Currency spending](https://drive.google.com/file/d/1M4FuS4zdCQHTkJpRsrbAshxCSYEnIF3H/view?usp=sharing)

**Smartphone:**
 - Device: Pixel 4 XL
 - OS: Android 10
 - Browser Firefox
 - Version 80.1.2

**Comment by louisledoux** [comment]
#1638 made a pull request with a fix for the bug :)

**Comment by Supamiu** [comment]
Fixed by #1638
