### ISSUE TITLE
feat: volume controls

### ISSUE THREAD

**Issue by jacob-keller** [ffxiv-teamcraft/ffxiv-teamcraft#1682]
**Is your feature request related to a problem? Please describe.**
The desktop version of teamcraft plays some of its sound effects at incredibly high volume. Most specifically, the volume of the sound effect for completing a material when in a list. This sound is so loud I often have to resort to lowering the application volume in Windows. However, this setting is not saved and must be re-applied after every time I launch the program.

**Describe the solution you'd like**
Ideally, add a volume control setting within the application so that it can save this volume setting.

**Describe alternatives you've considered**
Simply modifying the sound file that contains the "finished" sound effect that plays when a list entry completes would be sufficient.. but I suspect other folks do not mind or even prefer this loud volume.

**Comment by Supamiu** [comment]
Hi jacob, thank you for your suggestions.

An option for that is already present inside the settings page, in the `Desktop` tab, in the `Autofill completion sound` section.

Here you can edit the volume and the sound used for the notification.

If it's what you're looking for, I'll let you close this issue or suggest the solution you would like if it doesn't meet your needs.

**Comment by jacob-keller** [comment]
Hmm. I missed that. Thanks for pointing it out!
