### ISSUE TITLE
Blurry Font in Desktop App

### ISSUE THREAD

**Issue by A-Sparowe** [ffxiv-teamcraft/ffxiv-teamcraft#1689]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
I've  tried using the Desktop App on both of my monitors. With and without MacType turned on or having it on but disabling/excluding the desktop app. I mention MacType purely because of what it does. I doubt it's what's actually causing the issue because Having it turned off completely doesn't help as the issue still persists. 

What happens is while I'm using the Application the text displayed, along with pretty much everything being displayed, blurs or goes out of focus. Imagine DOF (Depth Of Field) in video games, but the opposite effect. Meaning whatever my mouse cursor is focusing on blurs to the point where it's super hard to read anything.

Using the webpage itself, as well as any other programs, video games, namely FFXIV, don't have this issue. I used to get it while using Firefox but I stopped using that browser a long time ago. I currently use Opera GX and rarely use Chrome only when I'm launching a webpage saved to desktop via the Chrome save to desktop feature that the browser has. 

**Screenshots**

![FFXIV_Teamcraft_8dcbqHgHhZ](https://user-images.githubusercontent.com/11279897/96754637-2ebc1680-1397-11eb-819f-c5e7aa6defc9.png)

There is a screenshot of the Desktop Application.  I've tried reinstalling it but didn't have any luck there. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 2004 Build 19041.572
 - Browser: Desktop App (Using my browser without issues. Opera GX & Advanced Chrome)
 - Version: Desktop 7.5.0 Current

**Comment by Supamiu** [comment]
Hi, this issue is coming from a hardware acceleration issue, you can disable is by editing the TC shortcut to add `-noHA` to it, and it will disable hardware acceleration, solving the issue.

**Comment by Supamiu** [comment]
I'm closing this as the `-noHA` parameter fixes the blurry fonts issue 🙂
