### ISSUE TITLE
Bug: Desktop App Very Laggy

### ISSUE THREAD

**Issue by flipwalker42** [ffxiv-teamcraft/ffxiv-teamcraft#1720]
**Describe the bug**
Desktop app is currently very laggy. Not constant, but frequently will take numerous seconds to change pages or recognize gathered items or items moved from inventory to inventory. Also affects overlays.

**To Reproduce**
1. Open Desktop app
2. I've seen issues in both opening and viewing lists as well as during gathering while viewing the optimized route.

**Expected behavior**
Expect responsive UI that reacts quickly and efficiently to inputs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Desktop App
 - Version 7.5.6

**Smartphone (please complete the following information):**
NA

**Additional context**
I've tried restarting app and FFXIV. My brother has similar issues. Did not experience the same issues with previous versions.

**Comment by utoxin** [comment]
Can confirm. (I'm the brother mentioned.)

Happy to provide any diagnostic logs needed.

**Comment by Supamiu** [comment]
It seems like your performance issues could be coming from the packet capture stuff, could you join our [discord server](https://discord.com/invite/r6qxt6P) and see if you can fix it using the pinned message in #troubleshooting channel please?

**Comment by utoxin** [comment]
This does not appear to have fixed it for me.

When the lag is happening, it's the ENTIRE teamcraft UI that's locking up. It becomes completely non-responsive (although not in the sense that windows notices that it's not responding.)

**Comment by Supamiu** [comment]
It'd be way more efficient to talk about this inside troubleshooting for faster replies and interactions.

Having steps to reproduce would also greatly help, but maybe this is coming from a hiccup in the app caused by something special on both your machines, this kind of bug is very hard to reproduce and troubleshoot, so sync communication in the form of discord would help a lot.

**Comment by utoxin** [comment]
Purely in the interests of documenting the troubleshooting that has been followed:

On the advice of Miu in the dicord, I have done an Inventory Reset, and will see if that fixes anything. Initial signs are promising, but the issue does take time to manifest, so I'll update later and we'll see how it goes.

**Comment by flipwalker42** [comment]
I've also done all the recommendations from the packet capture troubleshooting, and haven't seen any improvement. I'm on Discord and will continue trouble shooting there.

**Comment by utoxin** [comment]
It looks very likely that 7.6.2 resolved this. And it seems to be related to the lists our FC had shared with us.
