### ISSUE TITLE
feat: Unbound Gear section (Inventory Optimizer)

### ISSUE THREAD

**Issue by fivecatsrc** [ffxiv-teamcraft/ffxiv-teamcraft#1723]
I did google around to see if this could already be done somewhere but didn't find anything. Please bear in mind that I know nothing about anything, and am not sure what data you are able to easily pull or not pull at all so if this is a ridiculous request I apologize in advance.

**What feature are you proposing?**
Add a section to Inventory Optimizer showing gear in both Inventory and Armoury Chest that is currently not bound to you and can be sold on the MB.

**What is the use case for this feature?**
Allowing me not to have to stare at the top of each item as I hover over it trying to figure out if I should throw it on the MB or not.

(_Have you tried keeping cleaner bags?_ - Yes, but I'm a mess.)
(_Can't you use the setting that puts all new items in your inventory and check from there regularly?_ - Please do not bring logic into this.)

**Comment by Supamiu** [comment]
So I only checked this now as I thought it's be quite easy...

And it turns out it can simply not be done, because inventory data in TC doesn't include bound information, sorry.
