### ISSUE TITLE
bug: Cannot add Exarchic gear to a crafting list

### ISSUE THREAD

**Issue by apmorton** [ffxiv-teamcraft/ffxiv-teamcraft#1734]
**Describe the bug**
Attempting to add any Exarchic gear to a crafting list results in nothing happening.

**To Reproduce**
1. Search for "Exarchic"
2. Click to quick create a list from any of the gear (or add to existing list)
3. Observe an empty list instead of the expected gear

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: teamcraft 7.6.4

**Additional context**
Have also reproduced in an incognito window and after clearing cache to rule out any issues there

**Comment by fosspill** [comment]
This seems to be the case for any 5.4 crafting recipe that I've tried (so, also consumables)

**Comment by Supamiu** [comment]
Fixed with https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/bd88d6685b8ce2828890900de63e35476d65498c
