### ISSUE TITLE
feat: allow a way to remove previously favorited rotation folders

### ISSUE THREAD

**Issue by rftr** [ffxiv-teamcraft/ffxiv-teamcraft#1738]
While i find it great I can favorite a whole folder of someone's else rotations, I cannot find a way to remove it.
Maybe put a small button to remove a rotation, or create a favorited rotations page on the crafting session.

Just my 2 cents. Love the app, thanks for all the hard work.

**Comment by Supamiu** [comment]
In order to remove a folder from your favorites, you have to open it and click the favorite button again inside its details page.

That being said, I agree it's not ideal, I'll add a better way to do that in a future update.
