### ISSUE TITLE
Actions sort in multi-row rotations is not working properly

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#1742]
**Describe the bug**
A video is more accurate:

https://streamable.com/50v3pm

**To Reproduce**
1. Create a rotation with two lines of actions
2. Move an action from the second line

**Expected behavior**
Being able to properly move actions even when rotation has multiple lines

**Additional context**
Caused by https://github.com/angular/components/issues/13372, possible workarounds can be found inside of it.

**Comment by Matchstick92** [comment]
Hi! I've been using Teamcraft and I love it, so I'd like to help by picking this up. Do you mind if I start working on this?

**Comment by Matchstick92** [comment]
Awesome! Thanks for the hard work!

**Comment by Matchstick92** [comment]
I'm halfway through this, should be done soon!

**Comment by Matchstick92** [comment]
Sure! I've just created the draft [here](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/pull/2585).

Unfortunately with this solution transitions are not being used so it doesn't look as smooth. There's still an issue that when you drag a new action to the end of the rotation bar, it won't append at the end and becomes prepended, so I'm still looking at that. If this doesn't suit your needs do let me know!

I've also taken the liberty to refactor the following code into a function and call it wherever it's being used in the simulator page.

```
this.dirty = true;
this.dirtyFacade.addEntry('simulator', DirtyScope.PAGE);
```

**Comment by Supamiu** [comment]
Closed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/pull/2585
