### ISSUE TITLE
feat: Display hookset on the alarm page

### ISSUE THREAD

**Issue by ArutanSipdrae** [ffxiv-teamcraft/ffxiv-teamcraft#1751]
**Is your feature request related to a problem? Please describe.**
I've been meaning to complete my fishing log and that includes all the big fish. Going through ARR I never asked myself which hookset to use on legendary fishes, it was always the powerful one, but starting HW it varies from a fish to the other. Which mean every time I have to open the details of the fish to see which is the right hookset, and it's a bit long to load all the data of the fish when I just wanna see the hookset.

**Describe the solution you'd like**
A display of the icon for the hookset to use to reel in big fish under patience on the alarms.

**Describe alternatives you've considered**
I don't really have alternative solution for that, a small icon on the alarm would be enough.

**Comment by Supamiu** [comment]
Close by be035ed1c8f65b6631fd7d2d9ef84605034c82e4
