### ISSUE TITLE
feat: Desktop: Expose data from packet capture

### ISSUE THREAD

**Issue by highlyunavailable** [ffxiv-teamcraft/ffxiv-teamcraft#1759]
As a crafter who wants to sell regularly on the market, I need to identify what items I should be selling for a good profit flow.

To do so, I currently load market board listing and history data into a local SQL DB for analysis. I do this because the Universalis update rate is way too slow to be useful and it can't perform aggregation or listing over multiple items. I understand why, so I wrote my own solution to do this work.

**Describe the solution you'd like**

I'd prefer to piggyback off of Teamcraft to get the marketboard data that is parsed from network captures. To do so, I would like to be able to access the fully parsed data from Teamcraft. For example, I would like Teamcraft desktop to output the resulting [pcap](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/tree/master/apps/client/src/app/model/pcap) models somewhere from packet captures.

Ideally this is something my app could connect to (e.g. a named pipe or a websocket) but even a file per marketboard item that gets overwritten every time that item type is loaded would work. Just something at all that lets me get the data that's already there.

I can perform my own ETL and querying but I need to get the data.

**Describe alternatives you've considered**

I currently have a console app that performs its own packet capture and parsing as well as SQL loading.

I've looked at piggybacking off of the `MachinaWrapper` that Teamcraft starts, but unfortunately that still requires me to implement my own parsing, which is already done very well and maintained excellently in Teamcraft itself, hence this request.

**Comment by highlyunavailable** [comment]
Discord discussion: Too niche a use.

**Comment by Supamiu** [comment]
More details as of why this won't be done:

 - Exposing packet capture data would allow users to do stuff they want from it, including possible cheating behavior, which is not something I want to allow with TC.
 - It's really not as easy as it seems, and could have bad impact on performances for sure, especially because of the client packets.
