### ISSUE TITLE
bug: sorting by JOB in layout doesn't sort properly when using tiers display mode

### ISSUE THREAD

**Issue by highlyunavailable** [ffxiv-teamcraft/ffxiv-teamcraft#1768]
**Is your feature request related to a problem? Please describe.**
As an omni-crafter that does a lot of levekits and such for friends, I'd like to have my pre-crafts sorted by job, because it's annoying to have to swap back and forth between jobs a lot

**Describe the solution you'd like**
I would like the default layout to have its "pre crafts" section sorted by job inside each tier. I would like this to be in the default layout because I think it would be a useful addition and I'm having trouble making the layout designer do it for me.

**Describe alternatives you've considered**
I've attempted to make a custom layout to do this but it still doesn't sort it correctly.

**Additional context**
Note how there's multiple BSM and an ALC item between the second and last LTW items. Ideally, it would show all the ALC, then all the BSM, then all the LTW items (of course sorted by job priority in the settings).

![image](https://user-images.githubusercontent.com/6266125/103103584-cf68c580-45d6-11eb-9cb2-26cf0fcbc2b1.png)

**Comment by Supamiu** [comment]
I think this is more a layout sort bug than a feature request, as the whole
point of layouts is to display stuff the way you want.

iirc default layout has this sorting enabled, but it seems like it's bugged
yeah.

Le jeu. 24 déc. 2020 à 19:58, Ann Wright <notifications@github.com> a
écrit :
