### ISSUE TITLE
Bug: "Oddly Specific" Collectables (for Skysteel Tool Upgrades) Show Incorrect Rewards in Collectables Helper

### ISSUE THREAD

**Issue by b-sen** [ffxiv-teamcraft/ffxiv-teamcraft#1770]
**Describe the bug**
The Oddly Specific collectable crafts are each exchanged for the corresponding type of Gobbiegoo by speaking to Denys, and have no other purpose.  Therefore, I expect that if the Collectables Helper shows them, it will show their rewards as Gobbiegoo, and definitely not as a mix of crafters' and gatherers' scrip as in the reproduction example below.  (An XP reward is also shown for each, but since these crafts require level 80 to undertake, it is currently hard to tell if those are correct.)

**To Reproduce**
1. Go to the Collectables Helper, in the Helpers section of the sidebar.
2. Select Carpenter.  This may require an account with CRP set to 80.
3. Open the "Oddly Specific Materials Exchange (Carpentry)" panel.
4. Observe that the rewards shown do not involve any Carpenter's Gobbiegoo, and instead mix crafters' scrip (hexagonal) and gatherers' scrip (square).  The amounts are not correct either.

**Expected behavior**
Since there is no point to farming Gobbiegoo beyond two batches for each Skysteel Tool, I was pleasantly surprised that the Collectables Helper shows the Oddly Specific collectable crafts at all!  But if they are going to be shown, I expect that their true rewards for each threshold would be shown, namely the type and quantity of Gobbiegoo that Denys will trade for them.

**Screenshots**
![Carpenter Oddly Specific collectables showing mixed scrip rewards](https://user-images.githubusercontent.com/794427/103119093-d5df5780-463f-11eb-8904-69d3d3f7dca3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: Desktop v7.6.16

**Comment by Supamiu** [comment]
Hey, indeed the current collectables feature considers all the rewards as scrips while there's some exceptions. The XP, however, is accurate, it's just not shown at all inside the game, so I might aswell remove it from the display too.

I'll work on a way to include the alternate currencies for this.

**Comment by Supamiu** [comment]
After a deeper check, I can even tell that the real bug is the fact that these are shown, this page is not supposed to show anything but collectables that reward scrip 😄 because we don't have the data to figure out which reply is given by each ishgard delivery.

**Comment by Supamiu** [comment]
Fixed by 881d2275ed6694e5078ec27ba5103aae962d95e6 (forgot to link in commit again)
