### ISSUE TITLE
Desktop app packet capture submenu context

### ISSUE THREAD

**Issue by ayyaruq** [ffxiv-teamcraft/ffxiv-teamcraft#1789]
Add a submenu item to the desktop app menubar/systray icon to show the status of packet capture (green/red light?), which also expands a submenu for setting region, interface (if you want to override I guess?), maybe some other settings, as well as a control for toggling packet capture on or off. Essentially something to see and control the parser.

**Comment by Supamiu** [comment]
I'm ok with most of these but the part about changing capture interface is not about the menu, it's more about making this possible inside pcap itself.

Also, while I find interesting to be able to enable or disable pcap from tray menu, I think other settings should just require you to go to settings page instead.

That being said, I plan to group overlays in a submenu for more clarity, and I'm trying to find a good way to display pcap being enabled or not.
