### ISSUE TITLE
feat: (feature/content unlock) quest tracker

### ISSUE THREAD

**Issue by kamilrogo** [ffxiv-teamcraft/ffxiv-teamcraft#1800]
**Is your feature request related to a problem? Please describe.**
List of every quest in game with ability to check (or better "auto check") done quests.
For starters list can contain all quest that unlock something (purple ones) in game like minion, mount, duty etc. 

**Describe the solution you'd like**
I did MSQ and I have no idea what content I skipped.
There are some list of quests on web but having "(auto) checklist" would be so much easier than searching for every single quest in my quest log.

**Describe alternatives you've considered**
Using static (outdated) quests lists and checking every single quest manually in my completed quests list.

**Additional context**
none

**Comment by Supamiu** [comment]
My understanding is that you'd like a log tracker for quests? This seems overcomplex for something that very few people will actually use :/

The quest database pages contain a link to the next quest and the previous one, and ingame you can find the next quest from the quest tracking UI element that has been added with stormblood (iirc).

I'm not sure I really understand the use case for this, it seems like a very complex thing for a niche use case.

**Comment by kamilrogo** [comment]
Log tracker but just for feature/content unlocking quests. It could be just simple checklist with links to database (or even without links).

I don't need quest tracking for MSQ od Class Quests becouse game is showing if you didn't complete any of them. Don't think there is any place that shows what quests you didn't complete but shuld (for dungeons etc.) - exept having open "recommended quests" and jumping to every zone but this don't work for every quest.

For example: quest "Tricks and Stones" is beast tribe unlocking quest but it is hidden behind bunch of normal quests and I had no idea it exists.

Lists i found on wiki (Im not sure they are up to date):
https://ffxiv.consolegameswiki.com/wiki/Content_Unlock
https://ffxiv.consolegameswiki.com/wiki/Feature_Quests
https://ffxiv.gamerescape.com/wiki/Guide:Progression_and_Level_Locked_Content

Topics about this that i found in 5min search:
https://www.reddit.com/r/ffxiv/comments/2bwqob/important_side_quests_to_complete/
https://www.reddit.com/r/ffxiv/comments/6nm56w/is_there_any_way_to_check_ingame_which_content/
https://www.reddit.com/r/ffxiv/comments/30n6k8/list_of_quests_that_unlock_features/
https://www.reddit.com/r/ffxiv/comments/a5xmqn/list_of_important_side_quests/
https://www.reddit.com/r/ffxiv/comments/83ji3g/im_looking_for_a_current_list_of_all_unlockable/

I don't think it has to be complex. For starters just create a list with names of the quests and checkboxes and if people start asking about extending this feature then you will know that it will be usefull to some poeple :)

Of course I will understand if you don't want to add this option at all - it was just my simple idea for making teamcraft better :)

**Comment by Supamiu** [comment]
I think the idea is good but it doesn't integrate well with Teamcraft.

The main reason being that it would have to be maintained by hand and it means having someone update it on every patch day.

However, it could be a really nice thing for a small website kept up to date by someone else, or even included in ffxivcollect for instance.

I'll see if I can make this possible automatically, and in this case it could be interesting to have it since it'd mean not having to maintain anything at all, but if the list has to be made by hand, it'll be a nightmare if we don't have someone focused on it who has the required technical knowledge to update it asap on patch day.

**Comment by Supamiu** [comment]
I checked the data and this is not possible, it's only possible for the quests that unlock dungeons and trials, but nothing for side features like fashion report, hildibrand questline, etc

Only a handmade list would be accurate enough for what you're looking for, an automated version of it would lack a lot of useful informations.

I would be happy to help anyone who wants to build such a thing and maintain it by hand, wether it's in Teamcraft or not, but I cannot do it myself, it'd be too much time, sorry.
