### ISSUE TITLE
bug: "Copy isearch macro" does not return the "/isearch" part of the macro

### ISSUE THREAD

**Issue by aserra54** [ffxiv-teamcraft/ffxiv-teamcraft#1814]
**Describe the bug**
When selecting the "Copy isearch macro" option from an item's dropdown menu, it only returns the name of the item, without the preceding "/isearch" part.

For example, if a "Mythril-barreled Carbine" is in a crafting list, selecting "Copy isearch macro" copies "Mythril-barreled Carbine" to the clipboard, and not "/isearch Mythril-barreled Carbine".

**To Reproduce**
1. Create a new list.
2. Add any item to the list.
3. Right click on the "..." to the right of the item.
4. Select "Copy isearch macro".
5. Paste the contents of the clipboard somewhere, and observe the incorrect string was copied.

**Expected behavior**
The isearch macro is correctly copied, with the preceding "/isearch" part.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Firefox
 - Version 8.0.1

**Additional context**

It seems the behavior is coupled with the "Preferred copy type" configuration in the user settings. The behavior of "Copy isearch macro" seems to do whatever that configuration is set to, which didn't seem to be the case in the past (I believe that setting was only used for left-clicking an item).

**Comment by Supamiu** [comment]
Fixed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/92a957fb7759f38309e2456d11376118cf376762

**Comment by aserra54** [comment]
@Supamiu Not sure it's worth opening a new issue, but the tooltips are also inverted:

![image](https://user-images.githubusercontent.com/3211528/105793868-e7c25c00-5f57-11eb-9e4f-4ced603483c0.png)

![image](https://user-images.githubusercontent.com/3211528/105793934-04f72a80-5f58-11eb-9851-2414a0947df9.png)

**Comment by Supamiu** [comment]
It'll be fixed in 8.0.3 :) forgot to link the commit again 😄
