### ISSUE TITLE
bug: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Wait41** [ffxiv-teamcraft/ffxiv-teamcraft#1819]
Error: ENOENT: no such file or directory, scandir 'C:XUsers\Wait\Documents\MyGames\FINAL FANTASY XIV - A Realm Reborn'
at Object.readdirSync (fs.js:959:3)
at Object.e.readdirSync (electron/ljs2c/asar_bundle.js:5:10231)at new DatFilesWatcher
(C\Users\Wait\AppData\Localffxiv-teamcraftlapp-8.0.4\resourceslapp.asarldis..25)at Object.<anonymous>
(C\Users\Wait\AppData\Localffxiv-teamcraftlapp-8.0.4\resourceslapp.asarldi.…i23)at Module._compile (internal/modules/cjs/loader.js:1152:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
at Object.<anonymous: (electronljs2c/browser_init.js:185:3510)
![fd6f8cdd26d1ad44874323b39b8f31d](https://user-images.githubusercontent.com/57081979/105932231-30286980-607f-11eb-994c-1cc99f84a6ed.png)
![1](https://user-images.githubusercontent.com/57081979/105932278-446c6680-607f-11eb-9748-eb036ee867c3.png)

**Comment by Supamiu** [comment]
Hello, please use the template for reporting bugs instead of deleting it entirely and pasting the stack trace as an issue.

I'd love to be able to work on this issue properly, and the template provides informations that are required for me to have basic data about how to reproduce, and thus fix, the issue.

**Comment by Wait41** [comment]
Hello, my mother tongue is Chinese, so I don’t understand what you mean. Can it be expressed in another way? What information do I need to provide (what do I need to do)

**Comment by Supamiu** [comment]
I really just need one answer:

 - When are you getting this error?

**Comment by Wait41** [comment]
When installing  teamcraft

**Comment by Wait41** [comment]
Installed 8.0.4 this morning
