### ISSUE TITLE
Bug: A JavaScript error occurred in the main process & can't read the location

### ISSUE THREAD

**Issue by Nancy0Zhongliwuxin** [ffxiv-teamcraft/ffxiv-teamcraft#1823]
##Describe the bug

I'm actually having the same issue with the issue you just closed. It shows "A JavaScript error occurred in the main process. Uncaught exception" and same thing under. 
The reason I decided to install the software is that it couldn't read my location and need me to change my location in the game. Since I already uninstall the software, I can't show you the exact sentence, but it is the same sentence when I refresh the inventory. It happened when I used it the day before yesterday, and it is on the Chinese server. I'm sorry if I'm using the wrong template, thanks for your help.

## Steps to reproduce
1. Run the exe.
2. Error shows up.

##Desktop:
Windows 10
Version: Desktop 8.0.4

**Comment by Supamiu** [comment]
Please update to 8.0.5 and the issue will be fixed, you'll be able to go to the settings to change your game location.

#1819
