### ISSUE TITLE
A Javascript error occured in the main process

### ISSUE THREAD

**Issue by JaayYG** [ffxiv-teamcraft/ffxiv-teamcraft#1830]
bug : A JavaScript error occurred in the main process

**Describe the bug**

When I want to launch Teamcraft, there is a window error. In the app, nothing work, I can't import from my inventory etc. I was using the app this afternoon and everything worked.

**Screenshots**

![image](https://user-images.githubusercontent.com/78234699/106327226-07ba8e00-627e-11eb-9fd6-323cb0d84797.png)

**Comment by Supamiu** [comment]
Hi,

Did you try to restart your PC t see if the bug was fixed? I could also use your log.log file located in `%AppData%/ffxiv-teamcraft` to understand what's wrong.

**Comment by JaayYG** [comment]
I restarted like 3 times, unistall like 3 times too and nothing change

**Comment by Supamiu** [comment]
Can you provide your log file please? Also I think the troubleshooting channel on discord would be better suite for this, since it's sync communication, it makes it easier to find what causes this error.

**Comment by JaayYG** [comment]
Can you explain me in french to provide me log file pls ? My english is not too good at all, it'll be easier for me (I saw on your profile that you're french, that's why I am asking to)

**Comment by Supamiu** [comment]
- Fais Win + R
- Tappe `%AppData%/ffxiv-teamcraft`, ça va ouvrir une fenêtre explorer.
- Le fichier log.log est ici.

**Comment by JaayYG** [comment]
[log.log](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/files/5904261/log.log)

**Comment by Supamiu** [comment]
Everything inside the log file looks ok and shows that stuff is working as expected for most of the app.

Hopefully next update will fix that 😄

**Comment by SaengerItsWar** [comment]
hello I had the same error and for me it was the inventory.json that was completely empty

**Comment by JaayYG** [comment]
> Everything inside the log file looks ok and shows that stuff is working as expected for most of the app.
> 
> Hopefully next update will fix that 😄

All right, thanks !

**Comment by JaayYG** [comment]
> hello I had the same error and for me it was the inventory.json that was completely empty

Is it working right now ?

**Comment by SaengerItsWar** [comment]
for me yes

**Comment by SaengerItsWar** [comment]
> > hello I had the same error and for me it was the inventory.json that was completely empty
> 
> Is it working right now ?

yes since i deleted the inventory.json

**Comment by Supamiu** [comment]
@SaengerItsWar Thank you for your comment, now I know how to reproduce and most important, how to fix ! 

This will be fixed in next update for sure, and I'll close the issue with the commit fixing the bug 👍 It all makes sense now !

**Comment by JaayYG** [comment]
@SaengerItsWar Good to know

**Comment by JaayYG** [comment]
@SaengerItsWar Good to know and thanks :)

**Comment by Supamiu** [comment]
https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/96d66a252439c2c3846af32a52a8a3d4fdac2f4e
