### ISSUE TITLE
Bug : Currency needed for Alexander and Omega armor in Gearsets is incorrect

### ISSUE THREAD

**Issue by NewbieVenerable** [ffxiv-teamcraft/ffxiv-teamcraft#1832]
Hey there,

When you add any kind of Alexander/Omega savage gear to a gearset, the "currency needed" tab down right in the set is always double the right amount. For example, add an "Omega circlet of fending" and it's gonna tell that you need 12 Alphascape datalogs 2.0 when in the game you actually need 6. It's the same problem for every Alex/Omega savage gear. Eden savage gear seems to work fine and has the right numbers.

![image](https://user-images.githubusercontent.com/71186908/106361791-c5498d80-631f-11eb-84ab-2ed317b2afdc.png)

Very easy to reproduce, and happens on every machine i tried, on desktop app and browser site. Probably database related ?

Thanks in advance for having a look and all the good work. ;)

**Comment by Supamiu** [comment]
Hi, thank you for your report.

In the future, please make sure to use the bug report template when creating the issue so you can provide us with some usual data like app version, platform, etc. Even if it may not seem important for bugs like this, it is important to make sure we can reproduce the bug properly.

**Comment by NewbieVenerable** [comment]
Thanks, will do ! I thought about it but it didn't seem relevant for this. I sure will do it next time. :)
