### ISSUE TITLE
UX Redesign of Search / Filters

### ISSUE THREAD

**Issue by holdctrl** [ffxiv-teamcraft/ffxiv-teamcraft#1843]
Hello! Below are some of my UX findings for the search and filter feature on TeamCraft.

Please view my Figma File for referencing. 
[Figma File v1.0](https://www.figma.com/file/y1H23o38itkc5HdJ8FtdT2/FF14TC-Search-Filter?node-id=0%3A1)

### Before redesign as of Feb 10, 2021
![Before](https://user-images.githubusercontent.com/22898579/107532334-caae9f80-6b8b-11eb-8637-4e1ae2e80456.png)

### Example of redesign of search / filter
![desktopV1](https://user-images.githubusercontent.com/22898579/107528711-21b27580-6b88-11eb-96de-9cc734823543.png)

<hr>

### Problem
Filters may not be easily discoverable by users as the accordion looks separate from the search bar.
### Solution
Contain the search bar and filters together to make filters more visible. I also suggest that when a user first visits the search page, the filters should be open and visible. To allow the user to control the amount of space this window takes up, adding a means to hide the filters is an easy solution. It also requires the user to make a mental note that the filters exist in the first place.
The hide feature at the bottom helps tie the filters to the search bar instead of separating the filters and the search bar with the accordion tab. 
### Possible problems with the proposed solution shown in Figma
Users may not understand that they can hide the filters, which might need a more visible representation. I am also unsure if including the accordion tab at the bottom is feasible via coding. It might require extra work. 

<hr>

### Problem
Ambiguous features are given descriptions or instructions, which might not make sense to the user.
### Solution
Letting users select the patch via a dropdown, remove hints to exclude stats from stat filters, and give them a true/false alternative. Options are checkboxes or switches. 

<hr>

### Problem
Labels for stat filters were descriptive and made sense within the system, but even I was unsure of the difference between a stat and a stat bonus.
### Solution
Relabeling stat filters describes the difference, one for gear stats and the other for consumables. Renaming them in this fashion makes it more clear what the stats are that users are modifying. It also frees up space because a user will never use both gear stats and consumable stats to filter, so I combined them into 1 component. I checked Ant's design guidelines for tabs and replicated their standards. The only difference is I believe the tabs should take up equal space.

<hr>

### Problem
Some UI colors and text sizes are not accessible for visually impaired users.
### Solution
Reduce the value of the cobalt blue used for selected items and essential buttons (#315994). Change the light grey used on top of cobalt blue to white. 
Increase the text size for important interactable components. (This is least important, I leave text sizing up to your discretion.)

<hr>

### Problem
Worn by dropdown is not organized and easy to use; it requires hunting.
### Solution
Expand this section to icons of the jobs. It is replicated directly from the Party Finder menu within FF14. Not all of SquareEnix's UI changes are amazing, but the party finder window's revamping shows a vast improvement in organizing the data. By copying their UI, you can leverage an organization system already in use by users, so they don't need to learn anything new. Also, SquareEnix likely tested this UI rigorously, so we can rest assured that it is a viable one. :)
My original design used text labels as well as icons, but it simply used too much space. So I fell back on the UI model Square developed instead.

<hr>

### Problems with my design that might need iteration
I included a few other versions in my Figma file that explore responsiveness. I leave it up to you and your mods to ultimately decide how you wish to display the data. I tried to keep each "section" modular. You may need to reduce text sizing, margins, and paddings. 

Colors may need adjusting. I don't know if the value between the interact grey and the background is contrasted enough. You may be able to negate this by using borders or changing values. I don't think the skin/theme I made is important, so feel free to ignore any visual decisions I made.

After a week or two of implementing the new system, I think it would be good to pass out some surveys on discord and get some user feedback on the changes. It is possible we may have inadvertently created more problems for the user by changing the system's appearance.

**Comment by ArcaneDisgea** [comment]
Looks really good. Super impressed.

**Comment by Supamiu** [comment]
I really loved implementing this, thank you for this awesome and very professional  issue 👍 

![image](https://user-images.githubusercontent.com/11519203/107861164-34f16980-6e44-11eb-998d-98a8a0bb9179.png)


## Things to consider for next iteration

 - When adding a stat filter, it's possible to exclude it, but then the range becomes meaningless and could make the user think the filter excludes items with this value range instead of excluding the stat entirely. I'm already disabling the input but I feel we could do more.
 - Even if a lot of search calls are done with Item or Recipe content type, the display for other content types that have way less filters (Levequest, Action, Trait, Instance, and possibly more in the future) could probably use some optimizations.
