### ISSUE TITLE
Bug: Yellow Alumen Location is incorrect.

### ISSUE THREAD

**Issue by KevinAllenWiegand** [ffxiv-teamcraft/ffxiv-teamcraft#1845]
While in a List that has you gather Yellow Alumen (for instance if you add Sea Swallow Leather to your list), if you click on the mining icon to see the location, it is listed as:

lvl 70★★
The Inn at Journey's Head
Amh Araeng - lvl 70
X: 15.2, Y: 9.8

The actual coordinates are around X: 31.6, Y: 21.4

**Comment by Supamiu** [comment]
I just checked ingame and the coords are accurate, are you playing on korean or chinese server? Because they are not using the same version as Global one, meaning that if some nodes are changing position (like they did in 5.4 and 5.45), They get wrong coords since they're still using previous ones.

**Comment by KevinAllenWiegand** [comment]
I'm on Mateus, which is a North America server.  That's strange that it's showing up for you at the listed coords...I mean, that's nowhere near The Inn at Journey's Head - it's closer to Twine.  I'll attach a couple of screenshots as soon as I figure out how.

**Comment by Supamiu** [comment]
Can you regenerate your list please? To make sure it's using latest data sources.

**Comment by KevinAllenWiegand** [comment]
I regenerated the list, and it's showing in the correct location now.

**Comment by Supamiu** [comment]
I'm closing this as resolved 🙂
