### ISSUE TITLE
feat: update the listing when the person uploading buys an item

### ISSUE THREAD

**Issue by Aireil** [ffxiv-teamcraft/ffxiv-teamcraft#1848]
**Is your feature request related to a problem? Please describe.**

When data is being uploaded to Universalis, if the players buys an item for the listing that has just been sent, it makes the report already outdated, defeating the purpose of Universalis reports entirely.

**Describe the solution you'd like**

When the player buys an item, this item should be removed from the report, either by Teamcraft or by Universalis itself, using a specific endpoint.

**Describe alternatives you've considered**

*None, no solutions on the user end.*

**Additional context**

As of 5.45 hotfix:

Client sends `0x00BB` (MarketBoardPurchaseHandler)
- 0x00: uint64 retainerId
- 0x08: uint64 listingId
- 0x10: uint32 itemId
- 0x14: uint32 quantity
- 0x18: uint32 pricePerUnit

Server replies with `0x03DF` (MarketBoardPurchase)
- 0x00: uint32 itemId
- 0x08 uint32 quantity

**Comment by irisrune** [comment]
(Translated from Japanese by deepL)
Hi, I think it's natural to want to remove purchased items from the Universalis report (and add them to the purchase history).
However, I think that re-uploading the data to Universalis when you purchase an item will cause unforeseen problems.

For example, here are some examples
1. One player (Player X) opens a list of a particular item (Item A) in FF14.
2. Another player (Player Y) puts Item A up for sale.
3. Another player (player Z) opens the list of item A. (Player Y can open the list, for now, as long as it's someone other than Player X.)
4. Player X, who left the list of Item A open, buys one of the items.

Then, in the current processing flow, the following will happen.
1. The list of item A will be uploaded to Universalis.
2. Player Y's listing will be added to the list of item A in FF14.
3. The list of Item A with Player Y's item is uploaded to Universalis.
4. Player X's purchased item is removed from the list of item A in FF14.

However, if the upload to Universalis is done in 4., a list without Player Y's items will be uploaded.
This is akin to list rewinding, and should not be allowed to happen.

In the end, I don't think the inconsistency can be avoided unless FF14 itself starts sending and receiving lists again when items are purchased from the market.

In the meantime, one solution on the user side is to close and reopen the list after purchasing an item.

**Comment by Supamiu** [comment]
The id here would be to have Universalis expose an endpoint to remove an item from the currently registered listing.

This way, if player X buys an item after player Y updated the listing, only the item that has been bought will be removed from the listing, and the listing won't be reuploaded entirely from player X's point of view.

This is the only way to not have inconsistency when updating listings as a player buys an item.

**Comment by irisrune** [comment]
I think the approach of removing items from the uploaded list instead of re-uploading the list is a good one.

**Comment by karashiiro** [comment]
https://github.com/goatcorp/Dalamud/pull/377

Just referencing a related PR in Dalamud for bookkeeping.

**Comment by karashiiro** [comment]
Oh, and https://github.com/Universalis-FFXIV/Universalis/issues/433

**Comment by karashiiro** [comment]
This has now been implemented in Universalis, working on getting it into clients now.

**Comment by karashiiro** [comment]
Implemented in https://github.com/goatcorp/Dalamud/pull/377 - this will require adding pipes for MarketBoardPurchase and MarketBoardPurchaseHandler, and a new Universalis interface function.
