### ISSUE TITLE
bug: Macro translator incorrectly translates Waste Not II from English to Japanese

### ISSUE THREAD

**Issue by 3e849f2e5c** [ffxiv-teamcraft/ffxiv-teamcraft#1850]
**Describe the bug**
Macro translator still translates Waste Not II into "倹約II" in Japanese when it was renamed to "長期倹約" after a hidden change some time in Shadowbringers.

**To Reproduce**
1. Go to macro translator page
2. Set macro language to English
3. Enter `/ac "Waste Not II`
4. Translate to Japanese
5. Result is `/ac "倹約II"`

**Expected behavior**
For the result to be `/ac "長期倹約"`

**Screenshots**
![](https://kosblue.com/e/njbaf.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chromium
 - Version: Teamcraft version v8.0.13, Chromium version 88.0.4324.182

**Additional context**
The crafting simulator has the name set correctly when generating macros.

**Comment by Supamiu** [comment]
Close by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/352b8f3cc2744d2c944869f87068f94229ded346

Thanks for the report 🎉
