### ISSUE TITLE
Overlay clickthrough toggle doesn't toggle clickthrough

### ISSUE THREAD

**Issue by jhawkwind** [ffxiv-teamcraft/ffxiv-teamcraft#1851]
The overlay box cannot change its clickthrough state despite the change in settings.

On the settings page, under desktop, you check the option "Make overlay clickthrough" and you can still click on the overlay. Alternatively, if you tried to check the option "Clickthrough Overlays" on the system tray, the same issue appears where the overlay clickthrough state does not change.

I upgraded from a prior version before 8.0.13 and it worked, so I had the overlay clickthrough enabled, but then it won't undo the setting and kept the clickthrough. If I reset the overlay display settings using the "Reset Overlay Positions" option, the clickthrough is disabled but now I can't re-enable it after I reposition it.

The expected behavior is that if you change the Overlay Clickthrough option, it should toggle whether the overlay actually clicks-through, but instead it has no effect right now.

Currently on Windows 10 64-bit build version 20H2.
Using FFXIV Teamcraft desktop app v8.0.13

**Comment by Supamiu** [comment]
Hi, thank you for your report.

Please make sure to use the template provided to report a bug, it's not here to be annoying, just to make sure we have all the informations needed and properly structured to be able to work on the bug.
