### ISSUE TITLE
bug: disciples of the hand logs don't allow to choose recipe level

### ISSUE THREAD

**Issue by NewbieVenerable** [ffxiv-teamcraft/ffxiv-teamcraft#1864]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
In the logs section, you cannot choose the recipe level for disciples of the hand anymore. That means you can only see recipes from rlvl 1 to 5 and nothing more.  It was very useful to create lists for uncrafted stuff, which is sadly impossible right now. It works fine for gatherers. Both in desktop app and browser.

**To Reproduce**
1. Go to 'Logs'
2. Click on 'Disciples of the hand'

**Expected behavior**
There should be a tab on the left allowing to choose a recipe level range for every 5 rlvls, it's not there.

**Screenshots**
![image](https://user-images.githubusercontent.com/71186908/112692655-96631a00-8e7f-11eb-9cef-216126f22002.png)
![image](https://user-images.githubusercontent.com/71186908/112692705-a7ac2680-8e7f-11eb-832a-e63df9963cda.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 86.0.1

**Comment by Supamiu** [comment]
Hi, thank you for your report.

This bug will be fixed in 8.1.2 which will be released tomorrow GMT+1.
