### ISSUE TITLE
feat: add Free Company chest to Inventory Optimizer

### ISSUE THREAD

**Issue by nyanpasudo** [ffxiv-teamcraft/ffxiv-teamcraft#1884]
**Describe the solution you'd like**
I'd like to see Free Company chests added to the inventory optimizer.

With the ability to hide specific inventories from the optimizer, if people don't want it included, they could hide it

**Comment by Supamiu** [comment]
The reason why it's not listed in the optimizer is that FC chest tracking is really not reliable enough and half the time it'll report wrong content.

I'm going to close this as won't do, because it would require SE to change the way they're implementing FC chest for it to be reliable enough.
