### ISSUE TITLE
bug: Spear Fishing's Veteran's Trade is not clearing from Fishing Overlay

### ISSUE THREAD

**Issue by Hinalover** [ffxiv-teamcraft/ffxiv-teamcraft#1898]
**Describe the bug**
While in Fishing Overlay and while spear fishing in game, Veteran's Trade is not clearing once you exit a spear fishing node. It will hold onto the status into the next node. This will result in multiple Veteran's Trade buffs showing up at the same time.

**To Reproduce**
1. Activate Fishing Overlay
2. Switch to Fisher job
3. Trigger a Spear Fishing node
4. Spear once and then use Veteran's Trade
5. Veteran's Trade will appear in the Statuses.
6. Complete the node or use "Quite" ability to exit the node (either works)
7. Repeat steps 3 and 4 at a new node
8. A second Veteran's Trade buff will appear in the Statuses.

**Expected behavior**
Veteran's Trade buff is removed upon either exiting the node or entering a new node.

**Screenshots**
https://i.gyazo.com/6c868cc643cb118baa27721123212bde.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Desktop
 - Version: 8.1.10

**Comment by Supamiu** [comment]
I need to check how this buff is triggered, but it's not taken into account by the fishing overlay anyways since spearfishing is an entirely different system, so none of the packets will trigger for it and the report shouldn't happen for it anyways, so no wrong reports because of it at least 🙂

**Comment by Supamiu** [comment]
Should be fixed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/47a729578914d466e07ed1c5b696d4ddb615a089, will see in 8.1.13
