### ISSUE TITLE
feat: Boxplots or violin plots for fishing spot page bite times

### ISSUE THREAD

**Issue by Lodinn** [ffxiv-teamcraft/ffxiv-teamcraft#1906]
**The problem.**
Figuring out min and max possible bite time for the fish (with AND without Chum active) are a crucial part of high-end fishing.
The request is aimed to facilitate that and present the data in more readable format.

**The solution.**
Violin plots are quite possibly the best candidate for the job; box plots are also great but hard to read for people unfamiliar with them. Here is an example of what it would look like, with the relevant [Node package](https://www.npmjs.com/package/chartjs-chart-box-and-violin-plot)
The plots do not have to retain the relative bite frequency and should be normalized per-fish; bite chances are given in the bait table.
Horizontal box/violin plots would also be similar to the format CatBecameHungry uses, but better/more informative, given the bait is a selector now and more info could be displayed on a single plot.
Ideally, colors would be assigned by fish tug types also because the combination of the two [i.e. bite time + tug strength] is the only way to tell fish apart from a player's perspective.

**Describe alternatives you've considered**
Hovering over the current stacked histogram plot can be problematic, especially for extremely low bite chance fish like Sculptor; overall, it can be hard to reason about when trade-offs are concerned (e.g. how much of a chance to get fish X does one forgo by cancelling the cast early at Y seconds to avoid accidentally double hooking fish Z completely).

**Additional context**
Unfortunately, ngx seems to lack the feature, but page load times and older style timeline plots seem to be the only reason some people still stick with cbh (aside from comments from JP community that is).

**Somewhat related notes**
Performance is of concern, but it shouldn't be fundamentally different from the existing solution.
Potentially worthy of a separate discussion - maybe it is possible to move expensive calculations server-side entirely and update caches for plot data every day or week or so? This would add as many calculations as every client does while requesting the spot page to the server but eliminate the need to move large amounts of data between the client and the server every time it is requested, speeding up page loads and potentially reducing overall upkeep costs.

**Comment by Supamiu** [comment]
It looks like https://github.com/sluger/ng-chartjs-boxplot is able to do this for Angular, but I guess this woule be better as horizontal plots, and I'm not sure if the lib makes it possible or not.

**Comment by Lodinn** [comment]
From my understanding, this is indeed the integration of the lib into Angular with module magic and all that, and the original lib at least promises horizontal plots as well

> Chart
> four new types: boxplot, horizontalBoxplot, violin, and horizontalViolin

> doing as much stuff locally as possible is the way to go for us so it's as easy as possible to maintain
This is understandable; going server-side is tempting sometimes but quickly grows into an entire devops and admin mess 🤕 
I'm just asking because fishing charts specifically are one area where periodic serverside caching seems to make the most sense.

Thank you for looking into this; definitely looks painful to implement for seemingly marginal gains but I do believe it'd be a noticeable improvement in the long run!

**Comment by Supamiu** [comment]
Example with limsa lower decks:

![image](https://user-images.githubusercontent.com/11519203/117048968-e00f1200-ad13-11eb-8045-6acd0ba87884.png)
