### ISSUE TITLE
feat: Recipe finder adds crafted item to inventory when adding item to list

### ISSUE THREAD

**Issue by Corbalt** [ffxiv-teamcraft/ffxiv-teamcraft#1909]
*please prefix the issue with "feat:", example: "feat: commission board system"*

**Is your feature request related to a problem? Please describe.**
I enjoy using the recipe finder for clearing my inventory and filling out my crafting log. One thing it does not handle well are intermediate materials. If I want to find recipes for additional items I've made during my crafting session I have to delete the inventory and reimport from my inventory, saddlebag, and retainers.

**Describe the solution you'd like**
Currently when you add items to a list while using recipe finder the items used to make it are deducted from your inventory and the recipe list is updated. In addition to that, I'd like to have the product added to your inventory and any new available recipes would be added to the list.

**Describe alternatives you've considered**
I'm also okay with the recipe list not being updated immediately (I could see the search for new items being more expensive than checking if any existing items are no longer valid) -- if the inventory is still updated it'd make it easier to just hit Find Recipes again for a manual refresh.

**Additional context**
Recipe finder is my favorite feature! :)

**Comment by Supamiu** [comment]
I like this idea but I'll make it a setting inside the page, because I don't think everyone wants this behavior by default 👍
