### ISSUE TITLE
Bug: Can't open recipe finder, only black window shown

### ISSUE THREAD

**Issue by SysC0mp** [ffxiv-teamcraft/ffxiv-teamcraft#1920]
**Describe the bug**
Recipe finder is not loading, the app shows a black window without any content. 

**To Reproduce**
1. Open app
2. Click on "Helpers -> Recipe finder"

**Expected behavior**
See the expected functionality for that tab page.

**Screenshots**
![image](https://user-images.githubusercontent.com/8371978/118713386-268b6300-b822-11eb-8c3a-3b7901739d8d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Desktop app
 - Version: 8.2.3

**Comment by SysC0mp** [comment]
The same problem occurs when I try to open the "Settings" page from the top-right dropdown menu

**Comment by Supamiu** [comment]
Anything inside your console? `Ctrl + Shift + i` to open it.

**Comment by Supamiu** [comment]
I found the bug and fixed it, releasing 8.3.4 as a hotfix right now, ETA ~1h.

**Comment by SysC0mp** [comment]
Awesome, thanks a lot for the fast response & help! I'll test it again tomorrow
