### ISSUE TITLE
bug: Teamcraft 8.2.9: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by haojunsui** [ffxiv-teamcraft/ffxiv-teamcraft#1931]
After fresh install 8.2.9 and enabling packet packet feature, Javascript error dialog will pop-up. Such error dialog will continue to pop up on every subsequent app boot. After disabling the error dialog, Teamcraft app will not launch.

**To Reproduce**
1. Fresh install 8.2.9
2. Enable packet capture
3. Observe Javascript error dialog pop-up
4. Terminate teamcraft app
5. Re-launch teamcraft
6. Observe Javascript error dialog pop-up
7. Observe Teamcraft never launch afterwards

**Expected behavior**
Packet capture should be enabled and app should continue to launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/6809863/120059699-dd989300-c007-11eb-8f44-43245c330242.png)

![image](https://user-images.githubusercontent.com/6809863/120059712-e721fb00-c007-11eb-993d-346b41898862.png)

 - OS: Windows 10
 - Browser: Microsoft Edge (Chromium)
 - Version: Teamcraft 8.2.9

**Comment by haojunsui** [comment]
After reading through the log, it appears that npcap was not installed on device.

It would be nice for the installer to install external software needed.

Keeping this issue open to get awareness of the problem

**Comment by Supamiu** [comment]
The installer isn't able to do that at the moment, but the app is supposed to check for npcap to be installed or not, and then prompt the installer if needed.

This way, even if something like an aggressive antivirus removes npcap, Teamcraft will prompt to install it on startup if it's missing.

Thank you for reporting this, I'm going to push 8.2.10 as a hotfix for this.
