### ISSUE TITLE
bug: reduced animations option not taken into account

### ISSUE THREAD

**Issue by Arteneko** [ffxiv-teamcraft/ffxiv-teamcraft#1933]
### Browser

Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0

## Current behavior

My browser is configured with as little animations as possible, including every reduced motion option available.

The website disregards this setting (available, for example, through `prefers-reduced-motion` media query) and offers no way to disable animations manually.

## Expected behavior

I would expect the website to completely disable animations, or at least to tone them down to the bare minimum.

## Steps to reproduce

1. Enables reduced motion mode
2. Access the website

**Comment by Supamiu** [comment]
Hi,

Thank you for reporting this. Sadly I'm not sure I will be able to disable all the animations, but I should be able to reduce them by loading the animations module based on a media query. If I understand your setting properly, the media query is `prefers-reduced-motion: reduce`, right?

I think it should be possible to load `NoopAnimationsModule` in Angular based on it, but I'm not entirely sure about that.

**Comment by Supamiu** [comment]
I found a possible implementation, it'll be the best I can do for this, please look foward to next update to see it in action 🙂
