### ISSUE TITLE
bug: not all pre-craft items showing

### ISSUE THREAD

**Issue by J13lue** [ffxiv-teamcraft/ffxiv-teamcraft#1936]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
When using the Grand Company Supplies list option to create a crafting list I realized that not all pre-craft items (and their subsequent ingredients) are being shown. I complete the full list of ingredient collection and pre-crafting shown, only to find their are one or two more steps with more ingredients to complete the items I put on the list. This is the second time I noticed this, and it is occurring once all my crafter/gatherer classes were working with items over lvl 50. It only seems to be happening for the GCS lists. I have various other lists that all function perfectly.

**To Reproduce**
1. Go to 'Grand Company Supplies'
2. Click on 'Search'
3. Select the items that match what the Grand Company is collecting at that time
4. Check the list against the crafting menu in game and you may see pre-craft items or ingredients missing from the teamcraft list.

**Expected behavior**
I expect more ingredients and pre-craft items to be listed to accurately show the items I need to collect/craft to achieve the final crafted products I created the list for.

**Screenshots**
![TC_Bug_GameItem](https://user-images.githubusercontent.com/85815417/121794666-45d69f80-cbd8-11eb-8cad-9f59e92a6153.png)
![TC_Bug_GamePreCraft](https://user-images.githubusercontent.com/85815417/121794674-56871580-cbd8-11eb-88a7-fa3719f5ec14.png)
![TC_Bug_ListPreCraft](https://user-images.githubusercontent.com/85815417/121794679-5b4bc980-cbd8-11eb-8f85-a4a15ff525e6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 v 10.0.19041
 - Browser: Chrome v 91.0.4472.77
 - Version: Teamcraft version 8.2.10

**Additional context**
Context for the screenshots: TC_Bug_GameItem shows the in-game crafting window for an item on my list. TC_Bug_GamePreCraft shows an ingredient needed to complete that item - it, too, needs to be crafted, but is not listed as a pre-craft on my Teamcraft list. TC_Bug_ListPreCraft shows all of the pre-crafts listed on my Teamcraft list, missing the item from the previous screenshot.

**Comment by Supamiu** [comment]
Hi, thank you for reporting the issue 🙂

Can you please join the Discord server (https://discord.gg/r6qxt6P) to discuss this issue? I think it's due to a missconfiguration on your profile (if you don't have the level for some precrafts according to your profile, it'll move them to the other panels) or maybe a missinterpretation of the list system.

A sync discussion around it using Discord would help clearing these doubts and find if this issue should be closed or not together 👍
