### ISSUE TITLE
feat: Selling housing items and workshop items

### ISSUE THREAD

**Issue by lucianhatlemauri01** [ffxiv-teamcraft/ffxiv-teamcraft#1948]
*please prefix the issue with "feat:", example: "feat: commission board system"*

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Similar to how we can create commissions, it'd be nice to have a way for people to exchange un-marketable items but still exchange them through trade.
This in no way is a way to sell housing plots, just housing items or workshop items

**Describe alternatives you've considered**
Instead of having it on the app, a channel in the discord would be perfect as well 

**Additional context**
This is because a lot of crafters have these items but don't have a platform where to exchange them

**Comment by Supamiu** [comment]
Hi, while I understand your need, I'm not sure it'd be worth having it inside TC itself.

Having a channel in the Discord server might be an easy win that covers the case you're mentionning, not sure people will be using it a lot tho.

I'll think about this and eventually create the channel on Discord.

**Comment by lucianhatlemauri01** [comment]
Thank you for the reply!

In case you're going to implement it, I look forward to this feature
