### ISSUE TITLE
bug: Application window unresponsive on launch

### ISSUE THREAD

**Issue by Unknown-Zombie** [ffxiv-teamcraft/ffxiv-teamcraft#1966]
**Describe the bug**
The Windows 10 app will freeze/hang and be unresponsive to clicks or visual updates when first launched and will remain that way until the window loses focus (click away from the window and it starts working).

**To Reproduce**
1. Launch the Windows app
2. App window appears
3. Cannot click/hover over controls in the app window
4. Make app lose focus by alt-tab or clicking outside window.
5. App will start responding to clicks and hover actions.

**Expected behavior**
I expect the app to be ready to take inputs and be responsive as soon as launch is complete.

**Screenshots**
Below is a video showcasing the issue. In the video I start by launching the app and then attempting unsuccessfully to interact with controls in the app. Next, I opened the Start menu which caused the app window to lose focus, and after doing so could then interact with controls in the app window.

https://youtu.be/hLh7oUEy9Zw

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Browser: Desktop app
 - Version: 8.4.1

**Additional context**

**Comment by Supamiu** [comment]
I noticed this a while back and never found a good fix, even triggering the change detector manually every 10s for a minute didn't fix, as ugly as it is.

But it's a good idea to have it tracked as an issue to not forget about it 🙂
