### ISSUE TITLE
bug: stuck on "new character detected" popup

### ISSUE THREAD

**Issue by RumikoTheFox** [ffxiv-teamcraft/ffxiv-teamcraft#1975]
**Describe the bug**
Every time I teleport or change my class, I get a popup in the desktop app telling me a new character was detected, telling me Teamcraft needs to know which character I am playing on. However it doesn't give me an option to input anything to let it know that the character I'm on is the same one I've had verified in the app for ages. There isn't even a button to close the popup. I end up having to close the client entirely and reopen it to try to get around it. The thing is, I don't even have packet capture enabled, so I'm not sure how it's detecting I'm "changing characters" to begin with. 

I've tried resetting my settings and putting them back in from scratch, I've even tried completely uninstalling Teamcraft's app and reinstalling it and the error still persists. 

**To Reproduce**
1. Open the app
2. Have a character verified in profile and be playing on said character
3. Teleport to another location or change classes
4. See popup

**Expected behavior**
As I don't have packet capture enabled in my settings to begin with, I feel like this popup shouldn't be coming up. And even then, there's no way to dismiss this popup, give it the info it wants, or otherwise get it off the app other than to restart the app entirely. I feel like there should be a way to dismiss or give it the info it requests.

**Screenshots**
https://i.imgur.com/H5yda8b.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, though I'm using the desktop app
 - Version: v8.4.4

**Comment by Supamiu** [comment]
Hi, thanks for your report.

When this popup shows up, do you have anything inside your console? Press Ctrl + Shift + i to bring it up and go to the console tab, an error message is to be expected.

Also, do you have any kind of drive sync system? Like OneDrive or Google Drive that syncs your character data folder?

I recommend joining the discord server to troubleshoot this in realtime since it doesn't look like an issue everybody's getting, but I'd love to know if there's anything red inside your console first 🙂 .

**Comment by RumikoTheFox** [comment]
The error is

main.85be5ad673d858237f25.js:1 ERROR TypeError: Cannot read property 'Character' of null
    at W (main.85be5ad673d858237f25.js:1)
    at Go (main.85be5ad673d858237f25.js:1)
    at Ho (main.85be5ad673d858237f25.js:1)
    at main.85be5ad673d858237f25.js:1
    at Ho (main.85be5ad673d858237f25.js:1)
    at hs (main.85be5ad673d858237f25.js:1)
    at main.85be5ad673d858237f25.js:1
    at Ho (main.85be5ad673d858237f25.js:1)
    at main.85be5ad673d858237f25.js:1
    at Ho (main.85be5ad673d858237f25.js:1)

It keeps spamming the error until I close the client. I don't have OneDrive or GDrive synced to my pc.

**Comment by Supamiu** [comment]
Can you join the discord server or DM me at Miu#1568 for this please? I'll need your user id to check that everything's ok on your profile, because it looks like something's wrong and I can fix it 🙂
