### ISSUE TITLE
bug: invalid listings upload to Universalis

### ISSUE THREAD

**Issue by karashiiro** [ffxiv-teamcraft/ffxiv-teamcraft#1976]
**Describe the bug**
Most of the time, Universalis market board listings updates don't seem to include valid listings.

**To Reproduce**
1. (Optional) Check an item page on Universalis
2. View the item in-game with packet capture enabled
3. Wait up to a minute for Universalis's frontend cache to flush
4. Refresh the page
5. The last upload time will be updated, but the listings will be unchanged.

**Expected behavior**
The listings should be changed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Desktop app
 - Version: 8.4.4

**Additional context**
 - The only pcap changes since the previous update were some small CN things that should not be relevant to this
 - Before this update, upgrading npcap to v1.50 solved this
 - Downgrading npcap back to v1.10 from v1.50 does not fix the issue
 - It happens seemingly randomly
   - I tested this on RawSocket mode and had it happen about 50% of the time
   - Someone else tested this on npcap and had it happen somewhere around 75% of the time
 - It's sending some acceptable upload, because it's updating my timestamps
   - The payload probably has a valid history array
 - It works 100% of the time in Dalamud, so it's probably not an issue on my server

**Comment by karashiiro** [comment]
I found a related bug in which the content ID being null would send an upload anyways, leading to a parsing error when it was read as a BigInt, but that's likely unrelated.

That error should be fixed with https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/168e1bfaa2f8dee315d89c1daf5f7f26f4dcd735.

**Comment by karashiiro** [comment]
Should also consider swapping out the bundled version of npcap with the [latest version](https://nmap.org/npcap/dist/npcap-1.50.exe) at some point, since that fixed this problem previously.

**Comment by Supamiu** [comment]
I updated the bundled npcap installer to 1.50 in https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/5235a40bb4d205ac611de768dd79fbf984274ef9

**Comment by Supamiu** [comment]
Closing this as it seems like it has been fixed by the contentId fix and npcap update

**Comment by karashiiro** [comment]
Didn't get a notification for this, but that's on my website. It means that an upload happened, but evidently there was no actual listings data in the upload.

**Comment by karashiiro** [comment]
This was reported again in TC recently: https://discord.com/channels/355013337748209665/639503745176174592/918001393749602364
I had the person who reported it use our new standalone uploader (it shares code with the ACT plugin, so it's not anything new), and uploads worked fine with that. Presumably this isn't a driver issue, or otherwise a Machina issue, but rather something in pcap-ffxiv.

**Comment by karashiiro** [comment]
Or in TC's pipeline.
