### ISSUE TITLE
bug: contributing.md gives incorrect instructions for setup

### ISSUE THREAD

**Issue by AlaunusLux** [ffxiv-teamcraft/ffxiv-teamcraft#1978]
**Describe the bug**
When following the instructions on https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/staging/CONTRIBUTING.md , the project will run, but will give an error page about the version being wrong.

**To Reproduce**
Follow the 'Prepare your environment' and 'Live Development Server' steps in the link above.

**Expected behavior**
The project should run with no issues after following the documentation.

**Desktop (please complete the following information):**
 - OS: Windows 10, VS Code
 - Browser: Chrome

**Additional context**
Additional steps for setup might include directions for installing yarn, as in this link: https://classic.yarnpkg.com/en/docs/install/#windows-stable
   `npm install --global yarn
   `

Additionally, any commands referenced in CONTRIBUTING.md that read 'npm' might instead read 'yarn'

```
yarn install
yarn start
```
etc

**Comment by AlaunusLux** [comment]
Mentioning the need for [creating a beta account](https://beta.ffxivteamcraft.com/) may help clear up any potential confusion for new contributors as well.

**Comment by Supamiu** [comment]
You're god damn right, the contributing guide needs an update and right now, contributing without joining the discord server is almost impossible due to how badly written the guide is.

I'll try to allocate some time updating the guide, thanks for reminding me and creating an issue so my OCD makes me want to do it just to have one less issue opened.

**Comment by AlaunusLux** [comment]
Of course! I figured if no one else got around to it, I'd grab it when I felt more comfortable contributing. Meanwhile, the issue existing means it doesn't slip through the cracks. 

Glad your eyeballs are on it!
