### ISSUE TITLE
bug: Voyages does not register Submarine Sectors Discovered

### ISSUE THREAD

**Issue by Hinalover** [ffxiv-teamcraft/ffxiv-teamcraft#2001]
**Describe the bug**
After setting up the free company voyage tracker in Teamcraft, the sectors discovered registers the number of airship sectors discovered but not the submersible sectors discovered.

**To Reproduce**
1. Set up the Free Company Voyage tracker in Teamcraft
2. look at the number of sectors discovered
3. Select a Submersible in-game.
4. View navigational charts
3. Compare to the available in-game submersible sectors available.
4. Teamcraft Voyages shows zero sectors discovered.

**Expected behavior**
The sectors discovered should show the correct number of voyages discovered

**Screenshots**
![image](https://user-images.githubusercontent.com/10355909/135287971-832109b6-eeae-43d0-a7f3-298dcd3d6ca8.png)
![image](https://user-images.githubusercontent.com/10355909/135288022-9b2c297d-d260-4913-8e70-d5f85df2b5be.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8.5.9

**Additional context**
I am not sure if this is due to the fact that Submersibles have up to 3 maps they are looking at compared to 1 for Airships and teamcraft is not looking at that difference.

**Comment by Supamiu** [comment]
@shambarick You might want to take a look at this.

**Comment by shambarick** [comment]
The opcode might be wrong. I'll take a look at it when I have some time or next week.
