### ISSUE TITLE
feat: Inventory Optimizer: Sell low-value items

### ISSUE THREAD

**Issue by filliph** [ffxiv-teamcraft/ffxiv-teamcraft#2035]
Currently, I have no idea if I'm keeping items that can be bought from the Market Board for at-or-near the vendor value. These items can (likely) be safely discarded to save inventory space.

I would like the Inventory Optimizer to look up the current Universalis data to see the current & historical price records, and work out whether it would be feasible to sell the item. 
This might require some form of averaging on the historical data, and/or checks to see whether there's a large spread in the historical sale data (both in terms of price and time), to get an idea of whether the market for this item is stable.

**Comment by Supamiu** [comment]
I'm closing this as we have it inside the Discord's `#feature-requests` channel.

Please make sure to use the template next time you're submitting an issue to this repo, it's really useful even just for the formatting it provides 👍
