### ISSUE TITLE
bug: Pin fish in FFX|V Fish Tracker App takes 2 seconds

### ISSUE THREAD

**Issue by LunaPg** [ffxiv-teamcraft/ffxiv-teamcraft#2037]
*bug: Pin fish in FFX|V Fish Tracker App takes 2 seconds"*

**Describe the bug**
When you pin a fish, it take 2 seconds for the frontend to actually pin the fish, without any backend calls.
(Looks like, in the console, it sorts again the whole fishing list)

**To Reproduce**
1. Got to Pin fish in FFX|V Fish Tracker App takes 2 seconds
2.  Click on a fish to pin
3.  Wait for 2-3 seconds

**Expected behavior**
It should be instant

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 8
 - Browser : Brave destktop
 - Version Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 -  N/A
 
**Additional context**
- Do not sort the whole array has it has O(n) complexity.
- Checking the how many redraw has been called with Chrome performance profiler
- Printing in console add some lag in browser
-  Check possible optimisation 
-  Maybe minifying code could help a bit

**Comment by Supamiu** [comment]
Hi, that's a nicely detailed issue but unfortunately it's the wrong repo.

I am not the owner of Fish Tracker app. I suppose you mean CarbunclePlushy, which is located at https://github.com/icykoneko/ff14-fish-tracker-app

I'm closing this as irrelevant for Teamcraft, since there's nothing I can do.

**Comment by LunaPg** [comment]
Thanks for the answer Supamiu ! 

I'll move my issue :)
