### ISSUE TITLE
bug: progress bar isn't updating for sub groups

### ISSUE THREAD

**Issue by VyseGolbez** [ffxiv-teamcraft/ffxiv-teamcraft#2057]
**Describe the bug**
The progress bar for sub groups (i.e. gatherables) in a crafting list doesn't update properly. While a group still closes and turns green once everything is marked as completed, it no longer shows how much progress has been made in a group (i.e. 50% done)

**To Reproduce**
1. Create any list with multiple crafted items so that several materials are needed to complete the list
2. Mark one of the materials in, say, gatherables as completed
3. See that the percentage bar in that group doesn't update 

**Expected behavior**
I expected the progress bar for subgroups to still update like they did in the previous versions.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Desktop App, also seems to happen on Firefox
 - Version: 9.0.1

**Comment by Supamiu** [comment]
Hey, thanks for your report :) I fixed the bug for next update.
