### ISSUE TITLE
bug:  Log Tracker unable to open First Section in a list when Hide Completed is used

### ISSUE THREAD

**Issue by Havondor** [ffxiv-teamcraft/ffxiv-teamcraft#2061]
**Describe the bug**
When you use the Hide Complete feature on the Log Tracker (Helpers -> Log Tracker) the first Section (by section I mean the List of Groupings such as Housing (1) or Housing (2) found on the Left side of the screen) is not able to be open when you go to a New List (i.e. CRP, MIN, BTN, etc.) 

**To Reproduce**
1) Go to the Log Tracker 
2) Turn Hide Completed Items on 
3) Go to a New List i.e. CRP, MIN, BTN, ETC
4) Attempt to click on the First Section in the List 
5) Unable to see the items in the First Section
WORKAROUND: Click on a different Section i.e. Housing (2) instead of Housing (1) and then click to the original Section and it works. This Workdaround does not work if ONLY one section is left on a list.

**Expected behavior**
You should be able to see into the first section of a list without needing to click on another section first.

**Screenshots**
![image](https://user-images.githubusercontent.com/3629148/142463517-d813fbaa-4eac-4c45-a2eb-13b582c21b01.png)
![image](https://user-images.githubusercontent.com/3629148/142463685-d807a940-e294-4724-99fc-2dfda7064b4b.png)
![image](https://user-images.githubusercontent.com/3629148/142463736-1465b190-dd01-493a-8959-9c840c4f441a.png)
![image](https://user-images.githubusercontent.com/3629148/142463766-c3f88aa6-229c-4879-8669-1592e442f4c5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Desktop App
 - Version 9.0.3

**Comment by Supamiu** [comment]
This is a known bug that's related to the way ant design handles tabsets selection, I do'nt think we'll be able to fix it without refactoring the way Log Tracker displays stuff, sadly.

Doesn't mean it won't be done, just that it won't be done too soon 😄

**Comment by Supamiu** [comment]
I believe this is fixed now with the new log tracker data architecture. Let me know if it's not the case and I'll reopen.

**Comment by Lusankya** [comment]
Not OP, but this appears to have reverted.  Can replicate on desktop and web with TC 11.0.2.  Unsure how long ago the reversion happened.
