### ISSUE TITLE
feat: display a warning for anonymous users regarding packet capture not working

### ISSUE THREAD

**Issue by deathzombee** [ffxiv-teamcraft/ffxiv-teamcraft#2071]
- *please prefix the issue with "feat:", example: "feat: commission board system"*

Please add documentation, or get the attention of user using ffxiv-teamcraft with no character data to first register an account, and associate it with their lodestone identity.

I spent time troubleshooting why ffxiv-teamcraft couldn't pull up packet capture that ACT has no problem accessing, firewall isnt blocking, and client isn't interfering with. After solving my problem, I ventured to the discord to find out someone else also had this issue which proper documentation would solve.

- **Describe the solution you'd like**

I'm not familiar enough with this project to make a pull with an updated readme, or to implement documentation, but I can contribute to it when SWIM adds it to current documentation, or implements documentation in a way that suits the established project.

- **Describe alternatives you've considered**

Alternatives would be to force users to join your discord, which I actively have to use another discord account, or get rid of servers since this caps at 100, I view this as a negative feature.

**Comment by Supamiu** [comment]
I don't think this is a documentation issue, since nobody ever reads the TC documentation anyways.

It's more about showing the user by using a banner warning that packet capture won't work properly without an account, which is certainly doable.

**Comment by deathzombee** [comment]
Something like that is perfect. This will keep people out of the troubleshooting room, being referred to the packet capture troubleshoot bot for sure.
