### ISSUE TITLE
Lists stuck on an infinite loading loop for my account

### ISSUE THREAD

**Issue by Nortfor** [ffxiv-teamcraft/ffxiv-teamcraft#2085]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
When trying to check my list, it's stuck on an infinite loading loop, when I logout it's fine to check the list, only when logged in to my account does it do it.
Happens within both the desktop app and on the browser one. Only when logged into my account..

**To Reproduce**
Go to List within my account

**Expected behavior**
For it not to be loading indefinitely

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera GX
 - Desktop App version: 9.1.6 (also had the issue just before with 9.1.5)

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

Will not openly give my e-mail in here at least, hopefully understandable, not sure if I can share my UserID within Teamcraft freely however

**Comment by Supamiu** [comment]
Hi, you can share your user id freely, it has no security impact on your account.

However, if you could check the content of your console, that would be nice (F12 on web, then "Console" tab, I'm expecting red stuff here).

**Comment by Nortfor** [comment]
UserID: 10n2iVppORhrYbekQHsW53YXRMl2
![image](https://user-images.githubusercontent.com/12272647/145043909-df0aeaaa-d8bc-4054-b306-e4631a64668b.png)
And here is the console, my Adblock is disabled, so not sure why those errors exist... 🤔

**Comment by Supamiu** [comment]
I fixed it inside the database, should be working properly again now 😄

**Comment by Nortfor** [comment]
Yeap it's working again, thank you!
