### ISSUE TITLE
feat: Levequests in range of crafters

### ISSUE THREAD

**Issue by Tusky** [ffxiv-teamcraft/ffxiv-teamcraft#2093]
**Is your feature request related to a problem? Please describe.**
Anytime I open up the Levequest page, the default fields are levequests in range of 1-10.
https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/60908f99ef1ac95456c3a72ed5c229beaf1a9c5f/apps/client/src/app/pages/levequests/levequests/levequests.component.ts#L46
So when I open up the page, and start searching I always get no results back immediately, unless I'm looking for a leve in 1-10 range obv.

**Describe the solution you'd like**
I'd like it to be always the current expansion's max level as an ending range, so when user's search for a quest it does show up, since everything would be included in the 1-90 range.

**Describe alternatives you've considered**
As an alternative if that's related to DB load, it could use a formula of like [currentCrafterLevel - 10] - [currentCrafterLevel + 10/maxCrafterLevel], or just preset values based on crafter level, like if you are 64: 60-70, 69: 60-70, 70: 70-80

**Additional context**
Mainly how I use Levequests page is especially on new expansion launch is
- Set my job
- Get a range 80-90
- Show Impact on XP
- Use global exp
- Fill out experience field

And then I'll plan out a list of levequests that gives the most XP to get to 90 quickest, gather all the materials, and craft and hand them in.
Once I'm max level, the only reason I'd use this page is to quickly add a levequest I want to do, for money or whatever reason.
Both of these require me to manually go into the level range and type in high enough number, and I honestly don't see the point of it listing 1-10 range by default.

**Comment by Supamiu** [comment]
I'll change that to maxLevel, because connecting the current level for your crafter here is much more complicated than it might look, and I think 80-90 will be the most wanted range.
