### ISSUE TITLE
bug: Error at reading ECONNRESET

### ISSUE THREAD

**Issue by AkatsukiP** [ffxiv-teamcraft/ffxiv-teamcraft#2097]
**Describe the bug**
I updated to v9.2.4 and when it opened, an error poped up. It says 

> A JavaScript error occured in the main process.
> Uncaught Exception:
> Error: read ECONNRESET
>     at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)

I reinstalled and cleared cache, this thing still pop up at start.

I'm not sure if this next problem is related but seems relevant. So I'll put it here:
"Autofill stats using packet capture" doesn't work, whether using RawSocket. It doesn't do anything.
While i check or uncheck using RawSocket feature, the previous error about read ECONNRESET also pops up.

**To Reproduce**
1. Open Teamcraft v9.2.4
2. Error pop up.

3. Go to "Settings" -> "Desktop" -> "Packet Capture"
4. Check / Uncheck "Use RawSocket for packet capture"
5. Same error pop up.

6. Go to "Profile" -> ”Jobs“ -> "Autofill stats using packet capture".
7. Open UI normally and nothing would happen when i change jobs.

**Expected behavior**
No error pop up at start and packet capture works well.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Desktop Version.9.2.4

**Comment by AkatsukiP** [comment]
Hi, after some investigation i want to add some further information.
Sometimes another error pops up, it says
> A JavaScript error occured in the main process.
> Uncaught Exception:
> Error: connect ETIMEDOUT 151.101.76.133:443
> at TCPConnectWrap.afterConnect [as oncomplete] (node:net: 1146:16)

and in log file it says

> [2021-12-12 00:44:19.749] [info]  DAT Watcher started on C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
> [2021-12-12 00:44:25.207] [debug] The Npcap service was detected, starting Machina
> [2021-12-12 00:44:25.375] [info]  Starting PacketCapture with options: {"monitorType":"WinPCap","region":"Global","exePath":"C:\\Users\\斯哈\\AppData\\Local\\ffxiv-teamcraft\\app-9.2.4\\resources\\MachinaWrapper\\MachinaWrapper.exe"}
> [2021-12-12 00:44:25.603] [info]  Packet capture started
> [2021-12-12 00:45:22.301] [debug] The Npcap service was detected, starting Machina
> [2021-12-12 00:45:22.468] [info]  Starting PacketCapture with options: {"monitorType":"WinPCap","region":"Global","exePath":"C:\\Users\\斯哈\\AppData\\Local\\ffxiv-teamcraft\\app-9.2.4\\resources\\MachinaWrapper\\MachinaWrapper.exe"}
> [2021-12-12 00:45:22.690] [info]  Packet capture started
> [2021-12-12 00:45:39.925] [info]  []
> [2021-12-12 00:45:39.934] [info]  DAT Watcher started on C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
> [2021-12-12 00:45:39.984] [info]  Opening from argv :  []
> [2021-12-12 00:45:44.531] [debug] The Npcap service was detected, starting Machina
> [2021-12-12 00:45:44.729] [info]  Starting PacketCapture with options: {"monitorType":"WinPCap","region":"Global","exePath":"C:\\Users\\斯哈\\AppData\\Local\\ffxiv-teamcraft\\app-9.2.4\\resources\\MachinaWrapper\\MachinaWrapper.exe"}
> [2021-12-12 00:45:44.952] [info]  Packet capture started
> [2021-12-12 00:46:29.771] [info]  Starting PacketCapture with options: {"monitorType":"RawSocket","region":"Global","exePath":"C:\\Users\\斯哈\\AppData\\Local\\ffxiv-teamcraft\\app-9.2.4\\resources\\MachinaWrapper\\MachinaWrapper.exe"}
> [2021-12-12 00:46:29.975] [info]  Packet capture started
> [2021-12-12 00:46:34.395] [debug] The Npcap service was detected, starting Machina
> [2021-12-12 00:46:34.518] [info]  Starting PacketCapture with options: {"monitorType":"WinPCap","region":"Global","exePath":"C:\\Users\\斯哈\\AppData\\Local\\ffxiv-teamcraft\\app-9.2.4\\resources\\MachinaWrapper\\MachinaWrapper.exe"}
> [2021-12-12 00:46:34.729] [info]  Packet capture started
> [2021-12-12 00:46:35.858] [info]  Starting PacketCapture with options: {"monitorType":"RawSocket","region":"Global","exePath":"C:\\Users\\斯哈\\AppData\\Local\\ffxiv-teamcraft\\app-9.2.4\\resources\\MachinaWrapper\\MachinaWrapper.exe"}
> [2021-12-12 00:47:00.118] [info]  Packet capture started
> [2021-12-12 00:47:02.887] [debug] The Npcap service was detected, starting Machina
> [2021-12-12 00:47:03.000] [info]  Starting PacketCapture with options: {"monitorType":"WinPCap","region":"Global","exePath":"C:\\Users\\斯哈\\AppData\\Local\\ffxiv-teamcraft\\app-9.2.4\\resources\\MachinaWrapper\\MachinaWrapper.exe"}
> [2021-12-12 00:47:03.211] [info]  Packet capture started
> [2021-12-12 00:47:06.454] [info]  Starting PacketCapture with options: {"monitorType":"RawSocket","region":"Global","exePath":"C:\\Users\\斯哈\\AppData\\Local\\ffxiv-teamcraft\\app-9.2.4\\resources\\MachinaWrapper\\MachinaWrapper.exe"}
> [2021-12-12 00:47:06.667] [info]  Packet capture started
> [2021-12-12 01:43:05.137] [info]  []
> [2021-12-12 01:43:05.149] [info]  DAT Watcher started on C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
> [2021-12-12 01:43:05.223] [info]  Opening from argv :  []
> [2021-12-12 01:43:15.631] [debug] The Npcap service was detected, starting Machina
> [2021-12-12 01:43:15.785] [info]  Starting PacketCapture with options: {"monitorType":"WinPCap","region":"Global","exePath":"C:\\Users\\斯哈\\AppData\\Local\\ffxiv-teamcraft\\app-9.2.4\\resources\\MachinaWrapper\\MachinaWrapper.exe"}
> [2021-12-12 01:43:16.009] [info]  Packet capture started
> [2021-12-12 01:45:09.361] [info]  []
> [2021-12-12 01:45:09.373] [info]  DAT Watcher started on C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
> [2021-12-12 01:45:09.423] [info]  Opening from argv :  []
> [2021-12-12 01:45:14.604] [debug] The Npcap service was detected, starting Machina
> [2021-12-12 01:45:14.778] [info]  Starting PacketCapture with options: {"monitorType":"WinPCap","region":"Global","exePath":"C:\\Users\\斯哈\\AppData\\Local\\ffxiv-teamcraft\\app-9.2.4\\resources\\MachinaWrapper\\MachinaWrapper.exe"}
> [2021-12-12 01:45:15.006] [info]  Packet capture started

in this log you can tell i tried many times.
Anyway i hope it's helpful, thank you!

**Comment by Supamiu** [comment]
Should be all good with 9.2.6 that will be released tomorrow.
