### ISSUE TITLE
bug:  Yellow scrip labels instead of White

### ISSUE THREAD

**Issue by mlabastida** [ffxiv-teamcraft/ffxiv-teamcraft#2111]
**Describe the bug**
When i open a trade panel modal on a crafting list after the exchange location the label is Yellow Crafters' Scrip Exchange (Lv. 50) instead of White Crafters' Scrip Exchange (Lv. 50)

**To Reproduce**
1. Create a quick list crafting Ukha
2. Click on Trade on Solstice Garlic
3. Scroll down to the price part
4. See error on the title of that area 

**Expected behavior**
Expected the label to be White Crafters' Scrip Exchange (Lv. 50)

**Screenshots**
![image](https://user-images.githubusercontent.com/1307946/146528250-930c234e-012d-45e3-880e-afa44f289a1b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 9.2.10

**Comment by Supamiu** [comment]
I don't think it's possible to trade using yellow scrips anymore ingame, might need a check. Because the references to the yellow scrips are all gone in the game data. This might be misslabeling inside the game itself.
