### ISSUE TITLE
bug: can't load profile

### ISSUE THREAD

**Issue by marklabrecque** [ffxiv-teamcraft/ffxiv-teamcraft#2113]
**Describe the bug**
When logging into the desktop app (with Ncap installed), the loading animation goes on forever never loading the profile. When this happens, I get locked out of most of the features. There are no errors in the javascript when this occurs.

**To Reproduce**
1. Go to Anonymous -> Login
2. I login to my account attached to the email mark.labrecque@gmail.com
3. It never loads

**Expected behavior**
When I log in to my Teamcraft account, it should properly authenticate and show my profile picture.

**Screenshots**
![image](https://user-images.githubusercontent.com/16848211/146782650-ef6b938f-73a0-490c-a3ac-3d363a437203.png)
![image](https://user-images.githubusercontent.com/16848211/146782692-d8f8dc6b-1bc6-40fe-abbb-40b2943aa78c.png)
![image](https://user-images.githubusercontent.com/16848211/146782801-41a0a412-dbee-4ac5-8d04-962786c1e5dd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10/11 (reproducible on both)
 - Browser: desktop application, electron
 - Version 9.2.11

**Additional context**
I used to use this app frequently and it always worked perfectly for me. I just reinstalled it (on a freshly installed version of Windows) and it worked the first time, but after that it consistently fails to log in.

**Comment by Supamiu** [comment]
One of the characters you had linked to your profile was deleted or its lodestone id has been reassigned, I fixed your account and I'm closing this as resolved.

You might want to edit the issue to remove your email from it 🙂

**Comment by marklabrecque** [comment]
Good point. Thanks so much for the quick resolution to this!
