### ISSUE TITLE
bug: Gatherer's Guerdon Materia VIII listed as purchasable with 500 purple scrips

### ISSUE THREAD

**Issue by jacob-keller** [ffxiv-teamcraft/ffxiv-teamcraft#2116]
**Describe the bug**

The Gatherer's Guerdon Materia VIII is listed as purchasable with 500 purple scrips from the "white scrip lvl80 gathering materia" menu.

**To Reproduce**
1. Go to the Gatherer's Guerdon Materia VIII item listing
2. View the ways to obtain the item
3. Notice that it incorrectly defaults to purple scrips when thats not an available option.

**Expected behavior**
Methods to obtain the item should be accurate, and not list the invalid option.

**Comment by Supamiu** [comment]
Hey, thanks for your report.

This has been fixed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/94fb9566fbbc1f92ab8284ab77b158ffe5b02688 and will be in next update 🙂
