### ISSUE TITLE
feat: new profits features system

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#2125]
**Is your feature request related to a problem? Please describe.**
At the moment, profit helpers for TC are split in various pages, not to mention the pricing mode that's one of the oldest features that have never been revamped in the project.

**Describe the solution you'd like**

This is a non-exhaustive list that will need more data as ideas are added, but here is what I have in mind for now:

 - [ ] New pricing mode separated from lists, with a separate page and a recommendation engine.
 - [ ] New "how to make profit" feature based on your stats, your retainers, your server's economy status.
 - [ ] Possibly include how much time you have to make profit, so the app can tell you what's possible and worth with the time you have.

**Additional context**

This will require a large cache system for MB data to make sure Universalis isn't spammed too hard, @karashiiro 's point of view on how to make this possible is definitely needed. 

This could use gubal or a separate DB that would be proxified by data Cloud Run instances to grab cached data and make sure we don't hammer the API with our thousands of calls with different IPs, because we'll need pricing data for almost every items on every servers.

**Comment by karashiiro** [comment]
That's 13139 items times 89 worlds, which comes out to 1169371 different records, if you're only using the current data endpoint. That's only about 2.5 GB of data (in MongoDB), and I don't know how the data types translate into sizes in your DB, but you should be able to use that to plan this a bit. Of course, if you want the maximum history data, all of this goes out the window (that's at least a couple hundred GB more).

As for the actual requests, I currently have it set to 14r/s, so doing 100-item bulk requests for each world would only take about 14 minutes, if I'm napkin-mathing correctly. One decent way of doing this would be to populate your database once, and then poll the most-recent endpoint for updates, so you would only be doing the minimum number of requests to keep your database updated. You should also set the `statsWithin` query parameter on current data endpoint requests to 0 and calculate any metric you need on your end. This won't be a huge savings, but it'll add up over time.

Besides that, try to put a lock on your cache to avoid a cache stampede?

Also, I'm changing hosting providers early next month, so I'll keep you updated with how rate-limiting changes after that.

**Comment by Supamiu** [comment]
So I've got few questions regarding your plan on updating data:

 - How often should I call the most-recent endpoint? I tried it and noticed it's depending on a # of entries instead of a set time, making it hard to rely on for keeping things updated I think.
 - How viable would a "fetch everything once and compute from that" approach be for your end? It'd mean 14req/s for around 15min every hour or so.
 - Is there anything that could give me a list of updated items since a given date on a given server? (Or could I try to contribute such an endpoint?)

**Comment by karashiiro** [comment]
1. Every few seconds at most, since I don't keep an indefinite record of uploads. I said on Discord that those endpoints are fast, and I really meant it.
2. That's what sheet users do, so it's probably fine? This is the easiest option, and once I migrate the server this week or next week it should be totally fine wrt server load.
3. There is not currently, but if you want to create one that'd be great. I hadn't considered it before since it seems like a lot of data, but it should be fine so long as it keeps at most one record per item per world. If you want to contribute that, we can discuss specific designs.

**Comment by karashiiro** [comment]
Ultimately, server load (CPU/RAM/Disk) is the least of my concerns - I'm much more concerned about bandwidth, which is a far more significant bottleneck.
