### ISSUE TITLE
bug: Desktop app going blurry

### ISSUE THREAD

**Issue by Praedyth-Rey** [ffxiv-teamcraft/ffxiv-teamcraft#2126]
On the Desktop app, using a fresh install, the UI elements go blurry randomly with no real consistency

**To Reproduce**

1. Just open it
2. Wait

**Expected behavior**

It to not be blurry and clearly readable

**Screenshots**

![image](https://user-images.githubusercontent.com/77774191/147812694-f8761ee8-b02a-407c-9d7b-2062ba896605.png)

**Desktop**
 - OS: Windows 11, Latest build as of issue open
 - Browser: Firefox but N/A for this issue
 - Version: 9.3.4

**Additional context**

NVIDIA 3D Application settings _might_ be the cause, but unsure at the moment.
Driver Version 497.29

**Comment by Supamiu** [comment]
This is due to nVidia applying its own acceleration to the app, disable its antialiasing thing and everything will work fine again 👍

**Comment by votommy** [comment]
I found that turning Antialiasing - Mode to Off didn't fix it, but turning off Antialiasing - FXAA did work. You can leave the Mode as default as long as FXAA is off.
