### ISSUE TITLE
bug: base for level 90 machinist gearset appears wrong

### ISSUE THREAD

**Issue by dwsdolce** [ffxiv-teamcraft/ffxiv-teamcraft#2129]
The base stats for level 90 Machinist are:

Dexterity | 437
Critical Hit | 380
Determination | 340
Direct Hit | 380
Skill Speed | 380
Vitality | 340

on the website but are:

Dexterity | 446
Critical Hit | 400
Determination | 390
Direct Hit | 400
Skill Speed | 400
Vitality | 393

in the game.

I surmise that the stats are incorrect in the game settings. 

To reproduce, check the base specs on a level 90 machinist in 6.01. Use just the weapon and remove all although gear and then subtract the stats from the weapon.

This was seen on Windows 10 using Chrome 96.0.4664.110.

**Comment by Supamiu** [comment]
Should be fixed by 9.4
