### ISSUE TITLE
feat: In inventory  tab,  ability to see  items in Armoire and Glamour Dresser

### ISSUE THREAD

**Issue by polanskya** [ffxiv-teamcraft/ffxiv-teamcraft#2131]
Inventory feature is amazing.. I can basically see what items are at  retainers, bags.. etc.. 

The only thing is missing is content of Armoire and Glamour Dresser.

Thanks

**Comment by Supamiu** [comment]
Please use the template to ask for features, it's very important that it's used to provide as much data as possible.

Also it's not possible to add glamour dresser, armoire might be possible.

Anyways, closing as not following template.
