### ISSUE TITLE
feat: Import List from Etro link

### ISSUE THREAD

**Issue by Makar8000** [ffxiv-teamcraft/ffxiv-teamcraft#2138]
**Is your feature request related to a problem? Please describe.**
Lot's of players are starting to use Etro for gearsets. Unfortunately, Ariyala does not have a "Import from Etro" feature that would allow me to create an Ariyala link which could then by used by Teamcraft to import a list.

**Describe the solution you'd like**
It would be great if the "Import list from an external website" function on the Lists page supported importing lists from Etro, just like how importing lists from Ariyala works.

**Describe alternatives you've considered**
As mentioned earlier, I've tried checking Ariyala to see if I could just convert from Etro -> Ariyala -> Teamcraft, but that is not supported by Ariyala. So, if I want to make a Teamcraft list from an Etro link, I have to either manually make it on Ariyala and then import that Ariyala link in Teamcraft, or I have to just make the list myself using Teamcraft's search functionality.

**Additional context**
N/A

**Comment by Supamiu** [comment]
I'm going to need an API from etro to be able to implement this, without such an API, nothing is possible on my side since there's nothing exposed inside the url itself.
