### ISSUE TITLE
bug: java error during install

### ISSUE THREAD

**Issue by dreamfordearest** [ffxiv-teamcraft/ffxiv-teamcraft#2148]
## I'm submitting a...
* (_) Bug report *- please add bug: before the title*

### Browser
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

## Current behavior
A series of errors has occured during the first install(not sure this errors are javascript or java, but they are at least one of them). I'm a Korean FFXIV user, therefore my FFXIV server and launcher is Korean. Error messages were various and some of them disappered pretty quick. That's why I don't have any screenshots to attach.

My teamcraft seems to be unable to catch packets. The window.debugPackets = true; command didn't show any response after my character teleported to another area. Inventory sync isn't working and so are other features using packet capture. However, it somehow reconizes my character.

Teamcraft verson: 9.4.5.

**Comment by Supamiu** [comment]
5.58 update has just been released on korea, please give us a bit of time to update the opcodes and make stuff work properly again.
