### ISSUE TITLE
bug: Some items still labeled Collectables

### ISSUE THREAD

**Issue by thebluefish** [ffxiv-teamcraft/ffxiv-teamcraft#2152]
**Describe the bug**
Some items are still marked as Collectibles despite no longer being Collectable since 6.0.

**To Reproduce**
1. Go to the page for [Ok' Vundu Mok](https://ffxivteamcraft.com/db/en/node/327)
2. Observe that  Highland Oregano, Furymint, and Clary Sage are marked Collectable
3. Hit the node in-game
4. Observe that these 3 items are no longer Collectable

**Expected behavior**  
These items to no longer be marked Collectable in TC

**Screenshots**
![image](https://user-images.githubusercontent.com/4490910/149253326-6b1d4792-334d-4a0c-80db-a3353ee35a60.png)

**Additional context**
There are more items that should be accounted for. According to one user on Discord (Nomfur Farredzasyn), this appears to affect all gathering collectables that are also used for crafting recipes.

**Comment by Supamiu** [comment]
That's a funny one, typical leftover data.

The game data shows that reducing these items gives items, meaning that they can still exist as collectables, just not obtainable as such anymore.

I'll see if I can find a different flag for it, but really not sure.
