### ISSUE TITLE
bug: Item Database details - 'Used for'  block overruns 'Comments' block

### ISSUE THREAD

**Issue by n3farious** [ffxiv-teamcraft/ffxiv-teamcraft#2162]
**Describe the bug**
When viewing items in the item database, if the Used for block has a very long "Can contain items" list, the Comments block will be rendered on top of any items past the first 12. This makes both sections very difficult to read.  

**To Reproduce**
1. Go to Search
2. Enter the name of a treasure map such as "Timeworn Archaeoskin Map"
3. Select the "i" to the right of the result to view in database
4. Scroll down on details page to see the behavior.

**Expected behavior**
The "Can contain items" list should be a scrollable block should the default height be exceeded.

**Screenshots**
![image](https://user-images.githubusercontent.com/14372366/149851888-12cdf5eb-42b1-485a-865a-fecc5ffa474d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Desktop app
 - Version 9.4.8

**Comment by Supamiu** [comment]
Hi, thanks for your report. This is due to a missing overflow handling in the Used For section, I'll fix it for the next update 🙂
