### ISSUE TITLE
feat: Sync gearsets from Lodestone

### ISSUE THREAD

**Issue by silasary** [ffxiv-teamcraft/ffxiv-teamcraft#2167]
**Is your feature request related to a problem? Please describe.**

As a primarily console player, I'd like to be able to sync gearesets, regardless of how inefficient it might be.
Teamcraft supports importing from Lodestone, but it's something I have to do manually, and requires me to delete the obsolete gearset once I do it.

**Describe the solution you'd like**
Teamcraft knows my Lodestone ID (as I'm logged in). 
I'd like it to automatically check lodestone every few hours (or at the very least, each time I open the app), and pull my current gearset as listed on lodestone.
It should then put that into a synced gearset based on the class of that gearset.

**Describe alternatives you've considered**
As mentioned above, the best solution is to pull and replace gearsets manually.

I can also move my character to an ARR zone, and log in on my PC, update all my gearsets, and then do packet-capture sync, because I own the base game on PC, but that's not accessible to most console players and is even more work than the lodestone solution.

**Additional context**
I'm aware that Lodestone doesn't update frequently, and is not an accurate realtime representation of my gear.  But so long as I log out of the game on the gearset I want to update in Teamcraft, that's not too much of an issue (and is still much better than the current situation)

**Comment by Supamiu** [comment]
Hey, while I understand your need, having a worker in a server that fetches your gear and everything is really not efficient at all, and will cost a lot in terms of resources. Sadly best you can get is how it's made atm, to avoid rate limit issues and other stuff that would affect TC if such a feature was added.

**Comment by silasary** [comment]
I was expecting it to be a Desktop App exclusive feature, and run locally on my PC.  Is that not possible under the current architecture?

**Comment by silasary** [comment]
> Also as you said it's pretty niche to PS players who also happen to have a PC. 

I said it's niche to own the game on both.  I expect most people using Teamcraft have a PC or Laptop capable of running an electron app.  (It's not like the browser version works on the Playstation or phone browsers anyway)

But okay.  Three followup question then:
1. If I put the work in to make a PR, would you accept it?
2. If not, would it be possible to (optionally?) tweak importLodestoneGearset to overwrite gearsets with the same character and class, rather than making duplicates?
3. Would it be possible to make Teamcraft prefill my lodestone ID in the Lodestone Import popup, rather than asking me to find my ID every time?

**Comment by Supamiu** [comment]
1. For sure, if your intention is to contribute the feature, then I'll accept it, I'm the only dev on the project which makes me make some choices on what's "worth" the time and priorities (most of the stuff is on Discord, tho).
  2. Well, it's possible 👍 
  3. Yeah, it's possible by using the `mainCharacter$` Observable from `AuthFacade` Service.
  
  If you want some help to implement stuff or understand the code, feel free to hop on the Discord server and ask your questions, I'm always here reading stuff (well, except when I'm sleeping, ofc, GMT+1 btw) and I'm always happy to help people who are willing to contribute 😄

**Comment by Supamiu** [comment]
I'm closing this for innactivity, I don't have the time to implement it by myself and if nobody's willing to spend some time to do it, I won't keep it opened.
