### ISSUE TITLE
Bug: Nodes Miscategorized in MIN/BTN Log Tracker

### ISSUE THREAD

**Issue by Lalalavicious** [ffxiv-teamcraft/ffxiv-teamcraft#2182]
**Describe the bug**
Items which appear in the Special tab in-game remain miscategorized in Miner/Botanist section of Log Tracker in 9.5.0.

**To Reproduce**
1. Go to Helpers > Log Tracker > MIN/BTN
2. Observe that many items are classified as "Ishgard Restoration" and "Skysteel Tools" when they should not be, and that ACTUAL Ishgard Restoration items, Skysteel Tool items, and all Collectables are missing entirely from the Log Tracker even though they are shown in the log in game
3. Only the categories that appear in the Special tab in-game are affected; regular Level categories are all accurate, though the game itself of course now sorts them from newest to oldest crafts, while the Log Tracker retains the old behavior where they are sorted oldest to newest (which is minor)

**Expected behavior**
I will attempt to describe what should go where using item IDs and appropriate categories. Screenshot of the layout of the in-game Special tab for reference:
![image](https://user-images.githubusercontent.com/79701552/150734479-152558b9-28de-4f25-a34b-77931c48583a.png)

Google Sheet with sections and which IDs should go under them (now completed):
https://docs.google.com/spreadsheets/d/1s3Iz4VnfxwAz7-fMTOTPGEmidx-9mvNozqV5IR4q3Lg/edit?usp=sharing

**Desktop (please complete the following information):**
Teamcraft Version 9.5.0
Windows, desktop version or Chrome

**Comment by Supamiu** [comment]
Hi, thanks for your report.

I appreciate your work on this Google Sheet but unfortunately most of the data stuff in TC is automated because maintaining everything by hand as a single dev on his free time is not something I can do 😄 

It should be properly fixed in 9.5.1
