### ISSUE TITLE
bug: node v17 build fails on windows 10

### ISSUE THREAD

**Issue by mortalapeman** [ffxiv-teamcraft/ffxiv-teamcraft#2211]
**Describe the bug**
When trying to build the project on Windows 10 I ran into several issues that were not captured in the documentation. I needed to install a python distribution and visual studio with the C++ tools as well as downgrade to node v16. I think this was all in support of building Electron with node-gyp. 

**To Reproduce**
1. Start with clean Windows 10
2. Install Visual Studio community edition 2022 with C++ desktop tools
3. Install miniconda with python 3
4. Install node v17
5. Clone repo
6. cd to repo in miniconda powershell terminal
7. Run `npm i -g yarn; yarn;` in the root of the repo

**Expected behavior**
I would expect this to work given the contributing documentation.

**Desktop (please complete the following information):**
 - OS: Windows 10[e.g. iOS, Windows]
 - Version: Latest staging branch

**Additional context**
I don't think this is really a bug with your repo, just would be good to know that up-stream dependencies break your build and that only node versions 14-16 are supported at this time.

**Comment by Supamiu** [comment]
It indeed doesn't work with node 17 yet, can you make a PR to update the contributing file please? Would be a nice little contribution 😃

**Comment by mortalapeman** [comment]
Can do, should be able to get around to it tonight or tomorrow.
