### ISSUE TITLE
Inventory Tracking and Visiting Worlds

### ISSUE THREAD

**Issue by thebigcheeseknees** [ffxiv-teamcraft/ffxiv-teamcraft#2216]
**Describe the bug**
If I visit another world to purchase items the inventory tracking doesn't record anything new I've purchased and has to be manually added. Then when I return home, it won't register anything anymore unless I completely close the app down and restart it.

**To Reproduce**
1. Have TC open and tracking your inventory
2. Go visit any world
3. Purchase something
4. Come back home
5. Notice nothing has changed and will no longer work without reboot.

**Expected behavior**
I expect it to track like any other time I've gathered or purchased things from the marketboard.

**Desktop (please complete the following information):**
 - OS: Windows
 - Desktop App
 - Version 9.5.12

**Comment by Supamiu** [comment]
Hi, thank you for your report 👍 

ANything inside the console when this happens? (Ctrl + Shift + I to open the console).
