### ISSUE TITLE
Bug: voyage tracker

### ISSUE THREAD

**Issue by Narcyy** [ffxiv-teamcraft/ffxiv-teamcraft#2244]
bug: voyage tracker not capturing information

After the 6.1 update, voyage tracker stopped working, trying to update the information on the tool is not working. When using 'Import using packet capture' the app picks up the Free Company window, however interacting with any airships or submersibles won't fill in the information on the app and sectors discovered also remain at 0.

1. Click 'Import using packet capture
2. Go to Company's Workshop
3. Open Free Company window
4. Interact wíth each airship and submersible on the voyage control panel

**Expected behavior**
Packet capture on the app detects Free Company and populates the data when interacting with each airship and submersible.

**Screenshots**
![image](https://user-images.githubusercontent.com/65540093/163693453-d923a996-0f5a-4a18-b222-453c100e5d0c.png)

**Desktop:**
 - OS: Windows 11
 - Version: v9.5.20 (But Issue has been present since the app was updated post FFXIV 6.1 patch launch. Worked as intended before)

**Comment by Supamiu** [comment]
Hi, this is a known bug that's due to the packet structure having changed, I'm going to update it eventually but it'll take a bit of time before it's done.

**Comment by Supamiu** [comment]
THis issue has been fixed, restart your app to reload the opcodes and have it working just fine.
