### ISSUE TITLE
Feat: shortcut to jump to crafting simulator from an item on a List

### ISSUE THREAD

**Issue by Ranzer1255** [ffxiv-teamcraft/ffxiv-teamcraft#2258]
**Is your feature request related to a problem? Please describe.**
when working on a new list i often don't have pre-made rotations for the items i'm currently working on. so i have to copy the name of the item and move over to the crafting simulator to make a rotation. often waiting a moment or two for the search to populate

**Describe the solution you'd like**
i would like to see an option in the context (3 dot) menu for the craft-able item to jump into a pre-populated Crafting simulator session

**Describe alternatives you've considered**
the existing solution to copy the name and paste it in works. but it would be nice lazy person button :P

**Additional context**
None applicable

**Comment by Supamiu** [comment]
Hi, you can click the item's crafting job icon to have it redirect you to the simulator for this item.

![kjsCbXgO3M](https://user-images.githubusercontent.com/11519203/168025605-bf97e76e-86f1-4f17-a6cc-ebcde415b190.gif)

**Comment by Ranzer1255** [comment]
awesome! i completely missed the fact it was a button! thanks :D
