### ISSUE TITLE
feat: CDN Connection Check

### ISSUE THREAD

**Issue by Mundanity-fc** [ffxiv-teamcraft/ffxiv-teamcraft#2262]
**Is your feature request related to a problem? Please describe.**
As a Chinese user, I always use proxy to ensure the network connection. However, the CDN of jsDelivr seems unavailable to me recently.
Every time I launch TC, node.js will show an alert window like this:
![1](https://user-images.githubusercontent.com/17294992/168981911-9978b359-91d5-49f1-836e-c81240667d4d.png)
Or like this:
![2](https://user-images.githubusercontent.com/17294992/168981971-9fd6e51f-5e12-4c9a-a198-23c71044468d.png)

And the data capture seems not work when the CDN is down. Other features work as fine as those provided on the website.
After adding jsDelivr to the proxy rules, everything works fine now.

**Describe the solution you'd like**
Maybe we can add a try-catch statement to ensure the network connection. Instead of the alarm of node.js, a specific window will pop up to make users aware of the unreachable CDN.

**Describe alternatives you've considered**
What about adding a manual connection check in settings? Users can check their network status manually in settings. Then they can use some other workaround to fix the problem.

**Additional context**
Nothing else.

**Comment by Supamiu** [comment]
This is related to https://github.com/ffxiv-teamcraft/pcap-ffxiv as it's the one getting data from jsDelivr already. I do'nt understand what you mean by "adding jsDelivr to proxy rules" as if your region is properly set to China, it should already load from jsDelivr, as the code in pxap-ffxiv shows.

**Comment by Mundanity-fc** [comment]
Yes, I noticed the conditional operator.
I know it may be a little hard to understand, I will try to explain.
Accord to the search results, the CDN of jsDelivr is unstable in Chinese Mainland. And a recent post (2022.05.17) shows the CDN of it is unavailable again now. It matches the time when I found my TC not work.
As the CDN is *not always* unusable, my router cannot determine whether to use proxy. So I add the domain 'cdn.jsdelivr.net' to my proxy rules in router, and everything works correctly now.
Here are two screenshots I took form the homepage of JsDelivr just now (With Proxy Disabled).
As you can see, some resource cannot be loaded and some can be, even if both of them came from 'cdn.jsdeliver.net'. Strange, isn't it?
![cdn1](https://user-images.githubusercontent.com/17294992/169136113-464c068f-6851-44fe-a600-e6099114cc74.png)
![cdn2](https://user-images.githubusercontent.com/17294992/169136119-fba32bf1-a2c7-46df-9fc2-d0e1b6d00182.png)

**Comment by Supamiu** [comment]
Is there a better cdn solution that can just proxy github for mainland China? Or maybe we should just try to load from jsDelivr, and if it fails, try from cdn.jsdelivr instead? I'm trying to find the solution that requires the lowest amount of technical user configuration and knowledge ^^

**Comment by Mundanity-fc** [comment]
For the time being, I think the best way is to add some alternative selections for users to choose. For example, there's a personal CDN site 'https://raw.githubusercontents.com/' (added an S at the end of githubusercontent). 

So, we can fetch the json file by this URL: 'https://raw.githubusercontents.com/karashiiro/FFXIVOpcodes/master/opcodes.json'.

---

Well, I do have a different workaround. In Chinese Mainland, these exists a Github-like website called 'Gitee.com'. It can also provide raw files for all the users. Most important, it can sync its repo with the one in Github.

Therefore, I forked the [repository](https://github.com/karashiiro/FFXIVOpcodes), and create [a new main branch](https://github.com/Mundanity-fc/FFXIVOpcodes_Fork_Sync-with-Gitee). By adding some Github Action, my repository can sync with its upstream every 90 minutes. After the fork syncing, another Github Action will also sync the one in Gitee automatically.

Now all the Chinese users can fetch the json file by this URL: 'https://gitee.com/mundanity/FFXIVOpcodes_Fork_Sync-with-Gitee/raw/fork/opcodes.json'. Other files follow the same URL.

**Comment by Supamiu** [comment]
Thanks, I'll update pcap-ffxiv with this an include it in the next update.

Closing this one for reference 😃
