### ISSUE TITLE
bug: extra scroll bars on metrics tiles

### ISSUE THREAD

**Issue by jjspace** [ffxiv-teamcraft/ffxiv-teamcraft#2264]
**Describe the bug**
Something in the latest update, `v9.6.6`, made it so all the chart metrics I have have an unnecessary vertical scrollbar. This wasn't happening before I updated.

**To Reproduce**
1. Have some pie chart metrics and just open the metric panel

**Expected behavior**
No vertical scrollbar unless it's actually needed

**Screenshots**
![2022-05-18_18-48-28](https://user-images.githubusercontent.com/8007967/169168380-0033faa2-7407-4dd0-ae02-ea96d7052655.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: desktop 9.6.6

**Additional context**
Note I use Teamcraft on a vertical monitor so the horizontal scrollbars in the screenshot above are expected (even if not desired but that's a separate issue)

**Comment by Supamiu** [comment]
Hi, thanks for your reports 👍 

Many of your issues seem related to narower screens, this one in particular is a CSS issue with the charts lib we're using (ngx-charts). A migration to echarts is being considered bu at the moment, I don't have the timespan for this at all. I'm sure an extra scrollbar isn't the end of the world in the meantime ^^
