### ISSUE TITLE
feat: Better pie chart metric support for skinny window/vertical monitor

### ISSUE THREAD

**Issue by jjspace** [ffxiv-teamcraft/ffxiv-teamcraft#2265]
**Is your feature request related to a problem? Please describe.**
I use Teamcraft on a vertical monitor and not all parts of the site look good in a narrower window. I like having the metrics dashboard up while I play but the pie charts look really bad and are nearly un-usable when there are multiple items that need to expand horizontally. It creates a very weird double scrollbar situation as shown in the Items crafted pane below.
![2022-05-18_19-00-45](https://user-images.githubusercontent.com/8007967/169171958-9983940f-c55a-4349-bbff-e7defca72bd5.png)

**Describe the solution you'd like**
Make the pie charts more responsive to wrap the list if parts below the pie chart or at _least_ in a vertical list so it can be displayed better in a narrower view. Below is a mockup I threw together of a much better layout for narrow cards
![Slice 1 (2)](https://user-images.githubusercontent.com/8007967/169172022-d2f70a6f-08a6-402e-a2e2-56fb3dfb17df.png)

**Additional context**
I dug into the code for this briefly and realize that this probably isn't going to be super easy without changing the chart library you use. The [NGX carts pie chart](https://swimlane.gitbook.io/ngx-charts/examples/pie-charts/advanced-pie-chart) doesn't seem to have options for a vertical layout and I'm not familiar enough with angular to know how easy it would be to alter the rendering behavior of the component outside the library itself.

**Comment by Supamiu** [comment]
As stated in #2264 , yeah this won't be done without switching to a different charts library, because while charts are easy to mockup in an image, they're the most annoying thing in the entire HTML5 ecosystem by far 😄 .

I'm considering a switch to echarts for more flexibility but yeah, as said in the issue linked, I don't have the time for this and the impact is pretty small for the average user.

**Comment by Supamiu** [comment]
Should be better now that charts have been refactored in #2376
