### ISSUE TITLE
feat: non-retainer material price sheet

### ISSUE THREAD

**Issue by WuphonsReach** [ffxiv-teamcraft/ffxiv-teamcraft#2293]
*please prefix the issue with "feat:", example: "feat: commission board system"*

**Is your feature request related to a problem? Please describe.**

The retainer venture feature lets us see which material is best to send out retainers for.  But not all fish (or materials) can be harvested by retainers.  So there is no easy way to see which non-retainer materials have the best selling price.

**Describe the solution you'd like**

1. Specify Expansion (ARR, HW, etc.) or level range bands.
2. Choose hunting/fishing/botany/mining.
3. See prices for all materials of that type / level range.
4. Mark materials which can't be gathered by retainers (or allow filtering?).

**Describe alternatives you've considered**

Maintaining a list of Universalis bookmarks for all the mats in a tier/expansion which can't be obtained via retainer.

**Additional context**

Limiting the search to level range / expansion would make the list smaller.  If I'm going fishing, I'm probably only interested in fish from a specific expansion.

**Comment by Supamiu** [comment]
Hi, did you try using https://ffxivteamcraft.com/profits-helper instead? Or is that not fitting your use case?

My understanding of your feature makes it too specific imho, profit helper is more generic and just shows what to do right now to make some gil, I don't think such a specific feature is worth implementing considering the free time that can be allocated to the project these days.

**Comment by Supamiu** [comment]
I feel like this is quite specific, I don't get why people would want to farm these specifically if other mats, including the ones that retainers can get, are worth more in the MB. As said above, I don't think it's worth for me to implement it considering the small amount of free time I have for the next two months or so. But someone else could implement it if they want to, everything is Open Source and quite easy to setup afterall 😄

**Comment by WuphonsReach** [comment]
What I've found in particular is that some of the fish that can't be obtained via retainers are worth a lot more then the fish that the retainers can obtain.  I think there are similar materials under the other categories.
