### ISSUE TITLE
feat: Add support for new EU chaos worlds

### ISSUE THREAD

**Issue by xire28** [ffxiv-teamcraft/ffxiv-teamcraft#2295]
**Is your feature request related to a problem? Please describe.**
New Sagittarius and Shadow servers (EU Chaos) are not available in the characters information lists.

**Describe the solution you'd like**
Add support for those new servers

**Describe alternatives you've considered**
Data doesn't load when using the Lodestone ID directly

**Additional context**

![Capture12313123](https://user-images.githubusercontent.com/6560562/179359075-98dd13cf-f285-4c35-8e91-d31ac00ab14b.PNG)

![Capture2555](https://user-images.githubusercontent.com/6560562/179359048-b5cf6d07-c9ee-495a-8e84-bce1a6ba588b.PNG)

Thanks a lot for this wonderful tool !

**Comment by Supamiu** [comment]
Should be fixed after a reboot of the app/F5 on browser 😄
