### ISSUE TITLE
feat: filter alts in inventory optimizer

### ISSUE THREAD

**Issue by Taluu** [ffxiv-teamcraft/ffxiv-teamcraft#2316]
**Is your feature request related to a problem? Please describe.**
When using the inventory optimizer, in the duplicated section, some items on the current character are proposed when in fact they are also on an alt.

**Describe the solution you'd like**
I think it should either be an option to filter out alts or even do not check alts altogether actually.

This is not a life-threatening issue though. :P

**Comment by Supamiu** [comment]
There's a setting to ignore other inventories in inventory-related features, I believe this is what you're looking for.
