### ISSUE TITLE
feat: "Items that can be crafted easily" category for the Inventory Optimizer

### ISSUE THREAD

**Issue by VilcsiTH** [ffxiv-teamcraft/ffxiv-teamcraft#2324]
**Describe the solution you'd like**
I'd like for Inventory Optimizer to show me items that I can craft only with items that are easily gatherable. Kind of like an extension to the "Items that can be gathered easily" category, it'd free up space by showing users that you can, for example, get rid of Bronze Ingots, as they are made of 2 items that are easily gatherable, Copper Ore and Tin Ore.

**Comment by Supamiu** [comment]
Hi, please use the template for feature requests, as it provides better informations about the feature that's requested.

Additionaly, this optimizer used to exist but requires too much computing which freezes the page entirely, and it has been removed.
