### ISSUE TITLE
bug: Rendering issues with NVIDIA graphics card

### ISSUE THREAD

**Issue by mrk3767** [ffxiv-teamcraft/ffxiv-teamcraft#2325]
## I'm submitting a...
* (x) Bug report *- please add bug: before the title*

## Environment
- Windows 10
- Really old CPU
- NVIDIA 2060 Super

### Browser
* Teamcraft desktop app

## Current behavior
Resizing the window, loading large lists, and plenty of other features were bugging the app out like crazy for me. When attempting to log in while viewing a list, copying a value into the password field froze the app up for a full minute.

At first, I wondered if it was an issue with the list size, but I noticed that resizing the windows or turning overlays on and off had the same issue.

## Expected behavior
Responsive UI when resizing, clicking around, and doing core operations

## Workaround
Add Teamcraft as a customized program in the NVIDIA control panel 3D settings section and disable various features. For me, I turned off all the aliasing, filtering, and GSYNC stuff. Also disable the threading and changed to max performance.

I think something is wonky with the hardware acceleration, but I'm not totally sure... Using the workaround, nearly all the major complaints I had about the app have been mitigated. Some slow load things here and there, but nothing too disruptive.

**Comment by Supamiu** [comment]
This is known and sadly, we can't do anything about it aside from forcing hardware acceleration to off, which is an issue every electron apps are facing.

Thanks for your report 😃
