### ISSUE TITLE
bug: New server undefined in Voyage Tracker

### ISSUE THREAD

**Issue by drejjmit** [ffxiv-teamcraft/ffxiv-teamcraft#2332]
**Describe the bug**
New servers are **undefined** in **Voyage Tracker**.
I have two FCs with the same name on the two new servers **Phantom** and **Sagittarius**.
Since both are placed in "**undefined**" they replace each other (since they have the same FC name in the same category)
Can we please get the new servers defined in Voyage Tracker?

**To Reproduce**
Import using packet capture on new servers

**Expected behavior**
A split category of the new servers so different FCs don't replace each other

**Screenshots**
![image](https://user-images.githubusercontent.com/15526476/190017810-c465786b-ef2c-4e3a-9b90-8fe6804f1f4f.png)

**Desktop (please complete the following information):**
 - OS: **Windows**
 - Version **v9.7.10**

**Comment by Supamiu** [comment]
Hi, thanks four your report :)

I fixed the bug and it'll be deployed in the next update. You might have to import your subs and airships once more to have it fix itself.
