### ISSUE TITLE
Bug: Island Workshop Best for Rest of Day Tool no Longer Appears in Island Workshop Tab

### ISSUE THREAD

**Issue by graytonio** [ffxiv-teamcraft/ffxiv-teamcraft#2336]
**Describe the bug**
The island workshop best for rest of day feature no longer appears in workshop tab

**To Reproduce**
1. Go to Island Sanctuary Workshop Tab

**Expected behavior**
To see the workshop helper

**Screenshots**
![image](https://user-images.githubusercontent.com/9275515/190409288-b47ef4cd-aa90-4608-830b-addd6bf63f89.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 9.7.12

**Additional context**

**Comment by Supamiu** [comment]
This is not a bug, it has been removed for the second iteration of the optimizerr and will return as weekly optimizer in the next update.

There's a channel on the discord server named "updates" that has more details than just patch notes when these details are needed, feel free to check it.

Weekly optimizer should be available quite soon, tho 👍
