### ISSUE TITLE
Feat: "Pin" button for main window

### ISSUE THREAD

**Issue by mrk3767** [ffxiv-teamcraft/ffxiv-teamcraft#2337]
**Describe the solution you'd like**
Similar to the overlays, it would be nice to have a pin button that toggles the "Always on top" option in General settings for the main window.

**Describe alternatives you've considered**
I usually hop into settings and click it on then click it back off when I'm done

**Comment by Supamiu** [comment]
Should probably be added in the tray menu

**Comment by JoelLau** [comment]
@Supamiu can i attempt to implement this feature as part of hacktoberfest?

**Comment by Supamiu** [comment]
Sure ! Feel free to AMA on Discord if you need any help.

Sorry for the delay, just came back home from Devoxx Morocco 🇲🇦

**Comment by JoelLau** [comment]
haha no worries. hope you had a fantastic time there
