### ISSUE TITLE
bug: unable to view alarms set if logged in

### ISSUE THREAD

**Issue by blarghhh** [ffxiv-teamcraft/ffxiv-teamcraft#2387]
**Describe the bug**
After adding several fishes to the alarm via the list option, going to the alarms option, the page is blank/does not load.

**To Reproduce**
1. Log into account,
2. Go to https://ffxivteamcraft.com/alarms
3. Empty page.

**Expected behavior**
when visiting https://ffxivteamcraft.com/alarms, able to see all the alarms listed on registered account.

**Screenshots**
![www](https://user-images.githubusercontent.com/6789845/197366640-6c26da26-2823-4564-b269-f73888ac4f18.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox, Desktop app
 - Version: 9.9.0

**Additional context**
I was using Firefox to add the fish alarms from the list option.

**Troubleshooting steps taken*
1. Refreshing the browser (Firefox) and desktop app - alarms page does not load.
2. Deleting site data/cookies in Firefox - alarms page does not load.
3. Log out or use private browsing - alarms page loads.
4. Pressing ctrl+f5 - alarms page does not load.
5. Leaving the page alone for 10 mins - alarms page does not load.
6. Using Microsoft Edge and logging in - alarms page does not load.
7. However, if do not log in first, have one tab of the alarms open, open another tab and log in, the first alarms tab is populated.

update:
managed to delete all my alarms, some how. but the folders still appear as an option when i click in the lists.

**Comment by Supamiu** [comment]
This is due to an issue with alarm groups that's currently being worked on.

In the meantime, I'm deleting all the groups that cause this bug, and don't use alarm groups until 9.9.1 is released 😄
