### ISSUE TITLE
feat: alternative display modes for list details

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#2400]
**Is your feature request related to a problem? Please describe.**

In some lists, larger lists or just list aggregates (#2064) once they'll exist, the display can get quite slow because it contains way too many DOM nodes (a normal-sized list is already over 4k nodes, large ones can go over 50k). This occurs while part of the data that's displayed OR computed is useless for the end user.

**Describe the solution you'd like**

For now, I thought of two alternative display modes:

 **1. Minimalist display**

![Minimalist](https://user-images.githubusercontent.com/11519203/199310557-f903b494-d271-4c53-a27c-eb4e8541d7ba.png)

This display would turn panels content into grids, with easy integration in breakdowns (npc, zone or tier). It would also filter sources display to only show the source that has been filtered by the current panel, because knowing that a given item can be gathered and looted, bought etc when you just want to gather it makes no sense.

The only issue is regarding "others" panel, I guess this wouldn't apply to it at all.

**2. Step-by-step display**

![step by step](https://user-images.githubusercontent.com/11519203/199312251-09ada1a7-7853-424a-80f7-c689050bc594.png)

This display would change the page entirely, and instead of showing items and stuff, it'd show a list of things to do, kind of like what the optimized navigation does. It would display a map with details and optimized route to do stuff.

This would need some layout configuration to be able to configure vendor vs gathering in many cases, and would have the same issue with Others panel, as well as the items for which we don't have a map linked, can probably be handled last or always shown, below the main layout.

**Additional context**

This a proposal and these two can both be implemented at the same time, along with 10.0, I guess. everything here is made to be discussed, and this issue will be linked to the discord server for users to give their ideas and comments on the topic.

**Comment by n3farious** [comment]
I would use both of these alternates. Probably not all the time, but I can definitely see the use cases in my mind.

**Comment by saltyeyes** [comment]
I would trade my firstborn for that second layout.

**Comment by jhessin** [comment]
I think the 2nd option is the best idea. It takes little to no time to switch classes for gathering or hunting or even fishing. 👍🏼

**Comment by shawnyve** [comment]
Love both ideas and could see myself using them often. Perhaps the 2nd more than the first.

**Comment by Supamiu** [comment]
What about timed nodes in second approach? Should they always be displayed? Displayed per map? I'm struggling to find a good solution.

**Comment by n3farious** [comment]
> What about timed nodes in second approach? Should they always be displayed? Displayed per map? I'm struggling to find a good solution.

Yeah, that is tricky. I think always displayed and a grey timer for next spawn or blue countdown on currently active would convey the needed info.
