### ISSUE TITLE
feat: Bring back total and itemized list on Metrics pie charts

### ISSUE THREAD

**Issue by jjspace** [ffxiv-teamcraft/ffxiv-teamcraft#2401]
I'll start by saying the new pie charts _do_ look really nice.

### Is your feature request related to a problem? Please describe.
Looking at my metrics board it's hard to see exact numbers of what I've crafted or how much gil I've earned or spent. I use the pie charts mostly because they're great at showing relative proportions between categories. However they used to also show the totals and a list of the numbers that make up the slices. Now without them it's impossible to know the difference between "3 of item A and 1 of item B" and "300 of item A and 100 of item B"

Compare the difference between a screenshot I used for an [older issue](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/issues/2265) and the same metrics layout today:
![2022-05-18_19-00-45](https://user-images.githubusercontent.com/8007967/169171958-9983940f-c55a-4349-bbff-e7defca72bd5.png)
![2022-11-03_00-29-30](https://user-images.githubusercontent.com/8007967/199647803-9eda55e2-0e51-48e5-bda8-cf13892fd765.png)

### Describe the solution you'd like
Please bring back the total number and add a list of the items and their actual numeric values. I realize they're there if I hover but I often have TC open on a second monitor and just want to glance at the values.
Also please keep responsiveness in mind. As stated before I use TC on a vertical monitor and I don't really want a repeat of https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/issues/2265

### Additional context
This is basically a direct follow up to https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/issues/2265 which included some mockups of potential solutions.
![](https://user-images.githubusercontent.com/8007967/169172022-d2f70a6f-08a6-402e-a2e2-56fb3dfb17df.png)

**Comment by Supamiu** [comment]
While I agree with your issue and I'll bring these back, implementing mockups, especially for charts, is very hard and it won't look like this at all, but I'll improve the look of it 👍

**Comment by jjspace** [comment]
> I agree with your issue and I'll bring these back

Thank you, I appreciate it :pray: 

> implementing mockups, especially for charts, is very hard and it won't look like this at all

I totally understand that. They weren't meant as a "implement this exactly" just a "this is a way I might expect it to look, for inspiration" as long as the information is there somehow I'd probably be happy.
