### ISSUE TITLE
bug: Proftis Helper update failure: module hasn't updated since DEC 14 22

### ISSUE THREAD

**Issue by LyeMohAn** [ffxiv-teamcraft/ffxiv-teamcraft#2430]
bug: Profits Helper module in unable to update

The "Profits Helper" tab is still showing old market data from 14 Dec 22, and any attempt to refresh the page does not work.

1. Go to the 'Currencies' menu
2. Click on 'Profits Helper' to access the module.
3. Let the data load, then click on the refresh circle, a blue button on the top right.
4. Data does not update to the current time frame, and shows (Last updated: Dec 14, 2022, 11:42:25 AM), the lists within do not change.

**Expected behavior**
Data should update and procure a different list of mats to gather/craft for profit using current Universalis History and data.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 19045.2364
 - Browser: Desktop App
 - Version: v.9.9.14

**Comment by Supamiu** [comment]
This is due to an issue with Universalis being too unstable to properly update the profits helper, I've restarted the updater process and hopefully it'll stay stable this time.
