### ISSUE TITLE
Bug: Destop App Gathering Items Screen Not Showing Results

### ISSUE THREAD

**Issue by jph290** [ffxiv-teamcraft/ffxiv-teamcraft#2444]
## I'm submitting a...
* (X) Bug report *- please add bug: before the title*
* (_) Feature request *- please add feat: before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## Environment
Windows 11 64-bit 22H2
### Browser
*Please state your browser and version. Go [here](https://ipchicken.com/) and copy everything after "Browser:".*

Have you disabled script-/adblockers before submitting?
### Teamcraft Link
*If the bug appeared on a list (i.e. layout issues), please put a link here.*
### Layout code
If you're reporting a layout issue, please give us the layout code
```
Paste your Export code here
```

## Current behavior
When typing in the search field, it no longer starts looking for an item that matches what you are typing.  Also, when trying the item and clicking Apply Filters with Type = Any and Use = Any no results are found.  I was able to get it to display results once by selecting Type = Mining and clicking Apply Filters, however when changing the search term and then click Apply Filters again, nothing would happen.
## Expected behavior
Search should work like version 10.0.3 and start searching immediately and without having to select a Type or Use.

Note: I had restarted the app to see if that would fix it with no luck.  I ended up reverting to version 10.0.3 and it is working without issue now.

## Steps to reproduce
1. Go to Gathering -> Gather items.
2. Type a node name (Adamantite Ore in my case) in the search field.
3. No results are found.

**Comment by Supamiu** [comment]
This is being worked on and will be fixed with tomorrow's update, thanks for reporting it ! 😃
