### ISSUE TITLE
Cannot log in to website to verify character

### ISSUE THREAD

**Issue by tikitacos** [ffxiv-teamcraft/ffxiv-teamcraft#2449]
I have the desktop app installed and I am able to log in but to verify my character I have to log in to the website.  I attempted to use google to sign in on the website, but the little pop-up window that comes up is completely blank and never loads anything.

I attempted to reset my password.  I received the reset password link, but the web page that loaded was completely blank and never loaded anything.

I've cleared the cache and cookies so IDK.  Help?

**Comment by Supamiu** [comment]
Hi, this is not the place for this kind of support, please use the Discord server instead: https://discord.gg/r6qxt6P
