### ISSUE TITLE
bug: alarms not playing any sound

### ISSUE THREAD

**Issue by Kyle-B** [ffxiv-teamcraft/ffxiv-teamcraft#2469]
**Describe the bug**
Alarms do not trigger a sound when they should.

**To Reproduce**
Create any alarm, wait for when it should go off.

**Expected behavior**
The notification sound should play.

**Desktop:**
 - OS: Windows
 - Browser: Desktop App
 - Version: 10.1.5

**Additional context**
This change went in recently to try and dedupe alarms, but it looks like the conditional is flipped from what it should be?
https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/a93d94f8f16a8a5b96988657539e727ca9d66ba3#diff-5a83ba0f35258cb1b26aa1d4cdd33d602ca642b419333cac2e4a1ce3e36a51eaR39

I'm fairly sure that line should instead read:
```
    if (Date.now() - 10000 >= this.getLastPlayed(alarm)) {
```

**Comment by Supamiu** [comment]
Hi, thanks for reporting (altho I wouldn't have understood the problem without you digging in the code, as the steps to reproduce are a bit empty 😄 ).

I think you're right regarding that condition, I'll update it accordingly for the next update.
