### ISSUE TITLE
Bug: Latest Update, Nothing But Gray Screen

### ISSUE THREAD

**Issue by yshtola22** [ffxiv-teamcraft/ffxiv-teamcraft#2476]
## I'm submitting a...
* (_) Bug report *- please add bug: before the title*

### Browser
*Please state your browser and version. Go [here](https://ipchicken.com/) and copy everything after "Browser:".*
Desktop Version, Windows 10

```
Paste your Export code here
```

## Current behavior
Nothing but a gray screen on running it.

## Expected behavior
The software to actually work.

## Steps to reproduce
1. Restart to apply update
2. Turn it on
3. Nothing but gray screen

**Comment by retep998** [comment]
Same thing just happened to me.

**Comment by Supamiu** [comment]
I'm on it, please download 10.1.6 from the releases page in about 1h.

**Comment by Supamiu** [comment]
Can confirm it's now fixed with latest update available in releases.

**Comment by Supamiu** [comment]
Nevermind, while this bug is fixed, another one sneaked in (which makes no sense considering the amount of changes I've made) and I'll work on it tomorrow, don't update for now, I disabled auto updater anyways

**Comment by Supamiu** [comment]
Yeah, but prefer just downloading latest update from releases page please (10.1.6 is back and working)

**Comment by Supamiu** [comment]
Yup, because I removed the release as soon as it was reported on Discord, since it broke TC startup entirely, I couldn't propagate a fix update as the updater wasn't even starting :/ that was the only solution.
