### ISSUE TITLE
Bug: Capture Error in v10.3.8 on CN Server

### ISSUE THREAD

**Issue by a08381** [ffxiv-teamcraft/ffxiv-teamcraft#2537]
**Describe the bug**
after update to v10.3.8, teamcraft cannot capture packet on CN server.

**To Reproduce**
1. Open Game First
2. Open Teamcraft
3. See error

**Develop Tools Print Out**
```
Error: MachinaWrapper failed to start: System.Net.Http.HttpRequestException: ��������ʱ������ ---> System.Net.WebException: �޷����ӵ�Զ�̷����� ---> System.Net.Sockets.SocketException: ����Ŀ�����������ܾ����޷����ӡ� 127.0.0.1:13346
   �� System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   �� System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   �� System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   �� System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� MachinaWrapper.PacketDispatcher.<Run>d__11.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   �� System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   �� System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   �� System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Screenshots**
![2023-03-07](https://user-images.githubusercontent.com/2505002/223329613-2b26213a-6570-47f7-8570-25aa13cf1b76.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [desktop app]
 - Version [version 10.3.8]

**Comment by Supamiu** [comment]
Hi,

I think the error message says it all. Something is preventing Teamcraft from listening to localhost:13346, which is probably from an overly aggressive antivirus or a permission issue.

Listening to localhost means we only accept data from localhost, so that's not even listening to external traffic, which is why it's safe to use.

**Comment by a08381** [comment]
alright, i have tried to reset winsock and it looks work quite ok now.

**Comment by Supamiu** [comment]
Port 13346 is used by Teamcraft to get packet data from the MachinaWrapper process, fwiw.
