### ISSUE TITLE
bug: JavaScript errors with Packet Capture

### ISSUE THREAD

**Issue by BrandonDowlin** [ffxiv-teamcraft/ffxiv-teamcraft#2539]
**Describe the bug**
When enabling packet capture via the play button in the top right corner of the application, a JS error pops up followed by a second JS error when the first one is dismissed. I hadnt any issues with packet capture a week ago but recently it stopped working and now this is happening.

**To Reproduce**
1. Hover over Packet Capture status in top right
2. Click on play button to enable
3. First Error pops up, click ok
4. Second Error pops up, click ok
5. Packet Capture doesnt work

**Expected behavior**
I expected to enable Packet Capture and be able to use the Island Workshop feature

**Screenshots**
[Packet Capture not enabled](https://i.imgur.com/t5lFoDH.png)
[First Error](https://i.imgur.com/4D1VPeJ.png)
[Second Error](https://i.imgur.com/T8Rc50b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Desktop App
 - Version 10.3.9

**Comment by Supamiu** [comment]
Packet capture is not working for now, due to some changes in the game code.

This is to be expected and there's nothing you can do until we're back to a properly working capture system.

**Comment by BrandonDowlin** [comment]
Understood, thanks for the super fast reply!
