### ISSUE TITLE
Bug: Island Sanctuary Workshop page not updating on time

### ISSUE THREAD

**Issue by ItsLightningBolt** [ffxiv-teamcraft/ffxiv-teamcraft#2546]
**Describe the bug**
On the workshop page, the cycle agendas do not open according to the day of the week specified; yesterday was Thursday, yet cycle 4's agenda was not opened until Friday (today).

**To Reproduce**
1. Open IS Workshop page
2. Note the cycle agendas have not been updated for the right days.

**Expected behavior**
The workshop will provide the next day's agenda (or in cases of cycles 6 and 7, along with cycle 5's agenda) instead of posting the agenda the day it is meant to be used.

**Screenshots**
(taken today, 10/3)
![image](https://user-images.githubusercontent.com/103307235/224384651-26317eb9-5fd6-41cf-8fe8-f4456933bd4f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: OperaGX
 - Version v10.3.11

**Additional Context**
I used the Workshop page last week, and it updated correctly then.

**Comment by Supamiu** [comment]
Hi, this is due to the recent packet capture issues and the fact that two days have been missing from the schedule's history entirely.

There's nothing we can do to fix it, it'll just be back to normal on next weekly reset.
