### ISSUE TITLE
BUG: Teamcraft will not load on PC

### ISSUE THREAD

**Issue by Erodsel** [ffxiv-teamcraft/ffxiv-teamcraft#2552]
![Teamcraft Open But no longer in Task Manager](https://user-images.githubusercontent.com/127703081/224586280-bf4b1e1c-990e-4bf5-9f2b-7a7b0bb8b7f0.png)
BUG: Unable to launch Teamcraft in Windows 11 after a fresh install since patch 6.35.

**Describe the bug**
When I launch Teamcraft on the PC, it loads the launch window, and after a few moments just closes down completely. I performed an uninstall/reinstall with no change in behavior.

**To Reproduce**
1. Launch Teamcraft in Windows 10
2. Program loads and them shuts itself down.

**Expected behavior**
Program to launch for use.

**Screenshots**

**Desktop (please complete the following information):**
Device name	MSI
Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Device ID	8D5018BE-1811-4CF7-AAD5-1E17E6402945
Product ID	00325-96153-79930-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Windows
Edition	Windows 10 Home
Version	21H2
Installed on	‎3/‎10/‎2021
OS build	19044.2604
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by Supamiu** [comment]
Hi, are you using an antivirus? If yes, which one?

**Comment by Erodsel** [comment]
Web root SecureAnywhere CE 23.1
Version 9.0.33.35

**Comment by Supamiu** [comment]
Can you join the discord server to discuss this more easily please? https://discord.gg/r6qxt6P
