### ISSUE TITLE
"The Flagship" Fishing Spot lists inaccurate bait data

### ISSUE THREAD

**Issue by onyxavenger** [ffxiv-teamcraft/ffxiv-teamcraft#2581]
**Describe the bug**
The page for [The Flagship](https://ffxivteamcraft.com/db/en/fishing-spot/146/The-Flagship) fishing spot lists inaccurate data for the "Baitbugs" bait. The pages shows that this bait can be used at this fishing spot and 100% of the fish caught from it should be Functional Proto-hropken, when in fact this bait cannot be used at this fishing spot. I believe that the general data for this fish is correct, because the [Functional Proto-hropken](https://ffxivteamcraft.com/db/en/item/13727) page does NOT list the Baitbugs as a preferred bait.

**To Reproduce**
1. On the website, got to https://ffxivteamcraft.com/db/en/fishing-spot/146/The-Flagship and then page down to the "Fish per bait" section. Confirm that Bait Bugs shows as the first row of the bait data, and has 100% listed for the Functional Proto-hropken column.
2. To confirm the inaccuracy of the data, in FFXIV go to one of The Flagship fishing spots in Azys Lla (e.g. x:22.2, y:23.2, z:8.9) during Thunder Weather. (These are the necessary conditions for catching Functional Proto-hropken.)
3. Change to the Fisher (FSH) job by equipping a fishing rod in the main hand item slot. Apply "Baitbugs" as the bait.
4. Use the FSH "Cast" action to begin fishing at this fishing spot.
5. Wait until a fish bites or an error message appears. You will get the following message: "Nothing bites. The bait you are using may not be suited to this location."

**Expected behavior**
The Flagship fishing spot page dose not list "Baitbugs" as an a bait to be used on the "Fish per bait" section.

**Screenshots**
![image](https://user-images.githubusercontent.com/130308941/230789748-35111253-8776-4cd8-850f-f35a08f27146.png)
![image](https://user-images.githubusercontent.com/130308941/230789924-f1a8f61a-6c0f-423d-b384-751853ee6743.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser: Chrome Version 111.0.5563.147 (Official Build) (64-bit)
 - Version: Teamcraft v10.4.8

**Comment by Supamiu** [comment]
I removed this from the database, please prefer using db comments to report this kind of thing ^^

Also you can hover each % to see how many reports include this, and that 100% was on a 2/2, which shows that it was just wrong reports 😄.

**Comment by onyxavenger** [comment]
@Supamiu Thanks for taking care of this!

Where/how do I find db comments? I spent about 30 minutes trying to find an option for reporting incorrect information on the Teamcraft page, and then another 10 minutes googling to find this github. I was pretty sure wasn't correct since this wasn't dev-related, but I couldn't find any other way to contact someone for this.

**Comment by Supamiu** [comment]
I'm getting notifications for each new comment 😄
