### ISSUE TITLE
Bug: "Autofill stats using packet capture" is always active

### ISSUE THREAD

**Issue by Blade2187** [ffxiv-teamcraft/ffxiv-teamcraft#2594]
Bug: "Autofill stats using packet capture" is always active

**Describe the bug**
The "Autofill stats using packet capture" feature on the desktop client should only operate when pressing the button and staying on the popup screen. Instead, it functions all the time. This messes up the stats on your profile any time you eat food in-game.

**To Reproduce**
1. Run FFXIV
2. Run desktop client
3. Eat crafter food
4. Switch crafter jobs
5. Observe profile updating

**Expected behavior**
The stats don't capture unless you are actively trying to capture them. I.e., while staying on the popup screen. Alternately, some kind of slider switch to toggle the capture.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 10.4.9

**Additional context**
This bug has existed for probably years now, I was just too lazy to submit an issue since I assumed someone else would notice it and it would get fixed

**Comment by Supamiu** [comment]
Hi, thanks for taking the time to report this bug 😃 

Inside settings => Desktop, there's a checkbox called "Automatically update stats/levels when switching job ingame", can you make sure it is unchecked please (its default state is unchecked)?

I just tried to reproduce the bug using the steps you provided and I didn't reproduce it, leading me to think that you have this checkbox checked, making TC update your stats whenever they change ingame.

**Comment by Blade2187** [comment]
It is not checked, and in fact I question why this checkbox even exists, given that it seems to perform a function that can only be detrimental

But that's a separate issue

**Comment by Lalalavicious** [comment]
I suggest toggling the option on and then off again! There was a bug with it that Miu fixed a long while back where, for a brief period of time, it was stuck "on" even when it was showing off. After it was fixed, my suggested troubleshooting steps were toggling it even though it _looked_ like it wasn't on, and that seemed to work for everyone at the time! It's hard to reproduce in the current versions, because it requires a broken config from (as I recall?) months ago during the period when it was bugged.

**Comment by Blade2187** [comment]
Thanks, I will try that. Do you happen to remember which config file/where the setting would be stored? I can try to back up the relevant files before attempting this, to see how they change and if that can lead to a solution to resolve this without manual effort for anyone else still having the issue. The `config.json`, `Preferences`, etc. files look pretty bare.

**Comment by Supamiu** [comment]
This is stored in localstorage so it should really just need to be toggled on and then off again, it cannot be accessed as a file because the electron process doesn't require it.

**Comment by Blade2187** [comment]
Ah damn, I really should have checked what the localstorage settings data looked like before I toggled the checkbox. I would venture a guess, `true` vs. `"true"`? Would it be able to be checked for and regularized/updated on version update or something?

In any case, it seems to work correctly now. Thanks again for the help!
