### ISSUE TITLE
Bug: Layout Filters in Step by Step display

### ISSUE THREAD

**Issue by TheMerryMeatMan** [ffxiv-teamcraft/ffxiv-teamcraft#2595]
**Describe the bug**
Certain layout filters seem to be non-functional in step by step display. For example, when trying to exclude beat tribe vendors, no combination of filters will hide them from the list in this display mode. Filters function properly in full display,

**To Reproduce**
1. Go to Any List containing beast vendor items.
2. Apply filter to exclude beast tribe vendors.
3. Change to any map featuring tribe vendor items.

**Expected behavior**
Adding a NOT FROM_BEAT_TRIBE filter should remove that from the trades/vendor panels.

**Screenshots**
https://imgur.com/jyusfFB

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Desktop App
 - Version 10.4.9bout the problem here.

**Comment by Supamiu** [comment]
Hi, thank you for your report.

This issue will need some refactoring that was planned anyways, so I feel like it'll be done a bit faster than I thought 👍
