### ISSUE TITLE
bug: creating a custom alarm without weather will result in alarm not created

### ISSUE THREAD

**Issue by Jengines** [ffxiv-teamcraft/ffxiv-teamcraft#2599]
**Describe the bug**
When creating a custom alarm without specify a Weather, it will result in a console exception (and no alarm will be created, but the pop-up will say "Alarm created").

**To Reproduce**
1. Go to 'Alarms' page
2. Click on 'Add custom alarm' 
3. Fill the Name and Map fields (as required)
4. Click on 'Submit' 
5. Pop-up will said 'Alarm created', but not
6. See error in console (due to missing weather)

**Expected behavior**
If the weather is required, we need to explicitly defined this field as required.

As I think, some map will not have Weather associated, the process should allow alarm without Weather.

**Screenshots**
_No screenshot_

**Desktop (please complete the following information):**
 - OS: Windows (11)
 - Browser : 10.4.10
 - Version 10.4.10

**Additional context**
Error on debug console

```
Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at custom-alarm-popup.component.ts:140:65
    at map.js:7:37
    at i._next (OperatorSubscriber.js:13:21)
    at i.next (Subscriber.js:31:18)
    at i.Lv.next (zone-patch-rxjs.ts:89:21)
    at filter.js:6:128
    at i._next (OperatorSubscriber.js:13:21)
    at i.next (Subscriber.js:31:18)
    at i.Lv.next (zone-patch-rxjs.ts:89:21)
    at map.js:7:24
    at i._next (OperatorSubscriber.js:13:21)
    at i.next (Subscriber.js:31:18)
    at i.Lv.next (zone-patch-rxjs.ts:89:21)
    at combineLatest.js:42:40
    at i._next (OperatorSubscriber.js:13:21)
```

**Comment by Jengines** [comment]
Would like to resolve this issue as a contributor if it's possible (I probably need time and/or discuss about the resolving process before, that's why I submitted an Issue).

**Comment by Supamiu** [comment]
I would appreciate it for sure 😄.

Let me know if you need anything , it's easier to discuss things on Discord as you're working on them but feel free to ask anything !

**Comment by Jengines** [comment]
Related pull request: #2601
