### ISSUE TITLE
Bug: "Fill with Inventory" not showing Inventory

### ISSUE THREAD

**Issue by neko-js** [ffxiv-teamcraft/ffxiv-teamcraft#2614]
**Describe the bug**
The "Fill with Inventory" button does not show the *Inventory* and *FC Chest* option most of the times. It always shows the *Island Sanctuary Bag* though.

Packet capture is working and the right amount is showing in the list as well. The list also updates correctly when the autofill option is enabled.

**To Reproduce**
I do not how to reproduce this as it feels random if the option is available or not. But it is missing most of the times.

**Expected behavior**
*Inventory* option is available  for the "Fill with Inventory" button when packet capture is working.

**Screenshots**
Make sure packet capture is working:
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/40058557/e9f7584a-f329-476f-94bb-4ab9720b80fc)

Make sure items from inventory are showing correctly in the list:
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/40058557/56ebcc00-8da2-488f-b896-d207754889eb)

Despite that, "Fill with Inventory" only shows *Island Sanctuary Bag*, but not the *Inventory*.
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/40058557/4b3fb4b4-9781-4076-8a17-8c6654d66a9f)

**Desktop (please complete the following information):**
Windows 10
Desktop Client v10.5.0

**Comment by Supamiu** [comment]
Well I don't know how to reproduce that (tried my best but couldn't :/)

However, I believe resetting your inventories and teleporting to a new area should fix 😄 

If it doesn't, please join the Discord server so we can discuss this and troubleshoot it together

**Comment by neko-js** [comment]
Updating the list to the latest Teamcraft version fixes this issue.

![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/40058557/ccf7236f-3a60-4491-9b04-208569ceaffa)
