### ISSUE TITLE
feat: No vendors for Workshop's Aggregated View

### ISSUE THREAD

**Issue by Yukkun** [ffxiv-teamcraft/ffxiv-teamcraft#2622]
**Is your feature request related to a problem? Please describe.**
Currently you can't pick workshop's aggregated view to have no vendors as an option which sucks as I try to avoid using vendors at all costs. Even now with my current workshop list, it would cost me over 6M gil to do so.

**Describe the solution you'd like**
I just want similar button than the lists have where I can click "Default Layout without vendors"

**Describe alternatives you've considered**
Well the alternative solution is to go through all the lists one by one and gather the lists one by one.. Which ends up being waste of time if you have workshop list with multiple lists

**Comment by ray557913** [comment]
Also requesting this feature or directions on how to enable it if it is already in the program.  I currently am working on crafting one of each item and have the lists broken down by level grouping and want to be able to gather everything at one time without having to switch back and forth between lists

**Comment by ray557913** [comment]
> There is one way to this that I found.. When you are on the the page that has all your lists, there is this kind of icon. ![image](https://user-images.githubusercontent.com/33172909/244798126-1bfe6676-1262-40dc-a4d2-14d5feb6bb14.png) If you press on that, you can choose all the lists you want for the aggregated view and select the layout too..
> 
> The downsides of this is though, it doesn't seem to auto fill the list if you are using the desktop version, and it will freeze and lag a lot when you change amount of item or click it to be done, and the freezing and lag gets worser the bigger your list is.
> 
> Not sure why workshop doesn't work in the same way than the aggregated view does as they are essentially the same thing, with the exception of being able to categorize better with workshops

The only problem with that is when I tried it, on the desktop program, it only has the ones not in a workshop.  I would rather not have to empty all of my workshops to have that option.  and yes the lag is real on large risks.

**Comment by Supamiu** [comment]
Hi, just came back from holidays, hence the delay 😄 

So my understanding is that you'd like a way to change layout from the aggregated display mode instead of having to use the aggregate creator for that, right?

**Comment by ray557913** [comment]
Yes, my main problem is I don't want to buy from vendors, and when trying to look at gathering list half is missing cause it can be purchased.
