### ISSUE TITLE
feat: Copy Remaining Items as Text Button

### ISSUE THREAD

**Issue by Exorion1er** [ffxiv-teamcraft/ffxiv-teamcraft#2630]
**Is your feature request related to a problem? Please describe.**
In a list, I can currently use the "Copy as Text" Button to export the full list of items as text. However, as I progress through the list and complete items, it would be helpful to have an option to export only the remaining items, not the entire list.

**Describe the solution you'd like**
I would like to see a new feature that allows me to export only the remaining items from a list as text. This could be implemented as a new button, similar to the existing Copy as Text button, but filtering the rows to include only those that represent remaining items as well as only have the remaining quantities needed for unfinished rows.

**Describe alternatives you've considered**
An alternative would be to add a checkbox or option to the existing "Copy as Text" function that, when checked, would only export the remaining items.

**Additional context**
This new button would be particularly useful for users who are progressively working through a list and want to easily see and export just the items they still need to complete.
I would do it myself but have no idea how to work with Angular and TS, and don't have the time to learn it at the moment.

**Comment by Supamiu** [comment]
Hi,

You can achieve that by using the export as text button with "Hide completed rows" option active on the list, meaning that only incomplete items will show, and thus be copied by the "copy as text" button.

**Comment by Exorion1er** [comment]
Hi there,

While it does remove the completed rows, it still copies the full amount of items on non completed rows, not the remaining amount.
