### ISSUE TITLE
feat: force list overlay window to follow the layout of the actual list in the main window

### ISSUE THREAD

**Issue by CasintheTARDISin221B** [ffxiv-teamcraft/ffxiv-teamcraft#2633]
Currently, the default way Teamcraft organizes lists assumes that you will buy any material you can and only craft what you need to. I prefer to buy as little as possible and craft HQ so later steps in the process are easier. You actually have a built-in list layout that forces crafting as priority, which is awesome, but unfortunately it seems like the list overlay can _only_ display the default layout. I like using the overlay panel, as it arranges everything very intuitively right in the corner of my screen, and also directly displays the coordinates for each item, but that convenience is greatly reduced when I have to keep cross-checking what I do and don't actually need to buy.

**Describe the solution you'd like**
A way to force the overlay pane to display with the same layout as you have the list set to in the main window.

**Describe alternatives you've considered**
I guess displaying coordinates on the main window list, or having an option to, would also work? I recognize that the step-by-step view sort of does this but it also doesn't plan the most travel-efficient routes between maps and just assumes you'll teleport everywhere in whatever sequence  it gives you, and you still have to do a lot of cross-checking if you want to plan a route yourself.

**Additional context**

**Comment by Supamiu** [comment]
related to #2632
