### ISSUE TITLE
Bug: Updater Does Not Check for Disk Space

### ISSUE THREAD

**Issue by Blade2187** [ffxiv-teamcraft/ffxiv-teamcraft#2644]
Bug: Updater Does Not Check for Disk Space

**Describe the bug**
When the updater attempts to update Teamcraft, it doesn't actually check if there is enough disk space on the install drive. If there is not, it fails in any number of unexpected ways on next launch (e.g., ffmpeg can't be found). This is especially bad because updates aren't only triggered by the user, they also happen on program exit/next launch, seemingly.

**To Reproduce**
1. Let there be an update
2. Run out of disk space
3. Update
4. Observe catastrophic failure that requires uninstall (which also sometimes fails) and reinstall

**Expected behavior**
It should have an estimate of required disk space and warn/error if there is not enough, giving an opportunity to free up space before proceeding. Ideally, it should also not consume so much/clean up old files regularly.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Some recentish Teamcraft version within the past 3 months (I can't tell because I had to uninstall/reinstall it)

**Comment by Supamiu** [comment]
Hi, thanks for reporting this.

Sadly, I don't see any ways to do this natively with the electron udpater system: https://www.electron.build/auto-update.html

So what this would mean is that the update service should check download size before downloading, and make sure it can also be installed on the device. THis will require some time to implement and is low priority imo, as it's the first time we're having this reported in 6 years of existence ^^, but anyone willing to PR the change is welcome for sure !

The changes will likely need to happen in https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/staging/apps/electron/src/update/auto-updater.ts

**Comment by Blade2187** [comment]
Huh, I would have guessed the Electron autoUpdate or Electron Builder's system would have such functionality somewhere... Does it really not??? That's kind of a core functionality of an installer/updater system... at worst, I would expect it should fail, catch an error, and then revert the app back to using the previous version (which if I understood correctly is not immediately uninstalled/deleted).

I imagine Teamcraft devs have other things to do than independently develop an updater system, so this seems sadly unlikely to be addressed any time soon. Thanks as always for taking a look.

**Comment by Supamiu** [comment]
To be honest, the main issue here is that there's no "Teamcraft dev**s**", as I'm the only core dev here, then there's some contributors, quite randomly.

I agree it should be in the base electron update system but it's really bad and lacks a lot of features for what it should be 😞.

**Comment by Supamiu** [comment]
Closing this as I can't see how we could fix it at all.
