### ISSUE TITLE
Bug: Crafting Rotation Folders have " 40" appended to their names

### ISSUE THREAD

**Issue by Blade2187** [ffxiv-teamcraft/ffxiv-teamcraft#2645]
Bug: Crafting Rotation Folders have " 40" appended to their names

**Describe the bug**
As per title, crafting rotation folders, both old and newly created, have " 40" appended to their names. I'm unclear what feature this could be so I'm assuming it's a bug. Checked both desktop app and browser and the same bug is in both.

**To Reproduce**
1. Have or make a crafting rotation folder
2. Observe that it has " 40" after the name in the display
3. Try renaming it
4. Observe that the " 40" is not in the rename dialog

**Expected behavior**
That shouldn't happen

**Screenshots**
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/5685990/b5938097-e656-48f3-b8a3-d2dde8f4d460)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: Teamcraft 10.5.5

**Comment by Supamiu** [comment]
Oops, thanks for reporting this ! 👍 

This is something I added for debug purpose to show permission level on your folders and I forgot to remove it before pushing to production, will remove for next update ^^"
