### ISSUE TITLE
Winget version isn't updated.

### ISSUE THREAD

**Issue by Battler624** [ffxiv-teamcraft/ffxiv-teamcraft#2660]
Last update for the Winget version of teamcraft is 10.5.0.42245. slightly over 2 months ago.

**Comment by Supamiu** [comment]
The Winget? What are you talking about?

**Comment by Battler624** [comment]
If you use the commandline in Windows 11 you can use a command called winget that allows you install any packages in that repository

And the FFXIV-teamcraft team made a package and added it to said repo, to be used with winget, the package was last updated in may of this year.

https://github.com/microsoft/winget-pkgs/tree/master/manifests/f/FFXIVTeamcraft/FFXIVTeamcraft/10.5.0.42245

^ this is the repo and specifically the FFXIVTeamcraft installer

**Comment by Dot-Inni** [comment]
I don't believe this person is in any way connected to Teamcraft?

**Comment by Battler624** [comment]
Well, its the teamcraft app and distributed by "FFXIV Teamcraft", you'd think its an official package.

Eitherway, since you guys now know, its up to you on what to do, either take control of this package or request that it be deleted. I'd prefer the former.

**Comment by ArcaneDisgea** [comment]
The fact that Microsoft is letting *anyone*, even people who are unaffiliated with a given apps team, submit an app is a bit frustrating. Regardless if you wish to use Teamcraft you should download it from our releases page. 

I suspect @Supamiu (The owner of FFXIV-Teamcraft) is not interested in maintaining a winget release so I am going to close this issue and begin seeking out how to get this removed from the winget repo.

**Comment by AsciiWolf** [comment]
It is not frustrating, it is exactly how package maintenance worked on Linux for last 25 years or so. Forcing users to manually download and run a binary installer is the really frustrating thing that was already outdated (outside of Windows world) in 90's.

**Comment by ArcaneDisgea** [comment]
As the original issue creator mentioned, it's been out of date for a little over 2 months now. If the community wanted to maintain it I would have hoped they would actually maintain it. 

As I mentioned in the winget PR, we push updates fairly sporadically, sometimes multiple in the span of a few hours, so this will result in the package being almost always outdated unless someone is dedicating time to monitor releases.
