### ISSUE TITLE
bug: mats not appearing in crafting lists in desktop app v11

### ISSUE THREAD

**Issue by ecnunn** [ffxiv-teamcraft/ffxiv-teamcraft#2669]
**Describe the bug**
[Desktop App version 11.0.0] When creating a new list or opening an existing one, the required materials sections (pre-crafts, monster drops, timed nodes, etc.) are not displayed. Only "Items" and "Crystals" are displayed. 

**To Reproduce**
1. Create new personal list
2. Add any crafting item (e.g. Diadochos Beret of Healing)

**Expected behavior**
Expect to see both the item list and all the required mats need to make the items.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 11.0.0 (Desktop App)

**Comment by Supamiu** [comment]
Fixed by 3e706112ad95a5491f26bf65bcd179b9e912dc73, releasing 11.0.1 soon.
