### ISSUE TITLE
Bug: consumable stat filters aren't applied correctly

### ISSUE THREAD

**Issue by ErinCall** [ffxiv-teamcraft/ffxiv-teamcraft#2692]
**Describe the bug**

In the search page, filtering by any consumable stat will exclude all items (or include everything, if you check the "exclude" box).

**To Reproduce**

1. Go to https://ffxivteamcraft.com/search
2. Set "type" to "item" (or recipe)
3. Under "consumable stats," select any stat
4. Click "apply filters"

**Expected behavior**

The search returns 1 or more results.

**Additional context**

I peeked at my browser's network inspector and noticed `filters=bonuses.undefined.Max>=0,bonuses.undefined.Max<=9999` in the query params. I imagine that's relevant :)

Filtering by _gear_ stats works as expected.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox 116.0.3
 - Version: latest web

**Comment by Supamiu** [comment]
Fixed with 11.0.10
