### ISSUE TITLE
Feat: Add List Log feature

### ISSUE THREAD

**Issue by Aurora8orealis** [ffxiv-teamcraft/ffxiv-teamcraft#2708]
**Is your feature request related to a problem? Please describe.**
When making changes to a list, especially in teams, it would be nice to see a Log where u can see recent changes that were made.

**Describe the solution you'd like**
Adding a button to a List called "Log", this log is supposed to show any active changes in certain categories.
Categories will be: 
Autofill changes
Manual Changes
System Changes:

These can either be made in 2 Separate Tabs or be shown as "Tags", described by how they induced the change of the list.
This feature should also log changes of who made them if the list is shared or in a Team.
System messages are messages that are upon changes that are made by the system, usually by filling in an item that need a material in a different list, or because a list was simply reset, or marked as done.

It should also introduce filters, so a player can filter activity based on timeframe, if manual or autofill, made by a specific player, or if items were added or removed

**Describe alternatives you've considered**
None

**Additional context**
Examples:

[Manual] Player1: Added Team "Farming" to the List
[Autofill] Player1: +24/100 Hide /// 12:00:00 01/01/23
[Manual] Player2: +100/100 Water /// 4:00:00 02/01/23
[Manual] Player1: Tab "pre crafts" was reset /// 4:30:00 02/01/23
[System] Adjusting Lists accordingly to pre crafts reset.
[Manual] Player2: -30 Water: 70/100 /// 5:00:00 02/01/23

**Comment by Supamiu** [comment]
Linked to #2707 and closing it for the same reason explained there
