### ISSUE TITLE
bug: wrong items are being used as currencies

### ISSUE THREAD

**Issue by samisiddiqui** [ffxiv-teamcraft/ffxiv-teamcraft#2714]
**Describe the bug**
Certain items which are not currencies are being shown as currencies. For example, Allagan Tomestomes of Causality are showing up as Fire Shards, while Purple Crafter's Scrips are showing up as Lightning Shards

**To Reproduce**
1. Go to the item page of an item that is traded for either Allagan Tomestones of Causality or Purple Crafter's Scrips (I went to Thavnairian Flux for the Tomestones, and Immutable Solution for the Scrips).

**Expected behavior**
These items should show what they actually are traded for

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Chrome 117.0.5938.134, Teamcraft Desktop 11.0.9

**Comment by Supamiu** [comment]
Hi, this is due to a known change in SpecialShop that I forgot to apply properly to the data, it'll be fixed in next update 🙂
