### ISSUE TITLE
Feat: add time of casting-out to fishing overlay

### ISSUE THREAD

**Issue by caduceator** [ffxiv-teamcraft/ffxiv-teamcraft#2724]
**Is your feature request related to a problem? Please describe.**
Since which fish is on the line is snapshotted on cast-out, a piece of information that's very helpful and relevant to fish discovery and research is knowing what time in Eorzean Time you had cast out. However, right now there isn't an easy way to keep track of that information / find it if you hadn't already taken a note of it beforehand.

**Describe the solution you'd like**
I'd like the fishing overlay to be edited to include the time of cast-out in Eorzean Time, ideally being included in the "last report" section as well as the current cast section, but the latter would still be good if the former is difficult to implement for some reason.

**Describe alternatives you've considered**
I'm dimly aware of TC having some kind of ability to write a local .json with fishing records, and theoretically the information I'm looking for could be included there, but it wouldn't at all be the kind of quick-access solution I'm looking for.

**Additional context**
N/A

**Comment by Supamiu** [comment]
Hi, can you edit this issue to follow the template please? It's not here for nothing and helps a lot with readability.

**Comment by caduceator** [comment]
> Hi, can you edit this issue to follow the template please? It's not here for nothing and helps a lot with readability.

Sorry about that, I've edited it.
