### ISSUE TITLE
The Lone Ripper Timer is Wrong

### ISSUE THREAD

**Issue by snowfi6916** [ffxiv-teamcraft/ffxiv-teamcraft#2747]
When I added The Lone Ripper alarm, it says that the window is open right now. However, when I went to Halfstone, it is currently the Wind condition, and it needs to be Gales, so the timer is wrong.

If you go to other websites like https://ff14fish.carbuncleplushy.com/, it says that The Lone Ripper is not active right now, so this is an issue with Teamcraft specifically. As far as I can tell, this is the only fish that is having this issue. Please fix this.

I am using the desktop app on Windows 11.

![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/30598385/0eb4abae-15c2-42a2-8927-9bdc1787eef4)
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/30598385/e5aef9dc-f296-4b60-91c4-fede34912359)
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/30598385/9862baaf-c893-4438-904f-5483a72872af)

**Comment by Lalalavicious** [comment]
The condition info entered for the fish appears to match between Teamcraft and Carby, so one thing that might be handy for troubleshooting this is to double-check that your computer's time is correctly synced! Take a look at [Time.is](https://time.is/) and ensure that it indicates that your time is properly synced. Even a relatively small difference to humans can be significant for a computer. _Generally_ your time being incorrect would impact Carby as well, but there are a few reasons it might not, so it's good to take a look!

If your clock IS out of sync, simply disabling and re-enabling Windows' time sync will usually do the trick to fix it. If not, we'll look into this further and see if there's some reason it would display the alarm as active during the wrong weather!

**Comment by snowfi6916** [comment]
I am still having issues with the fish timers. The Sinker is acting up now as well.

![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/30598385/d24a048a-9fc9-4407-8593-b3cb810a930f)
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/30598385/882a45cc-9ae7-4859-b720-d50741fb15a7)

I have unsynced and synced my Windows time but it is still not correct. Please help.
