### ISSUE TITLE
I am still having issues with the fish timers. The Sinker is acting up now as well.

### ISSUE THREAD

**Issue by snowfi6916** [ffxiv-teamcraft/ffxiv-teamcraft#2748]
I am still having issues with the fish timers. The Sinker is acting up now as well.

![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/30598385/d24a048a-9fc9-4407-8593-b3cb810a930f)
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/30598385/882a45cc-9ae7-4859-b720-d50741fb15a7)

I have unsynced and synced my Windows time but it is still not correct. Please help.

_Originally posted by @snowfi6916 in https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/issues/2747#issuecomment-1879831321_

**Comment by Supamiu** [comment]
Hi, please report this kind of bug on the discord server including the time (realtime with date and timezone) at which it happened, there's nothing I can do with this kind of issue.
