### ISSUE TITLE
11.0.22 Javascript error could not locate the bindings file

### ISSUE THREAD

**Issue by Officerfriendly1** [ffxiv-teamcraft/ffxiv-teamcraft#2759]
**Describe the bug**
A clear and concise description of what the bug is. JavaScript error that prevents the program from launching, installing or uninstalling.

**To Reproduce**
1. Attempt to launch the program or installer.
2. See error attached

**Screenshots**
![Screenshot 2024-02-04 071156](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/158834438/06b3116b-95a0-4f8b-bd83-1f20675be4ef)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro version 10.0.22631
  - Version 11.0.22 of desktop app

**Additional context**
The program was functioning normally then stated there was an update. After that all attempts to utilize the program or associated installers etc... stopped working.

**Comment by NebulousByte** [comment]
Exact same error here. I deleted the %appdata%\ffxiv-teamcraft folder and reinstalled it. Same error.

**Comment by Supamiu** [comment]
Reinstall 11.0.21 from releases page, I'm on it 🙂 and I froze auto update so it won't update back to 11.0.22.

Please consider joining the discord server: https://discord.gg/r6qxt6P to get latest news asap (because it has been discussed a lot on it and it reported as known, priority bug).
