### ISSUE TITLE
bug: Unable to add items to lists from the list page.

### ISSUE THREAD

**Issue by thekdub** [ffxiv-teamcraft/ffxiv-teamcraft#2786]
**Describe the bug**
I am unable to add items to existing lists through the 'Add an Item' button on the list page.
Adding an item through the search page works, but not through the list page itself.

**To Reproduce**
1. Go to an existing list
2. Click on add an item
3. Search for an item to add, then click the check mark to add it
4. No item is added to the list

**Expected behavior**
An item should be added to the list when selected.

**Screenshots**
Before selecting the item to add
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/12961363/d8177861-bb11-49b7-b498-28f136abb152)

After selecting the item to add
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/12961363/fa0f85e2-4822-4097-8fc8-e91cfc17ebfc)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Google Chrome
 - Version 122.0.6261.131 (Official Build) (64-bit)
 - 

**Additional context**
A friend was having the same or similar issues using the desktop app.

**Comment by Supamiu** [comment]
closed by 01e26605c0b9e8788778482c8b37880ff1a2c60f
