### ISSUE TITLE
BUG: Island Sanctuary Seafarer Cowrie Count Is Wrong

### ISSUE THREAD

**Issue by snowfi6916** [ffxiv-teamcraft/ffxiv-teamcraft#2804]
The Workshop tab is showing the wrong seafarer cowrie count for rank 5 Workshops.

This is what it shows for this week for rank 5.

![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/30598385/6f13a0da-490c-42b9-9865-92b99f29b317)

But as you can see from what I've gotten from the past couple of days, the number should be higher.

![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/30598385/e5c33ec9-4b35-449d-9404-7cd549a65130)
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/30598385/7b60c1c9-e571-420f-af35-e316551e0d06)

If I set the Workshop rank to rank 4, the number it predicts suddenly goes up, which should not happen. I should be getting MORE cowries at rank 5, not less.

![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/30598385/818aebae-1ed1-47c5-a7fc-56f0bf38f396)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 11.0.38 of the desktop app

Thanks.

**Comment by snowfi6916** [comment]
Any update on this? I see that it was marked as a bug so I'm assuming it will be fixed at some point. Thanks.

**Comment by Supamiu** [comment]
Yes it will but I need to figure out why game data didn't handle this properly, because I need it to be reliable.

**Comment by snowfi6916** [comment]
> Yes it will but I need to figure out why game data didn't handle this properly, because I need it to be reliable.

Sounds good, take your time.

**Comment by Supamiu** [comment]
Turns out it was just an index issue...

Fix will be in next update !

**Comment by snowfi6916** [comment]
Awesome! Thank you so much!
