### ISSUE TITLE
feat: Ability to sort alarms in a group

### ISSUE THREAD

**Issue by AzariahAeroborn** [ffxiv-teamcraft/ffxiv-teamcraft#2831]
**Is your feature request related to a problem? Please describe.**
When you have an alarm group with large numbers of entries that come available at the same time (examples include a group of all spawns of Dark Matter Cluster, or chocobo feed materials, or to a lesser extent all scrip gatherables for a given expansion), the sort order within the alarm group doesn't stay stable as new nodes become available or unavailable.  This makes it difficult to track which nodes I've visited in the current cycle and which ones are still pending

**Describe the solution you'd like**
I'd like to be able to control the sort order, such as by time remaining in the node's active time and then by what zone / closest aetheryte for the node.  At a minimum, if no user control of sorting is feasible, the sorting should be stable and be sorted by amount of time remaining in the node and then some tie breaker so that nodes don't jump around within their time band.

**Describe alternatives you've considered**
Using a crafting list doesn't provide enough information about the nodes currently available to be feasible.

**Additional context**
This is easiest to see the problem with a group of all Dark Matter Cluster spawns between Eorzean Time 0100 and 0900.
Alarm group: https://ffxivteamcraft.com/alarm-group/gXjgRxRRdaHCWS94lTw1

**Comment by Supamiu** [comment]
I don't think we should have this configurable, instead, having a stable sort order would be better.

Time remaining is already used for sorting but for items with the same time remaining, this can become an issue indeed, gotta find a proper tie breaker (maybe just node id and item id but idk if that'd be enough, same ndoe same item seems stupid tho?)

**Comment by AzariahAeroborn** [comment]
That improved it significantly, thank you.  Seems to also result in putting HW nodes after ARR nodes that have the same expiration, which is good because the ARR nodes all have an earlier first available time due to the differences in node timers between ARR and post-ARR nodes.
