### ISSUE TITLE
Bug: not packet reading

### ISSUE THREAD

**Issue by ShiTsubasa** [ffxiv-teamcraft/ffxiv-teamcraft#2846]
Bug: Not packet reading

After Dawntrail release, I first had to swap out my subs.  I noticed that TC is not picking up on the send out data to give me return times.  I checked metrics and none of the gil I spent in travel was being recorded either.  Last worked pre-maintenance (6/25/24 21:30 approx).  

**To Reproduce**
Load and log into FFXIV
Load TeamCraft
Select Character to log in as

**Expected behavior**
Expected the Subs to update return times when accessing Timers and Submarine interface windows.
**Screenshots**

![Submarine Snip](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/158834818/7c647429-42a1-4193-89da-dfc1f037038c)
![Submarine Snip 2](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/158834818/6990141a-d407-4c54-adce-7c757705641d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome Version 126.0.6478.127 (Official Build) (64-bit)
 - Desktop App v11.2.0

**Additional context**
I sometimes get a Windows Defender exception window with a TC update, but I did not get one this time.

**Comment by Supamiu** [comment]
Hi, it's patch (and even expansion) day, packet capture is broken because opcodes have changed and possibly some structures too.

It'll be fixed later today.
