### ISSUE TITLE
bug: Step by Step Overlay doesn't detect list in main window

### ISSUE THREAD

**Issue by TheMusicMeister** [ffxiv-teamcraft/ffxiv-teamcraft#2866]
**Describe the bug**
When opening the Step-by-Step overlay via the "Open/Close step by step overlay" button in a list view, the overlay does not detect the list in the main window, instead displaying the "No list selected, please open a list in main window to have the overlay work as intended." error message.

**To Reproduce**
1. Open a list in the main TeamCraft desktop window.
2. Click on the "Open/Close step by step overlay" button.

**Expected behavior**
The step by step overlay should display the next step in the gathering process for the open list.

**Actual behavior**
The step by step overlay does not detect the open list.  "No list selected, please open a list in main window to have the overlay work as intended." error is displayed.

**Screenshots**
![TeamCraft Step by Step Overlay Bug](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/9562832/f56a5485-9a87-4502-96e1-f0af364bad0f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Desktop app
 - Version v11.2.11

**Comment by TheMusicMeister** [comment]
I also tried closing and reopening the list while the overlay was opened, received the same result - the list was still not detected.

**Comment by Supamiu** [comment]
closed by a66edb2e57979cf14c96d9c5daeb374f166ec3d9
