### ISSUE TITLE
bug: Profile page loading error due to new lodestone privacy settings.

### ISSUE THREAD

**Issue by Nortfor** [ffxiv-teamcraft/ffxiv-teamcraft#2869]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
Profile loads very slow and giving console errors, without me being able to manually edit my DoH/L levels.
Happens in both webversion and desktop version

**To Reproduce**
1. Go to Lodestone
2. Go to Privacy Settings change setting to "Switch All Settings to Private"

![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/12272647/203e7ca0-b815-446a-95c5-137ba3f056c3)
3. Save Changes
4. Try to use the profile options in Teamcraft for editing your levels
5. See error in console (see screenshots below)

**Expected behavior**
Still allowing me to edit my levels for my DoH/L after I've already verified myself, and changed the setting to all private.

**Screenshots**
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/12272647/b3d42be6-9789-4dfa-a51a-3a6d60c97078)
![image](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/assets/12272647/197ef3d0-d7b2-40d6-8a70-38ea2bcd47e1)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox, OperaGX, MSEdge
 - TC Version 11.2.11

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by Supamiu** [comment]
Teamcraft relies on your name and picture to be public, at least these info are mandatory.

If you don't want your stuff to be public, you should set just the profile to public and everything else to private.

**Comment by Nortfor** [comment]
Made the changes to my settings again.

Not sure whether it's a good idea or not to at least show an error on the profile page, for possible causes of the information not being able to be retrieved from the lodestone?

At least thanks for the clarification! (Closing the issue)
