### ISSUE TITLE
bug: adding my character & validating it doesn't save, reverts to somebody else's character

### ISSUE THREAD

**Issue by ttei080** [ffxiv-teamcraft/ffxiv-teamcraft#2872]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
I registered on teamcraft via google auth.
when I logged in it showed me somebody else's character (unvalidated).
I went to add my own character. 
I set mine as the new default, it gave me the code to validate it, which I pasted into my lodestone profile and saved.
Then I clicked the validate button and it gave me the green box okay.
But whenever i F5 or navigate to a different page it deletes my character and reverts to the other, unvalidated one.
Additionally I am unable to delete their unvalidated character.
Tried disabling adblockers and tried different browser, but it still won't save my character.

**To Reproduce**
As above, with or without attempting to delete the other character.
included a video below

**Expected behavior**
I want my character to save as the only character.

**Screenshots**
https://www.youtube.com/watch?v=43kkLE2kFmo

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows] W10
 - Browser [e.g. chrome, safari, desktop app] Firefox
 - Version [e.g. 22 or version of the desktop app] 119.0.1 x64
 - Also tried in Chrome 126.0.6478.127 (default install, disabled ublock)

**Additional context**
F12 console is spamming "[Teamcraft] o.character is undefined TypeError: o.character is undefined"

**Comment by Supamiu** [comment]
Hi, I'll need your user ID in order to fix your profile, ideally, join our Discord server so we can debug this quickly 🙂
