### ISSUE TITLE
bug: desktop shortcup created every update

### ISSUE THREAD

**Issue by vkyfox** [ffxiv-teamcraft/ffxiv-teamcraft#2875]
**Describe the bug**
It's not exactly a "bug" per se ; but despite me asking for no desktop shortcut on the initial install, I assume this preference is not stored anywhere, and every update creates a new desktop shortcut each time.

**To Reproduce**
1. Use Teamcraft normally.
2. Let the auto-update happen.
3. Say yes to the "Restart Teamcraft" prompt.
4. A new desktop shortcut is created.

**Expected behavior**
I would like to have the option for this shortcut not to be created.

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox, but not really applicable here
 - Version: It's been the case for as long as I remember, but this happened again from the previous version to 11.2.13

**Smartphone:**
 - Probably not applicable.

Unrelated, but thank you again for the wonderful software :pray:

**Comment by Supamiu** [comment]
Hey ! 

There's a setting for that actually 😄 

Under Settings > Desktop:
![image](https://github.com/user-attachments/assets/f9a03624-7b7e-46b9-80ed-0e943229882f)

**Comment by vkyfox** [comment]
My apologies ! 🙏 I was sure I had checked all the options for that, but I must have missed that one ! Sorry for bothering you and keep up the amazing work !
