### ISSUE TITLE
bug: retainer ventures fail to load

### ISSUE THREAD

**Issue by MasterChiefToby** [ffxiv-teamcraft/ffxiv-teamcraft#2887]
Description
The Retainer Ventures Tool (https://ffxivteamcraft.com/retainer-ventures) does not produce results since a couple of days ago.
Looks like a timeout & internal server error of the universalis api.

1. Go to https://ffxivteamcraft.com/retainer-ventures or Teamcraft App Retainer ventures
2. Fill in Retainer Attributes
3. Click Search
4. See loading circle
5. Nothing happens on the page or app afterwards
6. See errors in console (Screenshot 2 from chrome console & attached log files)

Screenshots
![image](https://github.com/user-attachments/assets/8e6d7792-66b9-446b-a691-a715be9515bf)

Device & Browser information
 - OS: Windows 11 23H2 Build 22631.3880
 - Browser: Teamcraft App, Chrome (Versions 126.0.6478.128) & Edge (Version 126.0.2592.113)
 - Versions: 11.3.4

**Additional context**
Logs from Chrome Console
![image](https://github.com/user-attachments/assets/13e2c97e-51b9-407c-8e8a-d3ba11e2bac4)
[ffxivteamcraft.com-1721401589119.log](https://github.com/user-attachments/files/16313742/ffxivteamcraft.com-1721401589119.log)
[ffxivteamcraft.com-1721401586240.log](https://github.com/user-attachments/files/16313743/ffxivteamcraft.com-1721401586240.log)
[ffxivteamcraft.com-1721401582558.log](https://github.com/user-attachments/files/16313744/ffxivteamcraft.com-1721401582558.log)
[ffxivteamcraft.com-1721401566896.log](https://github.com/user-attachments/files/16313745/ffxivteamcraft.com-1721401566896.log)
Also got a HAR file, but cant upload it here.

**Comment by Supamiu** [comment]
Universalis API being down these days means that this page is unstable, not much we can do about it, sorry.

**Comment by MasterChiefToby** [comment]
Thanks for the quick response and clarification.
I will close the issue, as it's on Universalis' site indeed nothing Teamcraft can do about it.
