### ISSUE TITLE
Install error - av_buffer_create

### ISSUE THREAD

**Issue by eXpensia** [ffxiv-teamcraft/ffxiv-teamcraft#2888]
Hello ! While trying to install team craft I got an error "The procedure entry point av_buffer_create could not be located in the dynamic link library"

**To Reproduce**
1. Trying to install Teamcraft

**Screenshots**
![error_tC](https://github.com/user-attachments/assets/8b2282b9-19d6-4f77-9675-1d261d50a692)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Supamiu** [comment]
Without more details, this looks like a windows library being missing for the setup, I don't know what else to say ^^"
