### ISSUE TITLE
bug: Fill Prices buttons on List page Pricing Mode do not work

### ISSUE THREAD

**Issue by TheMusicMeister** [ffxiv-teamcraft/ffxiv-teamcraft#2893]
*please start the issue name with "bug: ", example: "bug: cannot register on ios"*

**Describe the bug**
When viewing the Pricing Mode page for a crafting list, clicking on any of the "Fill prices based on marketboard prices" buttons does not properly fill all of the sub-items in a category.  It seems to be an API request error coming back from Universalis.

**To Reproduce**
1. Go to a crafting list.
2. Click on the Pricing Mode button at the top right.
3. Click on the "Fill prices based on marketboard prices" button on any category, or the similar button at the top of the Spending section.

**Expected behavior**
A price should be retrieved and displayed for each item in the category.

**Screenshots**
![image](https://github.com/user-attachments/assets/82ecd317-bcf4-415d-a9a7-060dbe37dfcb)

![image](https://github.com/user-attachments/assets/4cca24e3-d985-4eb8-ac7c-561605d25f5a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v11.3.5

**Additional context**
There is no Preview or Response content on the network requests in the console.  One of the request does come back with error status 429 (Too Many Requests)

**Comment by Supamiu** [comment]
Universalis is currently having issues which causes this kind of problem, there's nothing we can do aside from waiting for these issues to be fixed on their end.
