### ISSUE TITLE
Some market prices not loading in Desktop App

### ISSUE THREAD

**Issue by Underoath50** [ffxiv-teamcraft/ffxiv-teamcraft#2895]
bug: cannot load market prices in pricing mode on list

**Describe the bug**
When I click pricing mode on a list then select Fill prices based on marketboard prices (your server only) only a few load, if any. If I run it again sometimes the ones that did load are removed and others will show up.

**To Reproduce**
1. Go to List
2. Click on Pricing Mode
3. Scroll down to Fill prices based on marketboard prices (your server only) and click
4. Only some items load prices.
5. Clicking again only some load and sometimes those that previously loaded data is removed.

**Expected behavior**
I expect all items to load marketboard prices from my server

**Screenshots**
![Pricing error](https://github.com/user-attachments/assets/068d4bb7-4b00-4e5f-a695-5824b2c0a7c5)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Desktop app
 - Version 11.3.6

**Smartphone (please complete the following information):**
n/a

**Additional context**
Worked before Dawntrail update. I am logged in and my server is listed in my profile.

**Comment by Supamiu** [comment]
Universalis is having some issues, there's nothing we can do about it but that's what's causing this.

**Comment by Underoath50** [comment]
Ok thank you, I really appreciate you taking time to respond.
