### ISSUE TITLE
bug: Attempting to access properties of undefined in i18n pipe

### ISSUE THREAD

**Issue by Aviian314** [ffxiv-teamcraft/ffxiv-teamcraft#2903]
**Describe the bug**
When accessing lists, the developer console shows a ton of errors about attempting to access properties of undefiend

**To Reproduce**
Can't determine an exact sequence to break. Once it happens, it occurs a lot.

**Expected behavior**
No errors

**Screenshots**
![image](https://github.com/user-attachments/assets/ed2ce6a4-1aaf-405a-a58d-d918c80741fc)

**Additional context**
An optional chaining operator can be used before accessing ".replace" in the `i18n.pipe.ts` file to handle the possibility of undefined.
line 127 fix: `this.currentValue = next?.replace(/&nbsp;/g, ' ');`

**Comment by Aviian314** [comment]
While difficult to reproduce, a code review shows the possibility of this occurring.
![image](https://github.com/user-attachments/assets/1cf87665-dcf7-471c-9d26-6c1ceba43104)
`setCurrentValue` takes a string or undefined as the input parameter `val` and uses it to to set the variable `next`. If `val` is undefined, then `next` will also be undefined resulting in the above error when it tries to perform `next.replace`.

The method `setCurrentValue` is called from the observable subscription at the top of the file. This observable pipes values through some code that does indeed have a fallout condition of sending a `null` to the `setCurrentValue` method.
![image](https://github.com/user-attachments/assets/60ce54fe-6d81-4561-b208-7fb08e8460d1)

---

Motivation: I have a different issue occurring where list items show their background as blue as if i can craft them when i don't actually own the crafting materials. It seems to occur when I'm also getting the above error. Given javascript's propensity of doing weird things when errors are not caught, it seemed like a good first step to handle this error first. I haven't been able to get a local dev copy of the application working on my box to test this.

**Comment by Supamiu** [comment]
I'm not a big fan of fixing the final part that breaks instead of finding the root cause but in this case, the fact that val can be null should indeed be handled.

Did you check our [contributing](https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/blob/staging/CONTRIBUTING.md) guide file to start the local dev copy?

**Comment by Aviian314** [comment]
I did. I was struggling with various install issues. I didn't have a lot of time the day that I was attempting to do so. I'll give it another shot soon and reach out in discord for further assistance.
