### ISSUE TITLE
feat: updated fishing hole and fish

### ISSUE THREAD

**Issue by JoeRad** [ffxiv-teamcraft/ffxiv-teamcraft#2908]
# Fishing Spot Page Requests
- update the fishing hole page bait matrix to be filterable by catch data that used Modest and Ambitious Lure. It should have a filter that allows users to pick from 0, 1, 2, or 3 stacks of Modest OR Ambitious Lure, then filter the data and %'s based on the selection. (So the matrix will display bite rate data w/ 3 Modest Lure stacks, if that was chosen).

# Fish Page Request
- Create a new section on the fish page similar to the Hookset and tugs section that shows bite rate with 1-3 stacks of Modest or Ambitious Lure (similar to how it says "tugs" on this new section it could be the % on 1-3 stacks of M/ALure instead).
![image](https://github.com/user-attachments/assets/5dbb2602-454c-4abe-aed1-e348a34e727a)

into something like this> 
![image](https://github.com/user-attachments/assets/614d948d-4d22-4cda-973b-e0356617d8e6)

**Comment by Lalalavicious** [comment]
Similarly, the **Allagan Reports** interface should receive a new field that could be called
### Lure required:
With the options **{None,Modest,Ambitious}**
When you select one of the latter two, you can input/select:
### Minimum stacks required:
With the options {1,2,3}
