### ISSUE TITLE
Farming tracker double inventory after sorting in game.

### ISSUE THREAD

**Issue by ShiTsubasa** [ffxiv-teamcraft/ffxiv-teamcraft#2954]
bug: Farming window not tracking properly after sorting inventory

**Describe the bug**
Upon using Auto-sort in the inventory, the next acquisition doubles what you had previously and then adds the new item to the stack in the tracker.

**To Reproduce**
1. Farm an item (e.g. Stardust Shrimp in the case that was noticed)
2. Sort inventory (at 7 Stardust Shrimp in inventory and TC)
3. Farm another of the same item.
4. TC shows I have 15 in inventory when I only have 8 in game. (1 container, 15)

**Expected behavior**
Just an accurate accounting of the number of items farmed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Desktop App
 - Version: 11.3.18

**Additional context**
Noticed it earlier than the current farm, but wasn't sure how to reproduce the issue.  

Not sure if this was noticed and mentioned in the Discord.

**Comment by Supamiu** [comment]
Should now be fixed, can you confirm and eventually close if that's the case?

**Comment by ShiTsubasa** [comment]
Tested across multiple gathering styles.  Issue is fixed.
