### ISSUE TITLE
feat: link items to leves for exp informations

### ISSUE THREAD

**Issue by RobertCGouge** [ffxiv-teamcraft/ffxiv-teamcraft#408]
## What feature are you proposing

As a Teamcraft user I should be able to see if an item I am looking at can be used for a levequest.  This should be denoted by an icon to the right of the class icon when looking at an item.

## What is the use case for this feature?

This is a useful feature as it would inform me that I can craft extra items for XP.

**Comment by Supamiu** [comment]
This will need a bit more work as it needs some changes on garlandtools too, won't be in 4.2, sorry.

**Comment by Supamiu** [comment]
Fixed by 5.4.0 update with the new database system.
