### ISSUE TITLE
feat: add pop-out timers on list, or ability to import from list.

### ISSUE THREAD

**Issue by alexeiryn** [ffxiv-teamcraft/ffxiv-teamcraft#465]
## What feature are you proposing
Add the ability to use the extremely useful pop-out lists feature from Alarms either within a list (showing just that list's items) or add the ability to create a category from an already-existing list.
## What is the use case for this feature?
Ease of farming timed items while zoned out/semi-afk/alt-tabbed when crafting a particular list (or commission from the board)

**Comment by Supamiu** [comment]
If I understand the idea, you'd like to have a way to open a timers overlay with just the timers from a given list?

**Comment by alexeiryn** [comment]
Correct.

**Comment by Supamiu** [comment]
I don't see a proper way to do this for 4.4, it'll be delayed until I find a proper implementation.

**Comment by Supamiu** [comment]
![image](https://user-images.githubusercontent.com/11519203/43128256-caa2cd06-8f31-11e8-8a16-5aa31731f293.png)

I found a proper implementation, will be in 4.4
