### ISSUE TITLE
feat: gearset planner

### ISSUE THREAD

**Issue by ayyaruq** [ffxiv-teamcraft/ffxiv-teamcraft#485]
_This is a large feature request so extremely open to commentary, the checklist is more for general aims rather than implementation details._

### Gearset Planner

The goal is to create a gearset planner for DoH and DoL, similar to Ariyala but more for specific crafting and gathering needs in terms of materia handling and upgrading gear without compromising stats. In my mind, the planner has two modes of operation - a simple gearset viewer with materia that you can swap pieces or materia out inside an item level boundary, and an upgrade path planner where you structure two sets with materia and the tool will select which pieces and melds to do in what order to avoid dropping your stats part-way and breaking macros, as well as minimising early overmelds.

### Simple Gearsets

- [x] ~~load gearset from xivdb~~ *rip*
- [x] import from ariyala
- [x] customise gearset and save to a job for use in planner or rotation simulator
- [x] share/save/export/tag a gearset
- [x] item level selector for limiting gear show
- [x] for each slot, an expander to see other options
- [x] for each slot, minimised and expanded, materia selectors

The simple gearset planner should be able to read a gearset and allow the user to fiddle with items and materia, the same way Ariyala works. This is pretty basic but sets should also be able to share and tag, for example "cheap 3-star crafter set", as well as auto-tagging based on stats for things like "all overmelds IV or less", or "70 3-star with food". Users should be able to remove tags they don't want.

### Upgrading Gearsets

- [x] ~~load a saved gearset or import from xivdb~~ *rip*
- [ ] prioritise basic melds or overmelds depending on preference
- [ ] set target stats with presets such as "70 3-star"
- [ ] colour code items that force stats out of desired bounds (this might be derpy because of materia)

The gearset upgrade planner is a bit more complex than the simple viewer. I picture it as a side by side list of two gearsets, with an identifier next to the upgraded piece showing the order to upgrade. I'm not sure the best way to implement materia here, since you might do confirmed slots first and then look into overmelds, or all at once. Users could set a preference I suppose. There should be some minimal optimisation, maybe via colouring items the way we do in the simulator, so users know if their stats will drop below current or not hit their goal threshold.

### Optimisation

The most important part of this is optimisation. I'd like to see not just a gear item optimiser, but also materia and possibly food. Instead of being a dumb "try everything and see what's highest", I think a simple rules engine is best. If rules end up conflicting, inform the user on which bound or bounds could have caused it. This is obviously complicated, and the feature would be useful even with just the planner.

As a rules engine, I would want to have rules such as `max CP; crafts at least 3-star; max control; max overmeld IV; max final slot II`. Setting priority for non-cap melds such as `control > craftsmanship` would be good too. The optimiser should aim to maximise stats within materia costs for the user and prioritise stats in order of importance. Being able to migrate melds for an existing set would also help since a lot of players need to re-meld when new combat gear comes out with a higher star rating.

- [ ] set stat priorities
- [ ] set stat base rules, such as "max CP" or "crafts over 1500"
- [ ] presets for some rules, such as star ratings or HQ breakpoints for gathering
- [ ] materia base rules, such as "highest overmeld grade"
- [ ] materia slot rules, such as "no final slot V"
- [ ] compare to simulator? something like "can complete this rotation, but all NQ"

That last point is a bit over the top maybe, but it's a thought. Any thoughts or comments are appreciated so we can turn this into a real feature for everyone.

**Comment by Supamiu** [comment]
I think one of the first features users will require for that is the ability to import gearsets from aryiala, this would be done by either doing a plain text query on the page and loading the html to parse it and get gear pieces, or by requesting a json response format from aryiala (I don't know if it's a thing yet but it might be worth asking the dev behind it).

For tha last point, I feel like it's a really nice thing for newbies and people asking for melds, they could just say "only use V materias max" for instance, and require the melding to be able to craft a given item with a given rotation. Because rules like "be able to craft 3star items" are too inaccurate as they depend on the rotation used and only that.

Because the Simulator is independant from the rest, a simulation can be run using the gear without the display, which is a good point for that.

**Comment by ayyaruq** [comment]
For importing from Ariyala, `http://ffxiv.ariyala.com/store.app?identifier=<code>` is a JSON dump of the gearset plus filters, materia, and selected items. Might get a bit weird for sets that have multiple items but only one selected.

Definitely that's a simple rule, but I think if we have a proper rules editor (modal with dropdowns idk) that could fit in there fine. I read "be able to craft 3star items" as having the minimum required stats, rather than a rotation. More named badly than a bad filter though. Maybe be able to apply a gearset to a simulation and see if success or not.

**Comment by MDlumia** [comment]
just posting a tidbit from discord for refrence. 
is something that shows you have X melds on Y item.  How many melds and what ones might you need to Meet or exceed Y's Melds on (new) Z's item for a successful upgrade
use for that is knowing how many melds or over melds it takes before changeing to a new set with out losing to many if any stats that might break a rotation or craft
Killa Kagon (Siren) - Today at 8:52 AM
That sounds pretty nifty
a real "Is it time to upgrade or just meld"
Miu - Today at 8:53 AM
So an extimate of how many materias you'll need?
M'Marrie Lumia (Mateus) - Today at 8:53 AM
yes
and what ones
Miu - Today at 8:53 AM
can be done for sure :smiley: in the upgrade optimizer system

**Comment by ArcaneDisgea** [comment]
Totaling materia quantities at the bottom of the list would be great as well as having mouse over on the materia icons perhaps an alt attribute that says what the materia is so we don't have to make extra clicks to view what materia goes into what slot.
