### ISSUE TITLE
feat: API Access

### ISSUE THREAD

**Issue by cking** [ffxiv-teamcraft/ffxiv-teamcraft#532]
**Is your feature request related to a problem? Please describe.**
Not applicabale

**Describe the solution you'd like**
It would be awesome to have API Access in some way or kind.
The end points i would love to see would be:
- Get Comissionboard overview (Search with no params?)
- Search comission board for stuff
- Display a comission in detail

- Display $characterById lists (display hidden/private lists if authed in some way)
- Display list details and progress if read permissions is available
- Invitelink to ppl to join a list? Similar to how the share link works probably

There is no need to add the regular item metadata or recipe or anything, item IDs would be enough, there are more then enough services to crawl that data from.

**Describe alternatives you've considered**
Website crawling. But I'd prefer an official solution over something hacky

**Comment by cking** [comment]
also the new teams endpoint would be interesting to add. either as read only or r/w

**Comment by Supamiu** [comment]
This won't happen, because it is way too much time for it to happen, time that I don't have. And exposing an API from firestore isn't easy at all. Also raises concerns about rate limitations to avoid spam, IAM, etc.
