### ISSUE TITLE
feat:Ablity to add items to a list using number of crafts

### ISSUE THREAD

**Issue by MDlumia** [ffxiv-teamcraft/ffxiv-teamcraft#544]
*please prefix the issue with "feat:", example: "feat: commission board system"*

**Is your feature request related to a problem? Please describe.**
the Problem is for items like Cordials which make 3 per craft.  i find it annoying that i have to figure out how many items are x number crafts
**Describe the solution you'd like**
I would like the ablity to check a box or something and enter on the item search screen a number of "crafts" wanted  instead of just number of actual items made.  
**Describe alternatives you've considered**
taking the time to do the math and possibly mess up on it. but that does't flow as well and wont work if ones in a rush 
**Additional context**
![image](https://user-images.githubusercontent.com/7461284/43688644-4595865a-98b2-11e8-8e17-68a6351d1c0a.png)
example of the a screen where this could be handy

**Comment by AcidAshe** [comment]
I think this is actually a very good idea!
