### ISSUE TITLE
feat: Sort Lists/Item Search

### ISSUE THREAD

**Issue by Hranz** [ffxiv-teamcraft/ffxiv-teamcraft#685]
Related to feat: rearrange lists order #100 in a way.

I find it frustrating to only see lists in one order, or to search for items in one order. If I'm searching for BTN gear to help a friend power level, I get a mix of other gear too (like the All class gear). 

I would like to be able to sort a searched list, by name, level, crafter, etc. Or perhaps filter out items that have say, piety. I have also considered adding a filter for gear that contains a particular stat such as gathering, or control.

**Comment by Supamiu** [comment]
Hey, thanks for the feature request 👍 

Are you talking about the search feature inside /lists page or inside the /search page?

**Comment by Hranz** [comment]
My apologies. I never really know how to summarize my thoughts for a title.

I know when you look through a list/community list that's been assembled, and you're checking off the materials that have been obtained, one can sort the order of those mats or by crafter/gatherer. I'm talking about sorting lists on searches on /search, /list, /rotations, /community-lists, etc.. So that I can change the order of the results.

Continuing my example of Botanist gear using /search. Off hand, I don't know what levels a Botanist can get new gear, but I know I want to search a range of 44-52. My friend is at level 49 and should replace some gear, but has long out lived the level 29 accessories from the vendor. I want to be able to order by level in a descending order in this case. Later I might want to change the order to ascending, because I've changed the range from 50-55, as my friend levels up.

As for /lists, /community-lists, often times my keyword searches just don't cut it, because they are either too vague or the list names have some issue (misspelled, doesn't contain the keyword I want, etc.). I would select the tag I want and perhaps order by list name, most copied, maybe even order by number of tags (probably better in the last case to have a filter for "only contains tag" and "includes tag"). Some lists include far more than I might want to craft at a given time (ex/ all 4.3 crafter/gatherer gear vs 4.3 crafter MH). 

Please let me know if my examples need more detail or better wording, or if I need to be more specific.
