### ISSUE TITLE
feat: gathering simulator

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#778]
**Describe the solution you'd like**

As we have a crafting rotations simulator, it would be nice to have a gathering rotations simulator too, in order to be able to theorycraft rotations for optimal collectibility and reliability, and share them to other players like we do with the crafting rotations

**Comment by Supamiu** [comment]
Some nice data from S'yahn: https://www.reddit.com/r/ffxiv/comments/3r52tm/looking_for_data_on_gathering_breakpoints_data/

**Comment by MDlumia** [comment]
i would love to see this personaly  my self to be honest.

**Comment by Supamiu** [comment]
We are really too far from having enough data to make this possible sadly. I'll report it until we have enough data for that.
