### ISSUE TITLE
bug: upload too high on some actions

### ISSUE THREAD

**Issue by Val870** [ffxiv-teamcraft/ffxiv-teamcraft#807]
**Bug description**
I have an ADSL internet connection, that means (for me) 3.9 Mbit/s download and **829 kbit/s upload**. 
If I copy a public list on my account, Teamcraft consume up to **150 kbit/s**.
If a delete some items on a list on my account, Teamcraft consume up to **550 kbit/s**. 
Same thing if I am on the list and validating some stuff, looking where are the items, etc.
And finally, even after deleting the list, the upload consumed stays high for a time.

With these consumptions peaks, I cannot play FFXIV at the same time.

**Steps to reproduce the behavior:**
1. Go to Public lists
2. Search for "51-55 Goldsmith's log" (with tags, it's faster :))
3. Copy the list to the account
4. **Upload climbs up**
5. Go on My Lists
6. Delete some items of the newly copied list
7. **Upload climbs up**
8. Go into the list
9. Interact with the list and the items (set some items as done, check market boards, etc)
10. **Upload climbs up**
11. Return and the List page
12. Delete the list
13. **Upload stays high for a time**

**Expected behavior**
The same list as before but without points 4, 7, 10 and 13 ^^

**Environment details:**
 - OS: Windows 10
 - Desktop app
 - Version 5.0.38

**Comment by Supamiu** [comment]
Hello,

I'm really sorry about this issue and as you saw, it's tagged as very hard.

I can't be 100% sure this will be solved as it'll be hard to find how. In the mean time, you might want to try to use something to limit network usage of the desktop app: https://www.howtogeek.com/347711/how-to-limit-any-applications-bandwidth-on-windows/

**Comment by Val870** [comment]
I guess so ^^ 

Thanks for the link !

**Comment by ayyaruq** [comment]
I had a look into this and as far as I can tell, other than Chrome specifically having an option to throttle uploads, this isn't doable on the browser side. Normally a browser relies on the OS, and somewhat the upstream router QoS, to decide what traffic to prioritise and throttle. If your system is doing this inefficiently, there's no real way for the browser (that I can find) to throttle it. The desktop app is a browser wrapper so no real difference here as Electron itself doesn't seem to expose anything for it.

Now, realistically, the game requires about 30KB/s peak which is 240kbit/s (when you zone, typically it's below 10). Even with TC smashing 550, that should still fit perfectly well unless you have other upload going on. You can implement QoS on your router for the FFXIV servers though, or follow Miu's advice above, but ultimately there's not much that can be done for this. I have slightly worse net than you it seems but I've had no issues, what behaviour are you seeing in the game that makes it unplayable with TC running?

In terms of TC, the upload you see is document sync for the list. Changes are effectively the full data set for a list, so it needs to push the whole thing which can be a few MB. The upload you see after the fact is background synching. We're trying to minimise this (helps especially with mobile users) but this is the way the database works so other than shrinking upload size, the speed of the upload can't really be handled on our side.

**Comment by Val870** [comment]
At peaks of upload consumption, lags appear in the game. For instance, when you try to interact with bells, stables, NPCs, etc I had 1s latency before the interaction replied. And alos, with this latency, I cannot use crafting macros (or else I'd have to put `<wait.5>` on every line ^^' 
And furthermore, we are two people playing FFXIV on the same connection. So - for now - it's forbidden for either one of us to have TC running. 

> it needs to push the whole thing which can be a few MB 

I did not looked into the queries size but do you have gzip activated for upload and download ?

**Comment by ayyaruq** [comment]
Upload and download are limited by the database library we use. I couldn't even find a setting for it, and can't tell if the DB even works for it unfortunately. The issue feels a bit weird here still tho, you may want to fiddle with QoS on your router to prioritise the game because I can't see anything we can do on the TC side to remediate this. I use `wait.4-5` in my macros anyway but I can understand why people wouldn't want to do that.

**Comment by Supamiu** [comment]
Closed by #1115

This will be in 6.0.0

**Comment by Val870** [comment]
I'll try to check when it'll be out ^^
