### ISSUE TITLE
feat: simulation result in modal on list view

### ISSUE THREAD

**Issue by TiteiKo** [ffxiv-teamcraft/ffxiv-teamcraft#902]
**Is your feature request related to a problem? Please describe.**

I spend way too much time going back and forth between the list view and the simulation view, when all I need is just know what the result of the simulation is.

**Describe the solution you'd like**
Being able to launch a simulation from the list, only seing the result (solidity & quality bars and values (ideally with collectible marks)) in a modal to not leave the list view.

**Describe alternatives you've considered**
Opening the complete simulator view as a modal so that it can be easily closed without losing the state of the list view?

**Additional context**
Feel free to ask if needed

**Comment by Supamiu** [comment]
I'm closing this as it's implemented by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/318beb361663723c472333ee49ae27d8b3704652
