### ISSUE TITLE
DB: Missing data types

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#906]
This issue is meant to submit missing data types inside the beta database system.

If you want to report some of these, please follow the pattern below:

```
**Link to the item**: https://beta.ffxivteamcraft.com/db/en/item/....
**Missing data**: <Short description of what's missing>
```

See the first comments for examples.

Edit: comments where I add 🚀 reaction are the ones I handled.

**Comment by Supamiu** [comment]
**Link to the item**: https://beta.ffxivteamcraft.com/db/en/item/16172/Silver-trimmed-Sack
**Missing data**: Comes from PotD

----------------------------------

**Link to the item**: https://beta.ffxivteamcraft.com/db/en/item/20545/Wind-up-Susano
**Missing data**: Used to unlock a minion (track on external tool?)

**Comment by BanWiz** [comment]
**Link to the item**: https://beta.ffxivteamcraft.com/db/ru/item/16564/Night-Pegasus-Whistle
**Missing data**: Comes from gold-trimmed sacks from PotD

**Comment by BanWiz** [comment]
Link to the item: https://beta.ffxivteamcraft.com/db/ru/item/21907/Tyrannosaur-Horn
Missing data: Comes from lootboxes from Eureka
