### ISSUE TITLE
feat: offline lists

### ISSUE THREAD

**Issue by Supamiu** [ffxiv-teamcraft/ffxiv-teamcraft#922]
**Is your feature request related to a problem? Please describe.**
When trying to create very large lists, the website becomes slower and goes slower and slower with new items added to the list.

**Describe the solution you'd like**
As the slowness comes from the fact that the list is connected to a realtime database, having a way to create "offline" lists could be nice.

**Describe alternatives you've considered**
Splitting the list in multiple ones.

**Additional context**
Would only be on desktop app, as it needs file system to handle big lists, or evaluate LocalStorage for this, without reaching its limits.

**Comment by ayyaruq** [comment]
Def in favour of LocalStorage, even if it's only in desktop app, since that uses the filesystem anyway and could later be extended to browser too.
