### ISSUE TITLE
bug: (Flexbox) Style addition upon Levels update in Levequests breaks layout.

### ISSUE THREAD

**Issue by Jockie14** [ffxiv-teamcraft/ffxiv-teamcraft#965]
**Describe the bug**
When assigning a job and updating the levels in the Levequests menu, the following style gets added to the container: `style="flex-direction: row; box-sizing: border-box; display: flex;"`

This causes the leves to be displayed in columns instead of rows.

**To Reproduce**
1. Go to Levequests
2. Select any Job
3. Update the Level numbers
4. Let it update

**Expected behavior**
The flexbox style of the container should remain the same upon updating search values.

**Screenshots**
![firefox_2019-06-12_22-33-35](https://user-images.githubusercontent.com/10798439/59385654-1da3d400-8d65-11e9-969f-87f29baa6654.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox 67.0.2 & Chrome 75.0.3770.80
 - FFXIV Teamcraft v5.4.17 - Browser

**Comment by Supamiu** [comment]
Fixed by https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/commit/d15dcaff018e3ad95f193d55015340e6641ff71e , will be inside today's patch (5.5.0)
