### ISSUE TITLE
Feat: Able to pull in fish info from FF14Angler

### ISSUE THREAD

**Issue by Hinalover** [ffxiv-teamcraft/ffxiv-teamcraft#987]
*please prefix the issue with "feat:", example: "feat: commission board system"*

**Is your feature request related to a problem? Please describe.**
No.

This request is just seeing if it is possible to pull additional information from a site dedicated to fishing. This includes lure information, better display on when fishes are available, etc. 

IE: Namitaro: http://ff14angler.com/fish/311

I'm not sure what API information FF14Angler can provide, if any but it is worth making the suggestion.

**Comment by Supamiu** [comment]
Hello, thank you for your suggestion 😄 

Sadly, I want this too but ff14angler provides 0 API at all, all we have is manual data reported in a sheet, data we read from ff14angler, or from other sources, to input the best bait/weather/time combination for all of the fishes in the game.

I'm going to keep this issue opened with a "waiting for 3rd party update" just in case this API happens some day, but as the authors are japanese and to not seem to speak english, it's hard for me to communicate with them :/

**Comment by Supamiu** [comment]
This will most likely never be done, I'm going to implement our own data parser for fishing instead.
